// <auto-generated />
// 全局命名空间：Godot 示例项目共用的隐式 using。
// 由 GlobalUsings.cs 集中管理，避免每个文件重复引入同一组命名空间。

global using global::System;
global using global::System.Collections.Generic;
global using global::System.Threading;
global using global::System.Threading.Tasks;
global using global::MiKiNuo.Mvi.Platforms.Godot.Binding;
global using global::MiKiNuo.Mvi.Platforms.Godot.Composition;
global using global::MiKiNuo.Mvi.Samples.Godot.Composition;
global using global::MiKiNuo.Mvi.Samples.Godot.Features.AppShell;
global using global::MiKiNuo.Mvi.Samples.Godot.Features.Common;
global using global::MiKiNuo.Mvi.Samples.Godot.Features.Lobby;
global using global::MiKiNuo.Mvi.Samples.Godot.Features.Login;
