using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace MiKiNuo.Mvi.SourceGen.ViewModels;

/// <summary>
/// 生成 MVI ViewModel 绑定成员。
/// </summary>
[Generator]
public sealed class MviViewModelBindingGenerator : IIncrementalGenerator
{
    private const string ViewModelAttributeMetadataName = "MiKiNuo.Mvi.Abstractions.Binding.MviViewModelAttribute";
    private const string StateBindingAttributeMetadataName = "MiKiNuo.Mvi.Abstractions.Binding.MviStateBindingAttribute";
    private const string TwoWayBindingAttributeMetadataName = "MiKiNuo.Mvi.Abstractions.Binding.MviTwoWayBindingAttribute";
    private const string CommandAttributeMetadataName = "MiKiNuo.Mvi.Abstractions.Binding.MviCommandAttribute";

    /// <inheritdoc />
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var viewModels = context.SyntaxProvider.ForAttributeWithMetadataName(
            ViewModelAttributeMetadataName,
            static (node, _) => node is ClassDeclarationSyntax,
            static (generatorContext, _) => ViewModelModel.From(generatorContext))
            .Where(static model => model is not null);

        context.RegisterSourceOutput(viewModels, static (sourceProductionContext, model) =>
        {
            if (model is null || (model.Bindings.Count == 0 && model.Commands.Count == 0))
            {
                return;
            }

            sourceProductionContext.AddSource(
                $"{model.TypeName}.Binding.g.cs",
                SourceText.From(Render(model), Encoding.UTF8));
        });
    }

    private static string Render(ViewModelModel model)
    {
        var bindingFields = string.Join("\n", model.Bindings.Select(binding =>
            $"    private {binding.PropertyTypeName} {binding.FieldName} = default!;"));
        var commandFields = string.Join("\n", model.Commands.Select(command =>
            $"    private readonly MviIntentCommand<{model.TypeName}, {model.IntentTypeName}> {command.FieldName};"));
        var fields = JoinNonEmpty("\n", bindingFields, commandFields);
        var commandInitializers = string.Join("\n\n", model.Commands.Select(command => RenderCommandInitializer(model, command)));
        var bindingProperties = string.Join("\n\n", model.Bindings.Select(RenderBindingProperty));
        var commandProperties = string.Join("\n\n", model.Commands.Select(command =>
            $$"""
                /// <inheritdoc />
                public partial ICommand {{command.PropertyName}} => {{command.FieldName}};
            """));
        var properties = JoinNonEmpty("\n\n", bindingProperties, commandProperties);
        var applyCalls = string.Join("\n", model.Bindings.Select(binding =>
            $"        Set{binding.PropertyName}FromState(state.{binding.StatePropertyName});"));
        var setters = string.Join("\n\n", model.Bindings.Select(binding => RenderStateSetter(model, binding)));

        return $$"""
            // <auto-generated />
            #nullable enable

            using System.Collections.Generic;
            using System.Windows.Input;
            using MiKiNuo.Mvi.Core.Commands;
            using MiKiNuo.Mvi.Core.Store;

            namespace {{model.NamespaceName}};

            /// <summary>
            /// Auto：由 MiKiNuo.Mvi.SourceGen 自动生成，请勿手动修改。
            /// </summary>
            public sealed partial class {{model.TypeName}}
            {
            {{fields}}

                /// <summary>
                /// 初始化 {{model.TypeName}}。
                /// </summary>
                /// <param name="store">MVI 状态容器。</param>
                public {{model.TypeName}}(IMviStore<{{model.StateTypeName}}, {{model.IntentTypeName}}, {{model.EffectTypeName}}> store)
                    : base(store)
                {
            {{commandInitializers}}
                }

            {{properties}}

                /// <inheritdoc />
                protected override void ApplyStateCore({{model.StateTypeName}} state)
                {
            {{applyCalls}}
                }

            {{setters}}
            }
            """;
    }

    private static string RenderCommandInitializer(ViewModelModel model, CommandModel command)
    {
        var canExecute = command.CanExecuteStatePropertyName is null
            ? "null"
            : $"static viewModel => viewModel.{command.CanExecuteStatePropertyName}";
        return $$"""
                    {{command.FieldName}} = new MviIntentCommand<{{model.TypeName}}, {{model.IntentTypeName}}>(
                        this,
                        static viewModel => viewModel.DispatchAsync(new {{command.IntentTypeName}}()).AsTask(),
                        {{canExecute}});
        """;
    }

    private static string RenderBindingProperty(BindingModel binding)
    {
        if (binding.IntentTypeName is null)
        {
            return $$"""
                /// <inheritdoc />
                public partial {{binding.PropertyTypeName}} {{binding.PropertyName}} => {{binding.FieldName}};
            """;
        }

        return $$"""
            /// <inheritdoc />
            public partial {{binding.PropertyTypeName}} {{binding.PropertyName}}
            {
                get => {{binding.FieldName}};
                set
                {
                    if (EqualityComparer<{{binding.PropertyTypeName}}>.Default.Equals({{binding.FieldName}}, value))
                    {
                        return;
                    }

                    _ = DispatchAsync(new {{binding.IntentTypeName}}(value));
                }
            }
            """;
    }

    private static string RenderStateSetter(ViewModelModel model, BindingModel binding)
    {
        var commandNotifications = string.Join("\n", model.Commands
            .Where(command => command.CanExecuteStatePropertyName == binding.StatePropertyName || command.CanExecuteStatePropertyName == binding.PropertyName)
            .Select(command => $"        {command.FieldName}.RaiseCanExecuteChanged();"));

        return $$"""
            private void Set{{binding.PropertyName}}FromState({{binding.PropertyTypeName}} value)
            {
                if (EqualityComparer<{{binding.PropertyTypeName}}>.Default.Equals({{binding.FieldName}}, value))
                {
                    return;
                }

                {{binding.FieldName}} = value;
                RaisePropertyChanged(nameof({{binding.PropertyName}}));
            {{commandNotifications}}
            }
            """;
    }

    private sealed class ViewModelModel
    {
        public ViewModelModel(
            string namespaceName,
            string typeName,
            string stateTypeName,
            string intentTypeName,
            string effectTypeName,
            IReadOnlyList<BindingModel> bindings,
            IReadOnlyList<CommandModel> commands)
        {
            NamespaceName = namespaceName;
            TypeName = typeName;
            StateTypeName = stateTypeName;
            IntentTypeName = intentTypeName;
            EffectTypeName = effectTypeName;
            Bindings = bindings;
            Commands = commands;
        }

        public string NamespaceName { get; }

        public string TypeName { get; }

        public string StateTypeName { get; }

        public string IntentTypeName { get; }

        public string EffectTypeName { get; }

        public IReadOnlyList<BindingModel> Bindings { get; }

        public IReadOnlyList<CommandModel> Commands { get; }

        public static ViewModelModel? From(GeneratorAttributeSyntaxContext context)
        {
            if (context.TargetSymbol is not INamedTypeSymbol typeSymbol)
            {
                return null;
            }

            var baseType = FindMviViewModelBase(typeSymbol);
            if (baseType is null || baseType.TypeArguments.Length != 3)
            {
                return null;
            }

            var properties = typeSymbol.GetMembers().OfType<IPropertySymbol>().ToArray();
            var bindings = properties
                .Select(property => BindingModel.From(property, typeSymbol))
                .Where(binding => binding is not null)
                .Cast<BindingModel>()
                .ToArray();
            var commands = properties
                .Select(property => CommandModel.From(property, typeSymbol))
                .Where(command => command is not null)
                .Cast<CommandModel>()
                .ToArray();

            return new ViewModelModel(
                GetNamespaceName(typeSymbol),
                typeSymbol.Name,
                GetTypeName(baseType.TypeArguments[0], typeSymbol),
                GetTypeName(baseType.TypeArguments[1], typeSymbol),
                GetTypeName(baseType.TypeArguments[2], typeSymbol),
                bindings,
                commands);
        }

        private static INamedTypeSymbol? FindMviViewModelBase(INamedTypeSymbol typeSymbol)
        {
            var current = typeSymbol.BaseType;
            while (current is not null)
            {
                if (current.OriginalDefinition.MetadataName == "MviViewModelBase`3" &&
                    current.OriginalDefinition.ContainingNamespace.ToDisplayString() == "MiKiNuo.Mvi.Core.ViewModels")
                {
                    return current;
                }

                current = current.BaseType;
            }

            return null;
        }
    }

    private sealed class BindingModel
    {
        public BindingModel(
            string propertyName,
            string propertyTypeName,
            string statePropertyName,
            string fieldName,
            string? intentTypeName)
        {
            PropertyName = propertyName;
            PropertyTypeName = propertyTypeName;
            StatePropertyName = statePropertyName;
            FieldName = fieldName;
            IntentTypeName = intentTypeName;
        }

        public string PropertyName { get; }

        public string PropertyTypeName { get; }

        public string StatePropertyName { get; }

        public string FieldName { get; }

        public string? IntentTypeName { get; }

        public static BindingModel? From(IPropertySymbol propertySymbol, INamedTypeSymbol containingType)
        {
            var stateAttribute = propertySymbol.GetAttributes().FirstOrDefault(attributeData =>
                attributeData.AttributeClass?.ToDisplayString() == StateBindingAttributeMetadataName);
            if (stateAttribute?.ConstructorArguments.Length == 1 &&
                stateAttribute.ConstructorArguments[0].Value is string statePropertyName)
            {
                return new BindingModel(
                    propertySymbol.Name,
                    propertySymbol.Type.ToDisplayString(SymbolDisplayFormat.MinimallyQualifiedFormat),
                    statePropertyName,
                    ToCamelCase(propertySymbol.Name),
                    null);
            }

            var twoWayAttribute = propertySymbol.GetAttributes().FirstOrDefault(attributeData =>
                attributeData.AttributeClass?.ToDisplayString() == TwoWayBindingAttributeMetadataName);
            if (twoWayAttribute?.ConstructorArguments.Length == 2 &&
                twoWayAttribute.ConstructorArguments[0].Value is string twoWayStatePropertyName &&
                twoWayAttribute.ConstructorArguments[1].Value is INamedTypeSymbol intentType)
            {
                return new BindingModel(
                    propertySymbol.Name,
                    propertySymbol.Type.ToDisplayString(SymbolDisplayFormat.MinimallyQualifiedFormat),
                    twoWayStatePropertyName,
                    ToCamelCase(propertySymbol.Name),
                    GetTypeName(intentType, containingType));
            }

            return null;
        }
    }

    private sealed class CommandModel
    {
        public CommandModel(
            string propertyName,
            string fieldName,
            string intentTypeName,
            string? canExecuteStatePropertyName)
        {
            PropertyName = propertyName;
            FieldName = fieldName;
            IntentTypeName = intentTypeName;
            CanExecuteStatePropertyName = canExecuteStatePropertyName;
        }

        public string PropertyName { get; }

        public string FieldName { get; }

        public string IntentTypeName { get; }

        public string? CanExecuteStatePropertyName { get; }

        public static CommandModel? From(IPropertySymbol propertySymbol, INamedTypeSymbol containingType)
        {
            var commandAttribute = propertySymbol.GetAttributes().FirstOrDefault(attributeData =>
                attributeData.AttributeClass?.ToDisplayString() == CommandAttributeMetadataName);
            if (commandAttribute?.ConstructorArguments.Length != 1 ||
                commandAttribute.ConstructorArguments[0].Value is not INamedTypeSymbol intentType)
            {
                return null;
            }

            var canExecuteStatePropertyName = commandAttribute.NamedArguments.FirstOrDefault(argument =>
                argument.Key == "CanExecuteStatePropertyName").Value.Value as string;

            return new CommandModel(
                propertySymbol.Name,
                ToCamelCase(propertySymbol.Name),
                GetTypeName(intentType, containingType),
                canExecuteStatePropertyName);
        }
    }

    private static string GetNamespaceName(INamedTypeSymbol typeSymbol)
    {
        return typeSymbol.ContainingNamespace.IsGlobalNamespace
            ? string.Empty
            : typeSymbol.ContainingNamespace.ToDisplayString();
    }

    private static string GetTypeName(ITypeSymbol typeSymbol, INamedTypeSymbol containingType)
    {
        if (SymbolEqualityComparer.Default.Equals(typeSymbol.ContainingNamespace, containingType.ContainingNamespace))
        {
            return typeSymbol.Name;
        }

        return typeSymbol.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat).Replace("global::", string.Empty);
    }

    private static string JoinNonEmpty(string separator, params string[] values)
    {
        return string.Join(separator, values.Where(value => !string.IsNullOrWhiteSpace(value)));
    }

    private static string ToCamelCase(string value)
    {
        if (string.IsNullOrEmpty(value) || char.IsLower(value[0]))
        {
            return value;
        }

        return char.ToLowerInvariant(value[0]) + value.Substring(1);
    }
}
