using System.Collections.Generic;
using System.Linq;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace MiKiNuo.Mvi.Samples.Avalonia.BuildTime.SourceGeneration;

public sealed partial class AvaloniaSampleDiContainerGenerator
{
    private static string GenerateContainerSource(
        GenerationModel model,
        string containerName)
    {
        FeatureInfo login = model.LoginFeature!;
        FeatureInfo shell = model.ShellFeature!;
        FeatureInfo? dashboard = model.GetFeature("Dashboard");

        StringBuilder builder = new StringBuilder();

        EmitFileHeader(builder, model, containerName);
        EmitContainerFields(builder, model, dashboard);
        EmitConstructor(builder, model, containerName, login, shell, dashboard);
        EmitResolveMethod(builder, containerName);
        EmitCreateWithMethod(builder, model);
        EmitMediatorMethod(builder, model, shell, dashboard);
        AppendResolveCore(builder, model, containerName, login, shell, dashboard);
        EmitStoreMethods(builder, model, login, shell);
        EmitDashboardMethods(builder, model, dashboard);
        EmitViewRegistryMethod(builder, model, containerName);
        EmitPageFactoryMethod(builder, model, login, dashboard);
        EmitScopeClass(builder, containerName, login);

        builder.AppendLine("}");
        return builder.ToString();
    }

    /// <summary>生成文件头：using、namespace、类声明。</summary>
    private static void EmitFileHeader(StringBuilder builder, GenerationModel model, string containerName)
    {
        builder.AppendLine("// <auto-generated />");
        builder.AppendLine("#nullable enable");
        builder.AppendLine();
        builder.AppendLine("using System;");
        builder.AppendLine("using System.Collections.Generic;");
        builder.AppendLine("using System.Threading;");
        builder.AppendLine("using System.Threading.Tasks;");
        builder.AppendLine("using MiKiNuo.Mvi.Application.DI;");
        builder.AppendLine("using MiKiNuo.Mvi.Application.MVI.Diagnostics;");
        builder.AppendLine("using MiKiNuo.Mvi.Application.MVI.Mediator;");
        builder.AppendLine("using MiKiNuo.Mvi.Application.MVI.Middleware;");
        builder.AppendLine("using MiKiNuo.Mvi.Application.MVI.Store;");
        builder.AppendLine("using MiKiNuo.Mvi.Application.MVI.Threading;");
        builder.AppendLine("using MiKiNuo.Mvi.Domain.DI;");
        builder.AppendLine("using MiKiNuo.Mvi.Presentation.ViewRegistry;");
        builder.Append("using ").Append(model.CompositionNamespace).Append(';').AppendLine();
        builder.AppendLine();
        builder.Append("namespace ").Append(model.CompositionNamespace).AppendLine(";");
        builder.AppendLine();
        builder.AppendLine("/// <summary>");
        builder.AppendLine("/// 表示由源生成器生成的示例组合容器。");
        builder.AppendLine("/// 容器自身同时实现 <c>IMviViewRegistry</c> 与 <c>IDashboardPageFactory</c>：");
        builder.AppendLine("/// 避免为视图解析与页面分发单独生成无业务逻辑的「壳」类，");
        builder.AppendLine("/// 让组合根成为 ViewModel/View/Page 之间的唯一桥接点。");
        builder.AppendLine("/// </summary>");
        builder.Append("public sealed class ").Append(containerName)
            .Append(" : IMviResolver, IMviServiceGraph, IMviMediator, IMviDiagnosticSink, IMviViewRegistry");
        if (model.DashboardPageFactoryTypeName is not null)
        {
            builder.Append(", ").Append(model.DashboardPageFactoryTypeName);
        }

        if (model.ShellPageFactoryTypeName is not null)
        {
            builder.Append(", ").Append(model.ShellPageFactoryTypeName);
        }

        if (model.LoginNavigationService is not null)
        {
            builder.Append(", ").Append(Format(model.LoginNavigationService));
        }

        builder.AppendLine();
        builder.AppendLine("{");
    }

    /// <summary>生成容器字段声明。</summary>
    private static void EmitContainerFields(StringBuilder builder, GenerationModel model, FeatureInfo? dashboard)
    {
        builder.AppendLine("    private readonly Dictionary<Type, object> _singletons = new();");
        builder.AppendLine("    private readonly IReadOnlyList<MviServiceDescriptor> _serviceDescriptors;");
        // Avalonia 平台专用 UI 调度器单例；所有 ViewModel 与 CardStoreFactory 共用同一实例，
        // 确保 PropertyChanged/CanExecuteChanged 都能 marshal 到 Avalonia UI 线程。
        builder.AppendLine("    private IMviUiDispatcher? _uiDispatcher;");
        builder.AppendLine("    private IMviUiDispatcher ResolveUiDispatcher() => _uiDispatcher ??= new global::MiKiNuo.Mvi.Platforms.Avalonia.Threading.AvaloniaMviUiDispatcher();");
        builder.AppendLine();

        if (dashboard is not null)
        {
            builder.Append("    private ").Append(StoreType(dashboard)).AppendLine("? _dashboardStore;");
            builder.Append("    private ").Append(dashboard.ViewModelTypeName).AppendLine("? _dashboardViewModel;");
        }

        FeatureInfo? fieldClinicalEditor = model.GetFeature("ClinicalEditor");
        FeatureInfo? fieldClinicalReminder = model.GetFeature("ClinicalReminder");
        FeatureInfo? fieldBusinessCompositePage = model.GetFeature("BusinessCompositePage");
        if (fieldClinicalEditor is not null)
        {
            builder.Append("    private ").Append(StoreType(fieldClinicalEditor)).AppendLine("? _clinicalEditorStore;");
        }
        if (fieldClinicalReminder is not null)
        {
            builder.Append("    private ").Append(StoreType(fieldClinicalReminder)).AppendLine("? _clinicalReminderStore;");
        }
        if (fieldBusinessCompositePage is not null)
        {
            builder.Append("    private ").Append(StoreType(fieldBusinessCompositePage)).AppendLine("? _businessCompositePageStore;");
        }

        if (model.CardStoreFactory is not null)
        {
            builder.Append("    private ").Append(model.CardStoreFactory.TypeName).AppendLine("? _cardStoreFactory;");
        }
    }

    /// <summary>生成构造函数与服务注册。</summary>
    private static void EmitConstructor(
        StringBuilder builder,
        GenerationModel model,
        string containerName,
        FeatureInfo login,
        FeatureInfo shell,
        FeatureInfo? dashboard)
    {
        builder.AppendLine();
        builder.AppendLine("    /// <summary>");
        builder.AppendLine("    /// 初始化由源生成器生成的示例组合容器。");
        builder.AppendLine("    /// </summary>");
        builder.Append("    public ").Append(containerName).AppendLine("()");
        builder.AppendLine("    {");
        builder.AppendLine("        _serviceDescriptors = new MviServiceDescriptor[]");
        builder.AppendLine("        {");
        AppendDescriptor(builder, model.AuthService?.ServiceTypeName, model.AuthService?.ImplementationTypeName, "Singleton");
        if (model.LoginNavigationService is not null)
        {
            AppendDescriptor(builder, Format(model.LoginNavigationService), containerName, "Singleton");
        }

        if (model.ShellPageFactoryTypeName is not null)
        {
            AppendDescriptor(builder, model.ShellPageFactoryTypeName, containerName, "Singleton");
        }

        AppendDescriptor(builder, "global::MiKiNuo.Mvi.Application.MVI.Mediator.IMviMediator", containerName, "Singleton");
        AppendDescriptor(builder, "global::MiKiNuo.Mvi.Application.MVI.Diagnostics.IMviDiagnosticSink", containerName, "Singleton");
        AppendDescriptor(builder, "global::MiKiNuo.Mvi.Presentation.ViewRegistry.IMviViewRegistry", containerName, "Singleton");
        AppendDescriptor(builder, shell.ViewModelTypeName, shell.ViewModelTypeName, "Singleton");
        AppendDescriptor(builder, login.ViewModelTypeName, login.ViewModelTypeName, "Scoped");
        AppendDescriptor(builder, StoreType(login), "global::MiKiNuo.Mvi.Application.MVI.Store.MviStore<" + login.StateTypeName + ", " + login.IntentTypeName + ", " + login.EffectTypeName + ">", "Scoped");
        AppendDescriptor(builder, ReducerInterfaceType(login), login.ReducerTypeName, "Scoped");
        if (dashboard is not null)
        {
            AppendDescriptor(builder, dashboard.ViewModelTypeName, dashboard.ViewModelTypeName, "Singleton");
            if (model.DashboardPageFactoryTypeName is not null)
            {
                AppendDescriptor(builder, model.DashboardPageFactoryTypeName, containerName, "Singleton");
            }
        }

        builder.AppendLine("        };");
        builder.AppendLine("    }");
    }

    /// <summary>生成 Resolve 与 CreateScope 方法。</summary>
    private static void EmitResolveMethod(StringBuilder builder, string containerName)
    {
        builder.AppendLine();
        builder.AppendLine("    /// <summary>");
        builder.AppendLine("    /// 获取服务描述集合。");
        builder.AppendLine("    /// </summary>");
        builder.AppendLine("    public IReadOnlyList<MviServiceDescriptor> ServiceDescriptors => _serviceDescriptors;");
        builder.AppendLine();
        builder.AppendLine("    /// <summary>");
        builder.AppendLine("    /// 解析服务。");
        builder.AppendLine("    /// </summary>");
        builder.AppendLine("    /// <typeparam name=\"TService\">服务类型。</typeparam>");
        builder.AppendLine("    /// <returns>服务实例。</returns>");
        builder.AppendLine("    public TService Resolve<TService>()");
        builder.AppendLine("        where TService : notnull");
        builder.AppendLine("    {");
        builder.AppendLine("        return (TService)Resolve(typeof(TService));");
        builder.AppendLine("    }");
        builder.AppendLine();
        builder.AppendLine("    /// <summary>");
        builder.AppendLine("    /// 解析指定类型的服务。");
        builder.AppendLine("    /// </summary>");
        builder.AppendLine("    /// <param name=\"serviceType\">服务类型。</param>");
        builder.AppendLine("    /// <returns>服务实例。</returns>");
        builder.AppendLine("    public object Resolve(Type serviceType)");
        builder.AppendLine("    {");
        builder.AppendLine("        ArgumentNullException.ThrowIfNull(serviceType);");
        builder.AppendLine("        return ResolveCore(serviceType);");
        builder.AppendLine("    }");
        builder.AppendLine();
        builder.AppendLine("    /// <summary>");
        builder.AppendLine("    /// 创建作用域。");
        builder.AppendLine("    /// </summary>");
        builder.AppendLine("    /// <returns>服务作用域。</returns>");
        builder.AppendLine("    public IMviScope CreateScope()");
        builder.AppendLine("    {");
        builder.Append("        return new ").Append(containerName).AppendLine("Scope(this);");
        builder.AppendLine("    }");
    }

    /// <summary>生成 CreateWith 与 Record 方法。</summary>
    private static void EmitCreateWithMethod(StringBuilder builder, GenerationModel model)
    {
        builder.AppendLine();
        builder.AppendLine("    /// <summary>");
        builder.AppendLine("    /// 按构造参数即时构造服务实例。");
        builder.AppendLine("    /// </summary>");
        builder.AppendLine("    /// <typeparam name=\"TService\">服务类型。</typeparam>");
        builder.AppendLine("    /// <param name=\"args\">构造函数实参。</param>");
        builder.AppendLine("    /// <returns>新构造的实例。</returns>");
        builder.AppendLine("    public TService CreateWith<TService>(params object[] args)");
        builder.AppendLine("        where TService : notnull");
        builder.AppendLine("    {");
        builder.AppendLine("        if (args is null)");
        builder.AppendLine("        {");
        builder.AppendLine("            throw new ArgumentNullException(nameof(args));");
        builder.AppendLine("        }");
        builder.AppendLine();
        builder.AppendLine("        return (TService)CreateWithCore(typeof(TService), args);");
        builder.AppendLine("    }");
        builder.AppendLine();
        AppendCreateWithCore(builder, model);
        builder.AppendLine("    /// <summary>");
        builder.AppendLine("    /// 记录诊断条目。");
        builder.AppendLine("    /// </summary>");
        builder.AppendLine("    /// <param name=\"entry\">诊断条目。</param>");
        builder.AppendLine("    public void Record(MviDiagnosticEntry entry)");
        builder.AppendLine("    {");
        builder.AppendLine("        ArgumentNullException.ThrowIfNull(entry);");
        builder.AppendLine("    }");
        builder.AppendLine();
    }

    /// <summary>生成 IMviMediator 实现相关方法。</summary>
    private static void EmitMediatorMethod(StringBuilder builder, GenerationModel model, FeatureInfo shell, FeatureInfo? dashboard)
    {
        if (model.LoginNavigationService is not null)
        {
            AppendNavigateToDashboard(builder, shell, dashboard);
        }

        FeatureInfo? mediatorClinicalEditor = model.GetFeature("ClinicalEditor");
        FeatureInfo? mediatorClinicalReminder = model.GetFeature("ClinicalReminder");
        FeatureInfo? mediatorBusinessCompositePage = model.GetFeature("BusinessCompositePage");
        AppendMediator(builder, dashboard, mediatorClinicalEditor, mediatorClinicalReminder, mediatorBusinessCompositePage);
    }

    /// <summary>生成 Store 工厂方法。</summary>
    private static void EmitStoreMethods(StringBuilder builder, GenerationModel model, FeatureInfo login, FeatureInfo shell)
    {
        AppendStoreHelpers(builder, model, login, shell);
        AppendCardStoreFactoryResolver(builder, model);
    }

    /// <summary>生成 Dashboard 相关方法。</summary>
    private static void EmitDashboardMethods(StringBuilder builder, GenerationModel model, FeatureInfo? dashboard)
    {
        AppendDashboardHelpers(builder, model, dashboard);
        AppendDashboardPageFactory(builder, model, dashboard);
    }

    /// <summary>生成 ViewRegistry 方法。</summary>
    private static void EmitViewRegistryMethod(StringBuilder builder, GenerationModel model, string containerName)
    {
        AppendViewRegistryImplementation(builder, model, containerName);
    }

    /// <summary>生成 PageFactory 方法。</summary>
    private static void EmitPageFactoryMethod(StringBuilder builder, GenerationModel model, FeatureInfo login, FeatureInfo? dashboard)
    {
        AppendShellPageFactory(builder, model, login, dashboard);
    }

    /// <summary>生成作用域类。</summary>
    private static void EmitScopeClass(StringBuilder builder, string containerName, FeatureInfo login)
    {
        AppendScope(builder, containerName, login);
    }
}
