using System.Collections.Generic;
using System.Linq;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace MiKiNuo.Mvi.Samples.Avalonia.BuildTime.SourceGeneration;

public sealed partial class AvaloniaSampleDiContainerGenerator
{
    private static string GenerateViewRegistryForwarder(
        GenerationModel model,
        string containerName,
        string registryName)
    {
        // 容器已直接实现 IMviViewRegistry（参见 AppendViewRegistryImplementation）。
        // 此处仍生成一个 *GeneratedViewRegistry 兼容类，
        // 让 `Resolve<IMviViewRegistry>()` 之外仍然存在一个可独立 new 出来的壳，
        // 用于旧测试与第三方集成。所有方法 forward 到容器同一实例，避免双份路由表。
        StringBuilder builder = new StringBuilder();

        builder.AppendLine("// <auto-generated />");
        builder.AppendLine("#nullable enable");
        builder.AppendLine();
        builder.AppendLine("using System;");
        builder.AppendLine("using MiKiNuo.Mvi.Presentation.ViewRegistry;");
        builder.Append("using ").Append(model.CompositionNamespace).Append(';').AppendLine();
        builder.AppendLine();
        builder.Append("namespace ").Append(model.CompositionNamespace).AppendLine(";");
        builder.AppendLine();
        builder.AppendLine("/// <summary>");
        builder.AppendLine("/// 表示由源生成器生成的 Avalonia 视图注册表兼容壳。");
        builder.Append("/// 路由表实际由 <see cref=\"").Append(containerName).AppendLine("\"/> 持有；");
        builder.AppendLine("/// 本类仅 forward <c>CreateView</c>，避免父 VM 长期持有子 VM 引用同时维护双份路由表。");
        builder.AppendLine("/// </summary>");
        builder.Append("public sealed class ").Append(registryName).AppendLine(" : IMviViewRegistry");
        builder.AppendLine("{");
        builder.Append("    private readonly ").Append(containerName).AppendLine(" _container;");
        builder.AppendLine();
        builder.Append("    public ").Append(registryName).Append('(').Append(containerName).AppendLine(" container)");
        builder.AppendLine("    {");
        builder.AppendLine("        ArgumentNullException.ThrowIfNull(container);");
        builder.AppendLine("        _container = container;");
        builder.AppendLine("    }");
        builder.AppendLine();
        builder.AppendLine("    /// <summary>");
        builder.AppendLine("    /// 创建平台视图对象。");
        builder.AppendLine("    /// </summary>");
        builder.AppendLine("    /// <param name=\"viewModel\">视图模型。</param>");
        builder.AppendLine("    /// <returns>平台视图对象。</returns>");
        builder.AppendLine("    public object CreateView(object viewModel)");
        builder.AppendLine("    {");
        builder.AppendLine("        ArgumentNullException.ThrowIfNull(viewModel);");
        builder.AppendLine("        return _container.CreateView(viewModel);");
        builder.AppendLine("    }");
        builder.AppendLine("}");

        return builder.ToString();
    }

    /// <summary>
    /// 在容器类内部追加 <c>IMviViewRegistry.CreateView(object)</c> 的实现：
    /// 走 switch-case 把 ViewModel 解析为对应 View 实例，调用 <c>view.Bind(viewModel)</c> 后返回。
    /// <para>
    /// View 构造可能依赖 <c>IMviViewRegistry</c> 自身（用于递归嵌入场景，例如 <c>BusinessCompositePageView</c> 内部子槽位），
    /// 此类 View 已在 <see cref="ViewInfo.ConstructorKind"/> 标记，构造时把 <c>this</c> 传入。
    /// </para>
    /// </summary>
    private static void AppendViewRegistryImplementation(
        StringBuilder builder,
        GenerationModel model,
        string containerName)
    {
        builder.AppendLine("    /// <summary>");
        builder.AppendLine("    /// 创建平台视图对象。");
        builder.AppendLine("    /// </summary>");
        builder.AppendLine("    /// <param name=\"viewModel\">视图模型。</param>");
        builder.AppendLine("    /// <returns>平台视图对象。</returns>");
        builder.AppendLine("    public object CreateView(object viewModel)");
        builder.AppendLine("    {");
        builder.AppendLine("        ArgumentNullException.ThrowIfNull(viewModel);");
        builder.AppendLine();
        EmitViewRegistrySwitch(builder, model);
        builder.AppendLine("    }");
        builder.AppendLine();
        EmitViewConstruction(builder, model);
    }

    /// <summary>生成 CreateView 的 switch-case 分发逻辑。</summary>
    private static void EmitViewRegistrySwitch(StringBuilder builder, GenerationModel model)
    {
        builder.AppendLine("        switch (viewModel)");
        builder.AppendLine("        {");

        for (int index = 0; index < model.Views.Count; index++)
        {
            ViewInfo view = model.Views[index];
            builder.Append("            case ").Append(view.ViewModelTypeName).Append(" viewModel").Append(index).AppendLine(":");
            builder.Append("                return CreateView").Append(index).Append("(viewModel").Append(index).AppendLine(");");
        }

        builder.AppendLine("            default:");
        builder.AppendLine("                throw new MviViewNotFoundException(viewModel.GetType());");
        builder.AppendLine("        }");
    }

    /// <summary>生成各 View 的具体构造调用方法。</summary>
    private static void EmitViewConstruction(StringBuilder builder, GenerationModel model)
    {
        for (int index = 0; index < model.Views.Count; index++)
        {
            ViewInfo view = model.Views[index];
            // 所有 CreateView* 方法统一为实例方法：必须能访问 this 才能在 2-arg Bind 重载中
            // 传入解析器（容器自身就是 IMviResolver），以触发 View 的 OnBindSlots 钩子。
            // 即便 View 本身是无参构造、可以走 static 优化，也必须为实例方法以支持槽位绑定。
            builder.Append("    private ")
                .Append(view.ViewTypeName).Append(" CreateView").Append(index)
                .Append('(').Append(view.ViewModelTypeName).AppendLine(" viewModel)");
            builder.AppendLine("    {");
            builder.Append("        ").Append(view.ViewTypeName).Append(" view = new(");
            bool needsComma = false;
            if (view.ConstructorKind == ViewConstructorKind.Registry
                || view.ConstructorKind == ViewConstructorKind.RegistryAndCardStoreFactory)
            {
                builder.Append("this");
                needsComma = true;
            }

            if (view.ConstructorKind == ViewConstructorKind.RegistryAndCardStoreFactory)
            {
                if (needsComma)
                {
                    builder.Append(", ");
                }

                builder.Append("ResolveCardStoreFactory()");
            }

            builder.AppendLine(");");
            // 走 2-arg Bind 重载以触发 MviAvaloniaView<T>.OnBindSlots 钩子：
            // 否则带 [MviSlot] 字段的 View（DashboardView / OutpatientWorkstationView /
            // BusinessCompositePageView / EventBindingWorkbenchView）的 MviSlotHost
            // 永远不会被填入子 View，左侧菜单 / 头部 / 当前页面均为空。
            // 容器自身实现 IMviViewRegistry 又是 IMviResolver，this 即可作为解析器；
            // View 构造已按 ViewConstructorKind 决定是否需要把 this 传进去（递归嵌入场景）。
            builder.AppendLine("        view.Bind(viewModel, this);");
            builder.AppendLine("        return view;");
            builder.AppendLine("    }");
            builder.AppendLine();
        }
    }
}
