using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace MiKiNuo.Mvi.SourceGen.Registry;

/// <summary>
/// 生成 MVI View 注册表。
/// </summary>
[Generator]
public sealed class MviViewRegistryGenerator : IIncrementalGenerator
{
    private const string ViewRegistryAttributeMetadataName = "MiKiNuo.Mvi.Abstractions.Generation.MviViewRegistryAttribute";

    /// <inheritdoc />
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var registries = context.SyntaxProvider.ForAttributeWithMetadataName(
            ViewRegistryAttributeMetadataName,
            static (node, _) => node is ClassDeclarationSyntax,
            static (generatorContext, _) => RegistryModel.From(generatorContext))
            .Where(static model => model is not null);

        context.RegisterSourceOutput(registries, static (sourceProductionContext, model) =>
        {
            if (model is null || model.Mappings.Count == 0)
            {
                return;
            }

            sourceProductionContext.AddSource(
                $"{model.TypeName}.Views.g.cs",
                SourceText.From(Render(model), Encoding.UTF8));
        });
    }

    private static string Render(RegistryModel model)
    {
        var cases = string.Join("\n", model.Mappings.Select(mapping =>
            $$"""
                    if (viewType == typeof({{mapping.ViewTypeName}}))
                    {
                        viewModelType = typeof({{mapping.ViewModelTypeName}});
                        return true;
                    }
            """));

        return $$"""
            // <auto-generated />
            #nullable enable

            using System;

            namespace {{model.NamespaceName}};

            /// <summary>
            /// Auto：由 MiKiNuo.Mvi.SourceGen 自动生成，请勿手动修改。
            /// </summary>
            public sealed partial class {{model.TypeName}}
            {
                /// <summary>
                /// 尝试获取 View 对应的 ViewModel 类型。
                /// </summary>
                public bool TryGetViewModelType(Type viewType, out Type? viewModelType)
                {
            {{cases}}
                    viewModelType = null;
                    return false;
                }
            }
            """;
    }

    private sealed class RegistryModel
    {
        public RegistryModel(string namespaceName, string typeName, IReadOnlyList<ViewMappingModel> mappings)
        {
            NamespaceName = namespaceName;
            TypeName = typeName;
            Mappings = mappings;
        }

        public string NamespaceName { get; }

        public string TypeName { get; }

        public IReadOnlyList<ViewMappingModel> Mappings { get; }

        public static RegistryModel? From(GeneratorAttributeSyntaxContext context)
        {
            if (context.TargetSymbol is not INamedTypeSymbol typeSymbol)
            {
                return null;
            }

            var mappings = typeSymbol.GetAttributes()
                .Where(attribute => attribute.AttributeClass?.ToDisplayString() == ViewRegistryAttributeMetadataName)
                .Select(attribute => ViewMappingModel.From(attribute, typeSymbol))
                .Where(mapping => mapping is not null)
                .Cast<ViewMappingModel>()
                .ToArray();

            return new RegistryModel(GetNamespaceName(typeSymbol), typeSymbol.Name, mappings);
        }
    }

    private sealed class ViewMappingModel
    {
        public ViewMappingModel(string viewTypeName, string viewModelTypeName)
        {
            ViewTypeName = viewTypeName;
            ViewModelTypeName = viewModelTypeName;
        }

        public string ViewTypeName { get; }

        public string ViewModelTypeName { get; }

        public static ViewMappingModel? From(AttributeData attributeData, INamedTypeSymbol containingType)
        {
            if (attributeData.ConstructorArguments.Length != 2 ||
                attributeData.ConstructorArguments[0].Value is not INamedTypeSymbol viewType ||
                attributeData.ConstructorArguments[1].Value is not INamedTypeSymbol viewModelType)
            {
                return null;
            }

            return new ViewMappingModel(
                GetTypeName(viewType, containingType),
                GetTypeName(viewModelType, containingType));
        }
    }

    private static string GetNamespaceName(INamedTypeSymbol typeSymbol)
    {
        return typeSymbol.ContainingNamespace.IsGlobalNamespace
            ? string.Empty
            : typeSymbol.ContainingNamespace.ToDisplayString();
    }

    private static string GetTypeName(ITypeSymbol typeSymbol, INamedTypeSymbol containingType)
    {
        if (SymbolEqualityComparer.Default.Equals(typeSymbol.ContainingNamespace, containingType.ContainingNamespace))
        {
            return typeSymbol.Name;
        }

        return typeSymbol.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat).Replace("global::", string.Empty);
    }
}
