<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <IsPackable>false</IsPackable>
    <TreatWarningsAsErrors>false</TreatWarningsAsErrors>
    <WarningsAsErrors></WarningsAsErrors>
    <EnforceExtendedAnalyzerRules>false</EnforceExtendedAnalyzerRules>
    <TestingPlatformCommandLineArguments>--maximum-parallel-tests 1</TestingPlatformCommandLineArguments>
    <NoWarn>$(NoWarn);CS1591</NoWarn>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../../src/MiKiNuo.Mvi/MiKiNuo.Mvi.csproj" />
    <ProjectReference Include="../../src/MiKiNuo.Mvi.Godot/MiKiNuo.Mvi.Godot.csproj" />
    <ProjectReference Include="../../src/MiKiNuo.Mvi.Generators/MiKiNuo.Mvi.Generators.csproj" OutputItemType="Analyzer" ReferenceOutputAssembly="true" />
    <PackageReference Include="TUnit" />
    <PackageReference Include="Microsoft.CodeAnalysis.CSharp" />
  </ItemGroup>
</Project>
