using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace MiKiNuo.Mvi.SourceGen.Middleware;

/// <summary>
/// 生成 MVI 中间件管线工厂。
/// </summary>
[Generator]
public sealed class MviMiddlewarePipelineGenerator : IIncrementalGenerator
{
    private const string MiddlewareAttributeMetadataName = "MiKiNuo.Mvi.Abstractions.Generation.MviMiddlewareAttribute";

    /// <inheritdoc />
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var middlewares = context.SyntaxProvider.ForAttributeWithMetadataName(
            MiddlewareAttributeMetadataName,
            static (node, _) => node is ClassDeclarationSyntax,
            static (generatorContext, _) => MiddlewareModel.From(generatorContext))
            .Where(static model => model is not null)
            .Collect();

        context.RegisterSourceOutput(middlewares, static (sourceProductionContext, models) =>
        {
            var groups = models
                .Where(model => model is not null)
                .Cast<MiddlewareModel>()
                .GroupBy(model => model.GroupKey);

            foreach (var group in groups)
            {
                var ordered = group.OrderBy(model => model.Order).ToArray();
                if (ordered.Length == 0)
                {
                    continue;
                }

                sourceProductionContext.AddSource(
                    $"{ordered[0].FeatureName}MiddlewarePipelineFactory.g.cs",
                    SourceText.From(Render(ordered), Encoding.UTF8));
            }
        });
    }

    private static string Render(IReadOnlyList<MiddlewareModel> middlewares)
    {
        var first = middlewares[0];
        var parameters = string.Join(",\n        ", new[] { $"MiKiNuo.Mvi.Core.Dispatching.IIntentDispatcher<{first.StateTypeName}, {first.IntentTypeName}, {first.EffectTypeName}> dispatcher" }
            .Concat(middlewares.Select(model => $"{model.TypeName} {model.FieldName}")));
        var arrayItems = string.Join(",\n            ", middlewares.Select(model => model.FieldName));

        return $$"""
            // <auto-generated />
            #nullable enable

            using MiKiNuo.Mvi.Core.Middleware;

            namespace {{first.NamespaceName}};

            /// <summary>
            /// Auto：由 MiKiNuo.Mvi.SourceGen 自动生成，请勿手动修改。
            /// </summary>
            internal static partial class {{first.FeatureName}}MiddlewarePipelineFactory
            {
                /// <summary>
                /// 创建 MVI 中间件管线。
                /// </summary>
                public static MviMiddlewarePipeline<{{first.StateTypeName}}, {{first.IntentTypeName}}, {{first.EffectTypeName}}> Create(
                    {{parameters}})
                {
                    return new MviMiddlewarePipeline<{{first.StateTypeName}}, {{first.IntentTypeName}}, {{first.EffectTypeName}}>(
                        dispatcher,
                        new IMviMiddleware<{{first.StateTypeName}}, {{first.IntentTypeName}}, {{first.EffectTypeName}}>[]
                        {
                            {{arrayItems}}
                        });
                }
            }
            """;
    }

    private sealed class MiddlewareModel
    {
        public MiddlewareModel(
            string namespaceName,
            string typeName,
            string fieldName,
            string stateTypeName,
            string intentTypeName,
            string effectTypeName,
            int order)
        {
            NamespaceName = namespaceName;
            TypeName = typeName;
            FieldName = fieldName;
            StateTypeName = stateTypeName;
            IntentTypeName = intentTypeName;
            EffectTypeName = effectTypeName;
            Order = order;
        }

        public string NamespaceName { get; }

        public string TypeName { get; }

        public string FieldName { get; }

        public string StateTypeName { get; }

        public string IntentTypeName { get; }

        public string EffectTypeName { get; }

        public int Order { get; }

        public string GroupKey => NamespaceName + "|" + StateTypeName + "|" + IntentTypeName + "|" + EffectTypeName;

        public string FeatureName => IntentTypeName.EndsWith("Intent", StringComparison.Ordinal)
            ? IntentTypeName.Substring(0, IntentTypeName.Length - "Intent".Length)
            : IntentTypeName;

        public static MiddlewareModel? From(GeneratorAttributeSyntaxContext context)
        {
            if (context.TargetSymbol is not INamedTypeSymbol typeSymbol)
            {
                return null;
            }

            var middlewareInterface = typeSymbol.AllInterfaces.FirstOrDefault(IsMiddlewareInterface);
            if (middlewareInterface is null || middlewareInterface.TypeArguments.Length != 3)
            {
                return null;
            }

            var attribute = context.Attributes.FirstOrDefault(attributeData =>
                attributeData.AttributeClass?.ToDisplayString() == MiddlewareAttributeMetadataName);
            if (attribute?.ConstructorArguments.Length != 1 ||
                attribute.ConstructorArguments[0].Value is not int order)
            {
                return null;
            }

            return new MiddlewareModel(
                GetNamespaceName(typeSymbol),
                typeSymbol.Name,
                ToCamelCase(typeSymbol.Name),
                GetTypeName(middlewareInterface.TypeArguments[0], typeSymbol),
                GetTypeName(middlewareInterface.TypeArguments[1], typeSymbol),
                GetTypeName(middlewareInterface.TypeArguments[2], typeSymbol),
                order);
        }
    }

    private static bool IsMiddlewareInterface(INamedTypeSymbol interfaceSymbol)
    {
        var definition = interfaceSymbol.OriginalDefinition;
        return definition.MetadataName == "IMviMiddleware`3" &&
            definition.ContainingNamespace.ToDisplayString() == "MiKiNuo.Mvi.Core.Middleware";
    }

    private static string GetNamespaceName(INamedTypeSymbol typeSymbol)
    {
        return typeSymbol.ContainingNamespace.IsGlobalNamespace
            ? string.Empty
            : typeSymbol.ContainingNamespace.ToDisplayString();
    }

    private static string GetTypeName(ITypeSymbol typeSymbol, INamedTypeSymbol containingType)
    {
        if (SymbolEqualityComparer.Default.Equals(typeSymbol.ContainingNamespace, containingType.ContainingNamespace))
        {
            return typeSymbol.Name;
        }

        return typeSymbol.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat).Replace("global::", string.Empty);
    }

    private static string ToCamelCase(string value)
    {
        if (string.IsNullOrEmpty(value) || char.IsLower(value[0]))
        {
            return value;
        }

        return char.ToLowerInvariant(value[0]) + value.Substring(1);
    }
}
