using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace MiKiNuo.Mvi.SourceGen.Mediator;

/// <summary>
/// 生成 MVI Mediator 请求响应路由。
/// </summary>
[Generator]
public sealed class MviMediatorRouteGenerator : IIncrementalGenerator
{
    private const string MediatorAttributeMetadataName = "MiKiNuo.Mvi.Abstractions.Generation.MviMediatorAttribute";
    private const string RouteAttributeMetadataName = "MiKiNuo.Mvi.Abstractions.Generation.MviRouteAttribute";

    /// <inheritdoc />
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var mediators = context.SyntaxProvider.ForAttributeWithMetadataName(
            MediatorAttributeMetadataName,
            static (node, _) => node is ClassDeclarationSyntax,
            static (generatorContext, _) => MediatorModel.From(generatorContext))
            .Where(static model => model is not null);

        context.RegisterSourceOutput(mediators, static (sourceProductionContext, model) =>
        {
            if (model is null || model.Routes.Count == 0)
            {
                return;
            }

            sourceProductionContext.AddSource(
                $"{model.TypeName}.Routes.g.cs",
                SourceText.From(Render(model), Encoding.UTF8));
        });
    }

    private static string Render(MediatorModel model)
    {
        var routeChecks = string.Join("\n", model.Routes.Select(route =>
            $$"""
                    if (typeof(TRequest) == typeof({{route.RequestTypeName}}) &&
                        typeof(TResponse) == typeof({{route.ResponseTypeName}}))
                    {
                        throw new NotImplementedException("Mediator route handler generation is not implemented for {{route.RequestTypeName}} -> {{route.ResponseTypeName}}.");
                    }
            """));

        return $$"""
            // <auto-generated />
            #nullable enable

            using System;
            using System.Threading;
            using System.Threading.Tasks;
            using MiKiNuo.Mvi.Core.Mediator;

            namespace {{model.NamespaceName}};

            /// <summary>
            /// Auto：由 MiKiNuo.Mvi.SourceGen 自动生成，请勿手动修改。
            /// </summary>
            public sealed partial class {{model.TypeName}}
            {
                /// <inheritdoc />
                public ValueTask<TResponse> SendAsync<TRequest, TResponse>(
                    ComponentAddress target,
                    TRequest request,
                    CancellationToken cancellationToken)
                {
            {{routeChecks}}
                    throw new InvalidOperationException($"No mediator route is registered for request '{typeof(TRequest).FullName}' and response '{typeof(TResponse).FullName}'.");
                }
            }
            """;
    }

    private sealed class MediatorModel
    {
        public MediatorModel(string namespaceName, string typeName, IReadOnlyList<RouteModel> routes)
        {
            NamespaceName = namespaceName;
            TypeName = typeName;
            Routes = routes;
        }

        public string NamespaceName { get; }

        public string TypeName { get; }

        public IReadOnlyList<RouteModel> Routes { get; }

        public static MediatorModel? From(GeneratorAttributeSyntaxContext context)
        {
            if (context.TargetSymbol is not INamedTypeSymbol typeSymbol)
            {
                return null;
            }

            var routes = typeSymbol.GetAttributes()
                .Where(attribute => attribute.AttributeClass?.ToDisplayString() == RouteAttributeMetadataName)
                .Select(attribute => RouteModel.From(attribute, typeSymbol))
                .Where(route => route is not null)
                .Cast<RouteModel>()
                .ToArray();

            return new MediatorModel(GetNamespaceName(typeSymbol), typeSymbol.Name, routes);
        }
    }

    private sealed class RouteModel
    {
        public RouteModel(string requestTypeName, string responseTypeName)
        {
            RequestTypeName = requestTypeName;
            ResponseTypeName = responseTypeName;
        }

        public string RequestTypeName { get; }

        public string ResponseTypeName { get; }

        public static RouteModel? From(AttributeData attributeData, INamedTypeSymbol containingType)
        {
            if (attributeData.ConstructorArguments.Length != 2 ||
                attributeData.ConstructorArguments[0].Value is not INamedTypeSymbol requestType ||
                attributeData.ConstructorArguments[1].Value is not INamedTypeSymbol responseType)
            {
                return null;
            }

            return new RouteModel(
                GetTypeName(requestType, containingType),
                GetTypeName(responseType, containingType));
        }
    }

    private static string GetNamespaceName(INamedTypeSymbol typeSymbol)
    {
        return typeSymbol.ContainingNamespace.IsGlobalNamespace
            ? string.Empty
            : typeSymbol.ContainingNamespace.ToDisplayString();
    }

    private static string GetTypeName(ITypeSymbol typeSymbol, INamedTypeSymbol containingType)
    {
        if (SymbolEqualityComparer.Default.Equals(typeSymbol.ContainingNamespace, containingType.ContainingNamespace))
        {
            return typeSymbol.Name;
        }

        return typeSymbol.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat).Replace("global::", string.Empty);
    }
}
