using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.Text;
using TUnit.Assertions;
using TUnit.Core;

namespace MiKiNuo.Mvi.SourceGen.Tests;

public sealed class SourceGeneratorVerifierTests
{
    [Test]
    public async Task VerifyAsync_runs_generator_and_compiles_generated_source()
    {
        const string source = """
            namespace Demo;

            public static partial class GeneratedConsumer
            {
                public static partial string GetMessage();
            }
            """;

        var result = await SourceGeneratorVerifier.VerifyAsync(
            source,
            new MessageGenerator());

        await Assert.That(result.GeneratedTrees.Select(tree => tree.FilePath)).Contains(filePath => filePath.EndsWith("GeneratedMessage.g.cs", StringComparison.Ordinal));
        await Assert.That(result.Diagnostics).IsEmpty();
    }

    [Test]
    public async Task VerifyAsync_compiles_generated_source_that_references_runtime_contracts()
    {
        const string source = """
            using MiKiNuo.Mvi.Abstractions;
            using MiKiNuo.Mvi.Core.Dispatching;
            using MiKiNuo.Mvi.Core.Reducers;

            namespace Demo;

            public sealed record DemoState : IMviState;
            public abstract partial record DemoIntent : IMviIntent
            {
                public abstract int Kind { get; }
            }
            public sealed partial record FirstIntent : DemoIntent
            {
                public override int Kind => 0;
            }
            public sealed record DemoEffect : IMviEffect;
            """;

        var result = await SourceGeneratorVerifier.VerifyAsync(
            source,
            new RuntimeContractReferenceGenerator());

        await Assert.That(result.Diagnostics).IsEmpty();
        await Assert.That(result.GeneratedSources).Contains(sourceText => sourceText.Contains("IIntentDispatcher<DemoState, DemoIntent, DemoEffect>", StringComparison.Ordinal));
    }

    private sealed class RuntimeContractReferenceGenerator : IIncrementalGenerator
    {
        public void Initialize(IncrementalGeneratorInitializationContext context)
        {
            context.RegisterPostInitializationOutput(static postInitializationContext =>
            {
                postInitializationContext.AddSource(
                    "RuntimeContractReference.g.cs",
                    SourceText.From(
                        """
                        // <auto-generated />
                        #nullable enable

                        using System.Threading;
                        using System.Threading.Tasks;
                        using MiKiNuo.Mvi.Core.Dispatching;
                        using MiKiNuo.Mvi.Core.Reducers;

                        namespace Demo;

                        internal sealed class GeneratedDispatcher : IIntentDispatcher<DemoState, DemoIntent, DemoEffect>
                        {
                            public ValueTask<ReduceResult<DemoState, DemoEffect>> DispatchAsync(
                                DemoState state,
                                DemoIntent intent,
                                CancellationToken cancellationToken)
                            {
                                return ValueTask.FromResult(ReduceResults.StateOnly<DemoState, DemoEffect>(state));
                            }
                        }
                        """,
                        Encoding.UTF8));
            });
        }
    }

    private sealed class MessageGenerator : IIncrementalGenerator
    {
        public void Initialize(IncrementalGeneratorInitializationContext context)
        {
            context.RegisterPostInitializationOutput(static postInitializationContext =>
            {
                postInitializationContext.AddSource(
                    "GeneratedMessage.g.cs",
                    SourceText.From(
                        """
                        // <auto-generated />
                        #nullable enable

                        namespace Demo;

                        public static partial class GeneratedConsumer
                        {
                            public static partial string GetMessage() => "generated";
                        }
                        """,
                        Encoding.UTF8));
            });
        }
    }
}
