using MiKiNuo.Mvi.Generators.Diagnostics;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;
namespace MiKiNuo.Mvi.Generators.SourceGeneration;
/// <summary>在现有 Avalonia Control 上生成 View 接口与生命周期控制器，不要求泛型控件基类。</summary>
[Generator]
public sealed class MviViewGenerator : IIncrementalGenerator
{
    private static readonly DiagnosticDescriptor Invalid = new(DiagnosticIdCatalog.MviViewDeclarationInvalid, "View 声明无效", "{0}", "MviView", DiagnosticSeverity.Error, true);
    /// <summary>登记 View 的类型化生成。</summary>
    /// <param name="context">编译上下文。</param>
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var views = context.SyntaxProvider.ForAttributeWithMetadataName("MiKiNuo.Mvi.Abstractions.MVI.Binding.MviViewAttribute",
            static (node, _) => node is ClassDeclarationSyntax,
            static (ctx, _) => (Type: (INamedTypeSymbol)ctx.TargetSymbol, Attribute: ctx.Attributes[0]));
        context.RegisterSourceOutput(views, static (output, candidate) =>
        {
            var type = candidate.Type;
            bool control = false;
            for (INamedTypeSymbol? current = type.BaseType; current is not null; current = current.BaseType)
                if (current.ToDisplayString() == "Avalonia.Controls.Control") control = true;
            if (!control || type.Arity != 0 || type.ContainingType is not null || !type.DeclaringSyntaxReferences.Any(r => r.GetSyntax() is ClassDeclarationSyntax c && c.Modifiers.Any(SyntaxKind.PartialKeyword))
                || candidate.Attribute.ConstructorArguments[0].Value is not INamedTypeSymbol vm)
            { output.ReportDiagnostic(Diagnostic.Create(Invalid, type.Locations.FirstOrDefault(), "MviView 需要顶层非泛型 partial Avalonia Control 和 ViewModel 类型。")); return; }
            string model = vm.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
            var b = new StringBuilder("// <auto-generated />\n#nullable enable\n");
            if (!type.ContainingNamespace.IsGlobalNamespace) b.Append("namespace ").Append(type.ContainingNamespace.ToDisplayString()).AppendLine(";");
            b.AppendLine("/// <summary>View 的非继承式绑定接入。</summary>");
            b.Append(type.DeclaredAccessibility == Accessibility.Public ? "public" : "internal").Append(" partial class @").Append(type.Name).Append(" : global::MiKiNuo.Mvi.Binding.Views.IMviView<").Append(model).AppendLine(">, global::MiKiNuo.Mvi.Platforms.Avalonia.Views.IMviAvaloniaViewBinding\n{");
            b.Append("    private global::MiKiNuo.Mvi.Platforms.Avalonia.Views.AvaloniaViewBinding<").Append(model).AppendLine(">? __mviViewBinding;");
            b.AppendLine("    /// <summary>绑定借用的模型与解析器。</summary>\n    /// <param name=\"viewModel\">模型。</param>\n    /// <param name=\"resolver\">解析器。</param>");
            b.Append("    public void Bind(").Append(model).AppendLine(" viewModel, global::MiKiNuo.Mvi.Runtime.DI.IMviResolver resolver)\n    {");
            b.AppendLine("        __mviViewBinding ??= new(this, (model, bindings, services) => { ConfigureBindings(model, bindings, services); ConfigureSlots(model, bindings, services); });\n        __mviViewBinding.Bind(viewModel, resolver);\n    }");
            b.AppendLine("    /// <summary>仅释放绑定，不释放业务模型。</summary>\n    public void Unbind() => __mviViewBinding?.Unbind();");
            b.Append("    partial void ConfigureBindings(").Append(model).AppendLine(" viewModel, global::MiKiNuo.Mvi.Binding.Disposables.MviDisposableBag bindings, global::MiKiNuo.Mvi.Runtime.DI.IMviResolver resolver);");
            b.Append("    partial void ConfigureSlots(").Append(model).AppendLine(" viewModel, global::MiKiNuo.Mvi.Binding.Disposables.MviDisposableBag bindings, global::MiKiNuo.Mvi.Runtime.DI.IMviResolver resolver);\n}");
            output.AddSource(type.ToDisplayString() + ".View.g.cs", SourceText.From(b.ToString(), Encoding.UTF8));
        });
    }
}
