using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace MiKiNuo.Mvi.SourceGen.Intent;

/// <summary>
/// 生成 MVI 意图编号成员。
/// </summary>
[Generator]
public sealed class MviIntentKindGenerator : IIncrementalGenerator
{
    private const string IntentKindAttributeMetadataName = "MiKiNuo.Mvi.Abstractions.Generation.MviIntentKindAttribute";
    private const string IntentUnionAttributeMetadataName = "MiKiNuo.Mvi.Abstractions.Generation.MviIntentUnionAttribute";

    /// <inheritdoc />
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var unionTypes = context.SyntaxProvider.ForAttributeWithMetadataName(
            IntentUnionAttributeMetadataName,
            static (node, _) => node is TypeDeclarationSyntax,
            static (generatorContext, _) => IntentUnionModel.From(generatorContext));

        context.RegisterSourceOutput(unionTypes, static (sourceProductionContext, model) =>
        {
            if (model is null)
            {
                return;
            }

            sourceProductionContext.AddSource(
                $"{model.TypeName}.IntentUnion.g.cs",
                SourceText.From(RenderUnion(model), Encoding.UTF8));
        });

        var intentTypes = context.SyntaxProvider.ForAttributeWithMetadataName(
            IntentKindAttributeMetadataName,
            static (node, _) => node is TypeDeclarationSyntax,
            static (generatorContext, _) => IntentKindModel.From(generatorContext));

        context.RegisterSourceOutput(intentTypes, static (sourceProductionContext, model) =>
        {
            if (model is null)
            {
                return;
            }

            sourceProductionContext.AddSource(
                $"{model.TypeName}.Kind.g.cs",
                SourceText.From(RenderKind(model), Encoding.UTF8));
        });
    }

    private static string RenderUnion(IntentUnionModel model)
    {
        var typeKeyword = model.IsRecord ? "record" : "class";
        return $$"""
            // <auto-generated />
            #nullable enable

            namespace {{model.NamespaceName}};

            /// <summary>
            /// Auto：由 MiKiNuo.Mvi.SourceGen 自动生成，请勿手动修改。
            /// </summary>
            partial {{typeKeyword}} {{model.TypeName}}
            {
                /// <inheritdoc />
                public abstract int Kind { get; }
            }
            """;
    }

    private static string RenderKind(IntentKindModel model)
    {
        var typeKeyword = model.IsRecord ? "record" : "class";
        return $$"""
            // <auto-generated />
            #nullable enable

            namespace {{model.NamespaceName}};

            /// <summary>
            /// Auto：由 MiKiNuo.Mvi.SourceGen 自动生成，请勿手动修改。
            /// </summary>
            partial {{typeKeyword}} {{model.TypeName}}
            {
                /// <inheritdoc />
                public override int Kind => {{model.Kind}};
            }
            """;
    }

    private sealed class IntentUnionModel
    {
        public IntentUnionModel(string namespaceName, string typeName, bool isRecord)
        {
            NamespaceName = namespaceName;
            TypeName = typeName;
            IsRecord = isRecord;
        }

        public string NamespaceName { get; }

        public string TypeName { get; }

        public bool IsRecord { get; }

        public static IntentUnionModel? From(GeneratorAttributeSyntaxContext context)
        {
            if (context.TargetSymbol is not INamedTypeSymbol typeSymbol)
            {
                return null;
            }

            return new IntentUnionModel(
                GetNamespaceName(typeSymbol),
                typeSymbol.Name,
                typeSymbol.IsRecord);
        }
    }

    private sealed class IntentKindModel
    {
        public IntentKindModel(string namespaceName, string typeName, int kind, bool isRecord)
        {
            NamespaceName = namespaceName;
            TypeName = typeName;
            Kind = kind;
            IsRecord = isRecord;
        }

        public string NamespaceName { get; }

        public string TypeName { get; }

        public int Kind { get; }

        public bool IsRecord { get; }

        public static IntentKindModel? From(GeneratorAttributeSyntaxContext context)
        {
            if (context.TargetSymbol is not INamedTypeSymbol typeSymbol)
            {
                return null;
            }

            var attribute = context.Attributes.FirstOrDefault(attributeData =>
                attributeData.AttributeClass?.ToDisplayString() == IntentKindAttributeMetadataName);
            if (attribute?.ConstructorArguments.Length != 1 ||
                attribute.ConstructorArguments[0].Value is not int kind)
            {
                return null;
            }

            return new IntentKindModel(
                GetNamespaceName(typeSymbol),
                typeSymbol.Name,
                kind,
                typeSymbol.IsRecord);
        }
    }

    private static string GetNamespaceName(INamedTypeSymbol typeSymbol)
    {
        return typeSymbol.ContainingNamespace.IsGlobalNamespace
            ? string.Empty
            : typeSymbol.ContainingNamespace.ToDisplayString();
    }
}
