using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace MiKiNuo.Mvi.SourceGen.Intent;

/// <summary>
/// 生成 MVI 意图分发器。
/// </summary>
[Generator]
public sealed class MviIntentDispatcherGenerator : IIncrementalGenerator
{
    private const string IntentUnionAttributeMetadataName = "MiKiNuo.Mvi.Abstractions.Generation.MviIntentUnionAttribute";
    private const string IntentHandlerAttributeMetadataName = "MiKiNuo.Mvi.Abstractions.Generation.MviIntentHandlerAttribute";

    /// <inheritdoc />
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var unions = context.SyntaxProvider.ForAttributeWithMetadataName(
            IntentUnionAttributeMetadataName,
            static (node, _) => node is TypeDeclarationSyntax,
            static (generatorContext, _) => IntentUnionModel.From(generatorContext))
            .Where(static model => model is not null)
            .Collect();

        var handlers = context.SyntaxProvider.ForAttributeWithMetadataName(
            IntentHandlerAttributeMetadataName,
            static (node, _) => node is TypeDeclarationSyntax,
            static (generatorContext, _) => IntentHandlerModel.From(generatorContext))
            .Where(static model => model is not null)
            .Collect();

        var input = unions.Combine(handlers);
        context.RegisterSourceOutput(input, static (sourceProductionContext, pair) =>
        {
            foreach (var union in pair.Left)
            {
                if (union is null)
                {
                    continue;
                }

                var matchingHandlers = pair.Right
                    .Where(handler => handler is not null && handler.IsForUnion(union))
                    .Cast<IntentHandlerModel>()
                    .OrderBy(handler => handler.Kind)
                    .ToArray();
                if (matchingHandlers.Length == 0)
                {
                    continue;
                }

                sourceProductionContext.AddSource(
                    $"{union.TypeName}Dispatcher.g.cs",
                    SourceText.From(Render(union, matchingHandlers), Encoding.UTF8));
            }
        });
    }

    private static string Render(IntentUnionModel union, IReadOnlyList<IntentHandlerModel> handlers)
    {
        var dispatcherName = $"{union.TypeName}Dispatcher";
        var constructorParameters = string.Join(",\n        ", handlers.Select(handler =>
            $"{handler.HandlerTypeName} {handler.FieldName}"));
        var fields = string.Join("\n", handlers.Select(handler =>
            $"    private readonly {handler.HandlerTypeName} {handler.FieldName};"));
        var assignments = string.Join("\n", handlers.Select(handler =>
            $"        this.{handler.FieldName} = {handler.FieldName};"));
        var cases = string.Join("\n", handlers.Select(handler =>
            $$"""
                    case {{handler.Kind}}:
                        return {{handler.FieldName}}.HandleAsync(state, ({{handler.IntentTypeName}})intent, cancellationToken);
            """));

        return $$"""
            // <auto-generated />
            #nullable enable

            using System;
            using System.Threading;
            using System.Threading.Tasks;
            using MiKiNuo.Mvi.Core.Dispatching;
            using MiKiNuo.Mvi.Core.Reducers;

            namespace {{union.NamespaceName}};

            /// <summary>
            /// Auto：由 MiKiNuo.Mvi.SourceGen 自动生成，请勿手动修改。
            /// </summary>
            internal sealed partial class {{dispatcherName}} : IIntentDispatcher<{{handlers[0].StateTypeName}}, {{union.TypeName}}, {{handlers[0].EffectTypeName}}>
            {
            {{fields}}

                /// <summary>
                /// 初始化意图分发器。
                /// </summary>
                public {{dispatcherName}}(
                    {{constructorParameters}})
                {
            {{assignments}}
                }

                /// <inheritdoc />
                public ValueTask<ReduceResult<{{handlers[0].StateTypeName}}, {{handlers[0].EffectTypeName}}>> DispatchAsync(
                    {{handlers[0].StateTypeName}} state,
                    {{union.TypeName}} intent,
                    CancellationToken cancellationToken)
                {
                    switch (intent.Kind)
                    {
            {{cases}}
                        default:
                            throw new InvalidOperationException($"No intent handler is registered for kind '{intent.Kind}'.");
                    }
                }
            }
            """;
    }

    private sealed class IntentUnionModel
    {
        public IntentUnionModel(string namespaceName, string typeName, string fullTypeName)
        {
            NamespaceName = namespaceName;
            TypeName = typeName;
            FullTypeName = fullTypeName;
        }

        public string NamespaceName { get; }

        public string TypeName { get; }

        public string FullTypeName { get; }

        public static IntentUnionModel? From(GeneratorAttributeSyntaxContext context)
        {
            if (context.TargetSymbol is not INamedTypeSymbol typeSymbol)
            {
                return null;
            }

            return new IntentUnionModel(
                GetNamespaceName(typeSymbol),
                typeSymbol.Name,
                typeSymbol.ToDisplayString());
        }
    }

    private sealed class IntentHandlerModel
    {
        public IntentHandlerModel(
            string handlerTypeName,
            string fieldName,
            string stateTypeName,
            string intentTypeName,
            string intentUnionTypeName,
            string effectTypeName,
            int kind)
        {
            HandlerTypeName = handlerTypeName;
            FieldName = fieldName;
            StateTypeName = stateTypeName;
            IntentTypeName = intentTypeName;
            IntentUnionTypeName = intentUnionTypeName;
            EffectTypeName = effectTypeName;
            Kind = kind;
        }

        public string HandlerTypeName { get; }

        public string FieldName { get; }

        public string StateTypeName { get; }

        public string IntentTypeName { get; }

        public string IntentUnionTypeName { get; }

        public string EffectTypeName { get; }

        public int Kind { get; }

        public bool IsForUnion(IntentUnionModel union)
        {
            return IntentUnionTypeName == union.FullTypeName;
        }

        public static IntentHandlerModel? From(GeneratorAttributeSyntaxContext context)
        {
            if (context.TargetSymbol is not INamedTypeSymbol handlerType)
            {
                return null;
            }

            var handlerInterface = handlerType.AllInterfaces.FirstOrDefault(IsIntentHandlerInterface);
            if (handlerInterface is null || handlerInterface.TypeArguments.Length != 3)
            {
                return null;
            }

            var stateType = handlerInterface.TypeArguments[0];
            var intentType = handlerInterface.TypeArguments[1] as INamedTypeSymbol;
            var effectType = handlerInterface.TypeArguments[2];
            if (intentType is null)
            {
                return null;
            }

            var kindAttribute = intentType.GetAttributes().FirstOrDefault(attributeData =>
                attributeData.AttributeClass?.ToDisplayString() == "MiKiNuo.Mvi.Abstractions.Generation.MviIntentKindAttribute");
            if (kindAttribute?.ConstructorArguments.Length != 1 ||
                kindAttribute.ConstructorArguments[0].Value is not int kind)
            {
                return null;
            }

            var unionType = intentType.BaseType;
            if (unionType is null)
            {
                return null;
            }

            return new IntentHandlerModel(
                handlerType.Name,
                ToCamelCase(handlerType.Name),
                stateType.ToDisplayString(),
                intentType.ToDisplayString(),
                unionType.ToDisplayString(),
                effectType.ToDisplayString(),
                kind);
        }
    }

    private static string GetNamespaceName(INamedTypeSymbol typeSymbol)
    {
        return typeSymbol.ContainingNamespace.IsGlobalNamespace
            ? string.Empty
            : typeSymbol.ContainingNamespace.ToDisplayString();
    }

    private static bool IsIntentHandlerInterface(INamedTypeSymbol interfaceSymbol)
    {
        var definition = interfaceSymbol.OriginalDefinition;
        return definition.MetadataName == "IIntentHandler`3" &&
            definition.ContainingNamespace.ToDisplayString() == "MiKiNuo.Mvi.Core.Dispatching";
    }

    private static string ToCamelCase(string value)
    {
        if (string.IsNullOrEmpty(value) || char.IsLower(value[0]))
        {
            return value;
        }

        return char.ToLowerInvariant(value[0]) + value.Substring(1);
    }
}
