// <auto-generated />
// 全局命名空间：MVI 表现层项目共用的隐式 using。
// 由 GlobalUsings.cs 集中管理，避免每个文件重复引入同一组命名空间。

global using global::System;
global using global::System.Collections.Generic;
global using global::System.Threading;
global using global::System.Threading.Tasks;
