// <auto-generated />
// 全局命名空间：示例项目共用的隐式 using。

global using global::System;
global using global::System.Collections.Generic;
global using global::System.Threading;
global using global::System.Threading.Tasks;
