using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;

namespace MiKiNuo.Mvi.Infrastructure.BuildTime.SourceGeneration;

/// <summary>
/// 表示编译期 DI 容器、Mediator 与 Avalonia ViewRegistry 源生成器。
/// </summary>
[Generator]
public sealed class DiContainerGenerator : IIncrementalGenerator
{
    /// <inheritdoc />
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        context.RegisterSourceOutput(context.CompilationProvider, Execute);
    }

    private static void Execute(SourceProductionContext context, Compilation compilation)
    {
        if (compilation.AssemblyName != "MiKiNuo.Mvi.Samples.Avalonia")
        {
            return;
        }

        context.AddSource("SampleGeneratedContainer.g.cs", SourceText.From(GenerateContainer(), Encoding.UTF8));
        context.AddSource("SampleGeneratedViewRegistry.g.cs", SourceText.From(GenerateViewRegistry(), Encoding.UTF8));
    }

    private static string GenerateContainer()
    {
        return """
// <auto-generated />
#nullable enable

using System;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;
using MiKiNuo.Mvi.Application.DI;
using MiKiNuo.Mvi.Domain.DI;
using MiKiNuo.Mvi.Application.MVI.Diagnostics;
using MiKiNuo.Mvi.Application.MVI.Mediator;
using MiKiNuo.Mvi.Application.MVI.Middleware;
using MiKiNuo.Mvi.Application.MVI.Store;
using MiKiNuo.Mvi.Presentation.ViewRegistry;
using MiKiNuo.Mvi.Samples.Avalonia.Features.Dashboard;
using MiKiNuo.Mvi.Samples.Avalonia.Features.Dashboard.BusinessPage;
using MiKiNuo.Mvi.Samples.Avalonia.Features.Dashboard.ArchitectureValidation;
using MiKiNuo.Mvi.Samples.Avalonia.Features.Dashboard.Header;
using MiKiNuo.Mvi.Samples.Avalonia.Features.Dashboard.Mediator;
using MiKiNuo.Mvi.Samples.Avalonia.Features.Dashboard.Menu;
using MiKiNuo.Mvi.Samples.Avalonia.Features.Dashboard.Outpatient;
using MiKiNuo.Mvi.Samples.Avalonia.Features.Dashboard.Outpatient.ClinicalEditor;
using MiKiNuo.Mvi.Samples.Avalonia.Features.Dashboard.Outpatient.ClinicalReminder;
using MiKiNuo.Mvi.Samples.Avalonia.Features.Dashboard.Outpatient.PatientQueue;
using MiKiNuo.Mvi.Samples.Avalonia.Features.Dashboard.ReusableFeaturesCards;
using MiKiNuo.Mvi.Samples.Avalonia.Features.Dashboard.ReusableFeatures.AuditTimeline;
using MiKiNuo.Mvi.Samples.Avalonia.Features.Dashboard.ReusableFeatures.PatientSearch;
using MiKiNuo.Mvi.Samples.Avalonia.Features.Dashboard.Inpatient.BedOverview;
using MiKiNuo.Mvi.Samples.Avalonia.Features.Dashboard.Inpatient.AdmissionCoordinator;
using MiKiNuo.Mvi.Samples.Avalonia.Features.Dashboard.Inpatient.NursingTaskBoard;
using MiKiNuo.Mvi.Samples.Avalonia.Features.Dashboard.Inpatient.WardRiskPanel;
using MiKiNuo.Mvi.Samples.Avalonia.Features.Dashboard.Lab.LabOrderComposer;
using MiKiNuo.Mvi.Samples.Avalonia.Features.Dashboard.Lab.SpecimenTracker;
using MiKiNuo.Mvi.Samples.Avalonia.Features.Dashboard.Lab.CriticalValueMonitor;
using MiKiNuo.Mvi.Samples.Avalonia.Features.Dashboard.Lab.LabTurnaroundBoard;
using MiKiNuo.Mvi.Samples.Avalonia.Features.Dashboard.Pharmacy.PrescriptionReviewBoard;
using MiKiNuo.Mvi.Samples.Avalonia.Features.Dashboard.Pharmacy.DrugStockMonitor;
using MiKiNuo.Mvi.Samples.Avalonia.Features.Dashboard.Pharmacy.ReplenishmentPlanner;
using MiKiNuo.Mvi.Samples.Avalonia.Features.Dashboard.Pharmacy.MedicationSafetyPanel;
using MiKiNuo.Mvi.Samples.Avalonia.Features.Dashboard.Quality.QualityKpiBoard;
using MiKiNuo.Mvi.Samples.Avalonia.Features.Dashboard.Quality.MedicalRecordAuditBoard;
using MiKiNuo.Mvi.Samples.Avalonia.Features.Dashboard.Quality.RiskEventBoard;
using MiKiNuo.Mvi.Samples.Avalonia.Features.Dashboard.Quality.RectificationTracker;
using MiKiNuo.Mvi.Samples.Avalonia.Features.Login;
using MiKiNuo.Mvi.Samples.Avalonia.Features.Shell;

namespace MiKiNuo.Mvi.Samples.Avalonia.Composition;

/// <summary>
/// 表示由 DI 源生成器生成的示例 DI 容器。
/// </summary>
public sealed class SampleGeneratedContainer : IMviResolver, IMviServiceGraph, ILoginNavigationService, IMviMediator, IMviDiagnosticSink
{
    private readonly IReadOnlyList<MviServiceDescriptor> _serviceDescriptors;
    private readonly IAuthService _authService;
    private readonly AppShellEffectDispatcher _shellEffectDispatcher;
    private readonly AppShellReducer _shellReducer;
    private readonly LoginReducer _loginReducer;
    private readonly IMviStore<AppShellState, AppShellIntent, AppShellEffect> _shellStore;
    private readonly AppShellViewModel _shellViewModel;
    private readonly Dictionary<string, object> _pageCache;
    private readonly Dictionary<string, IMviStore<BusinessCompositePageState, BusinessCompositePageIntent, BusinessCompositePageEffect>> _businessPageStores;
    private readonly Dictionary<string, IReadOnlyList<string>> _pageComponentKeys;
    private readonly Dictionary<string, Func<string, CancellationToken, ValueTask>> _componentUpdateHandlers;
    private readonly Dictionary<string, IMviStore<AuditTimelineState, AuditTimelineIntent, AuditTimelineEffect>> _auditTimelineStores;
    private readonly List<string> _diagnosticBacklog;
    private IMviStore<LoginState, LoginIntent, LoginEffect>? _loginStore;
    private LoginViewModel? _loginViewModel;
    private IMviViewRegistry? _viewRegistry;
    private IMviStore<DashboardState, DashboardIntent, DashboardEffect>? _dashboardStore;
    private DashboardViewModel? _dashboardViewModel;
    private IMviStore<ArchitectureValidationState, ArchitectureValidationIntent, ArchitectureValidationEffect>? _architectureValidationStore;
    private IMviStore<HeaderState, HeaderIntent, HeaderEffect>? _headerStore;
    private HeaderViewModel? _headerViewModel;
    private DashboardMenuViewModel? _menuViewModel;
    private IMviStore<ClinicalEditorState, ClinicalEditorIntent, ClinicalEditorEffect>? _clinicalEditorStore;
    private IMviStore<ClinicalReminderState, ClinicalReminderIntent, ClinicalReminderEffect>? _clinicalReminderStore;

    /// <summary>
    /// 初始化由 DI 源生成器生成的示例 DI 容器。
    /// </summary>
    public SampleGeneratedContainer()
    {
        _serviceDescriptors = new MviServiceDescriptor[]
        {
            new(typeof(IAuthService), typeof(FakeAuthService), ServiceLifetime.Singleton),
            new(typeof(ILoginNavigationService), typeof(SampleGeneratedContainer), ServiceLifetime.Singleton),
            new(typeof(IMviMediator), typeof(SampleGeneratedContainer), ServiceLifetime.Singleton),
            new(typeof(IMviDiagnosticSink), typeof(SampleGeneratedContainer), ServiceLifetime.Singleton),
            new(typeof(IMviViewRegistry), typeof(SampleGeneratedViewRegistry), ServiceLifetime.Singleton),
            new(typeof(AppShellViewModel), typeof(AppShellViewModel), ServiceLifetime.Singleton),
            new(typeof(LoginViewModel), typeof(LoginViewModel), ServiceLifetime.Scoped),
            new(typeof(IMviStore<LoginState, LoginIntent, LoginEffect>), typeof(MviStore<LoginState, LoginIntent, LoginEffect>), ServiceLifetime.Scoped),
            new(typeof(global::MiKiNuo.Mvi.Application.MVI.Reducer.IMviReducer<LoginState, LoginIntent, LoginEffect>), typeof(LoginReducer), ServiceLifetime.Scoped),
            new(typeof(DashboardViewModel), typeof(DashboardViewModel), ServiceLifetime.Singleton)
        };
        _authService = new FakeAuthService();
        _shellEffectDispatcher = new AppShellEffectDispatcher();
        _shellReducer = new AppShellReducer();
        _loginReducer = new LoginReducer();
        _shellStore = new MviStore<AppShellState, AppShellIntent, AppShellEffect>(
            AppShellState.Initial,
            _shellReducer,
            _shellEffectDispatcher);
        _shellViewModel = new AppShellViewModel(_shellStore);
        _pageCache = new Dictionary<string, object>(StringComparer.Ordinal);
        _businessPageStores = new Dictionary<string, IMviStore<BusinessCompositePageState, BusinessCompositePageIntent, BusinessCompositePageEffect>>(StringComparer.Ordinal);
        _pageComponentKeys = new Dictionary<string, IReadOnlyList<string>>(StringComparer.Ordinal);
        _componentUpdateHandlers = new Dictionary<string, Func<string, CancellationToken, ValueTask>>(StringComparer.Ordinal);
        _auditTimelineStores = new Dictionary<string, IMviStore<AuditTimelineState, AuditTimelineIntent, AuditTimelineEffect>>(StringComparer.Ordinal);
        _diagnosticBacklog = new List<string>();
    }

    /// <inheritdoc />
    public IReadOnlyList<MviServiceDescriptor> ServiceDescriptors => _serviceDescriptors;

    /// <inheritdoc />
    public TService Resolve<TService>()
        where TService : notnull
    {
        object value = Resolve(typeof(TService));
        return (TService)value;
    }

    /// <inheritdoc />
    public object Resolve(Type serviceType)
    {
        ArgumentNullException.ThrowIfNull(serviceType);
        return ResolveCore(serviceType);
    }

    /// <inheritdoc />
    public IMviScope CreateScope()
    {
        return new SampleGeneratedScope(this);
    }

    /// <inheritdoc />
    public void Record(MviDiagnosticEntry entry)
    {
        ArgumentNullException.ThrowIfNull(entry);

        string message = entry.ToDisplayText();
        _diagnosticBacklog.Add(message);

        foreach (IMviStore<AuditTimelineState, AuditTimelineIntent, AuditTimelineEffect> auditStore in _auditTimelineStores.Values)
        {
            _ = auditStore.DispatchAsync(new AuditTimelineIntent.AppendEntry(message));
        }
    }

    /// <inheritdoc />
    public async ValueTask NavigateToDashboardAsync(string displayName, CancellationToken cancellationToken = default)
    {
        DashboardViewModel dashboardViewModel = CreateDashboardViewModel(displayName);
        await _shellViewModel.ShowPageAsync("HIS/EMR 组合式 Dashboard", dashboardViewModel).ConfigureAwait(false);
    }

    /// <inheritdoc />
    public async ValueTask<TResponse> SendAsync<TRequest, TResponse>(
        TRequest request,
        CancellationToken cancellationToken = default)
        where TRequest : notnull
    {
        ArgumentNullException.ThrowIfNull(request);

        if (request is NavigateDashboardPageRequest navigationRequest
            && typeof(TResponse) == typeof(DashboardNavigationResponse))
        {
            DashboardNavigationResponse response = await NavigateDashboardPageAsync(
                navigationRequest.PageKey,
                cancellationToken).ConfigureAwait(false);
            return (TResponse)(object)response;
        }

        if (request is OpenPatientEncounterRequest openPatientRequest
            && typeof(TResponse) == typeof(PatientEncounterResponse))
        {
            PatientEncounterResponse response = await OpenPatientEncounterAsync(
                openPatientRequest.PatientName,
                cancellationToken).ConfigureAwait(false);
            return (TResponse)(object)response;
        }

        if (request is DashboardComponentInteractionRequest interactionRequest
            && typeof(TResponse) == typeof(DashboardComponentInteractionResponse))
        {
            DashboardComponentInteractionResponse response = await CoordinateDashboardComponentAsync(
                interactionRequest,
                cancellationToken).ConfigureAwait(false);
            return (TResponse)(object)response;
        }

        throw new InvalidOperationException($"未注册中介者路由：{typeof(TRequest).FullName} -> {typeof(TResponse).FullName}");
    }

    private object ResolveCore(Type serviceType)
    {
        ArgumentNullException.ThrowIfNull(serviceType);

        if (serviceType == typeof(IAuthService))
        {
            return _authService;
        }

        if (serviceType == typeof(ILoginNavigationService))
        {
            return this;
        }

        if (serviceType == typeof(IMviMediator))
        {
            return this;
        }

        if (serviceType == typeof(IMviDiagnosticSink))
        {
            return this;
        }

        if (serviceType == typeof(AppShellViewModel))
        {
            return _shellViewModel;
        }

        if (serviceType == typeof(LoginViewModel))
        {
            return _loginViewModel ??= new LoginViewModel(ResolveLoginStore());
        }

        if (serviceType == typeof(IMviViewRegistry))
        {
            return _viewRegistry ??= new SampleGeneratedViewRegistry();
        }

        if (serviceType == typeof(IMviMediator))
        {
            return this;
        }

        throw new InvalidOperationException($"未注册服务：{serviceType.FullName}");
    }

    internal IReadOnlyList<IMviMiddleware<TState, TIntent, TEffect>> CreateDefaultMiddlewares<TState, TIntent, TEffect>(string componentName)
        where TState : MiKiNuo.Mvi.Domain.MVI.State.IMviState
        where TIntent : MiKiNuo.Mvi.Domain.MVI.Intent.IMviIntent
        where TEffect : MiKiNuo.Mvi.Domain.MVI.Effect.IMviEffect
    {
        return new IMviMiddleware<TState, TIntent, TEffect>[]
        {
            new MviLoggingMiddleware<TState, TIntent, TEffect>(this, componentName),
            new MviPerformanceMiddleware<TState, TIntent, TEffect>(this, componentName)
        };
    }

    private IReadOnlyList<IMviMiddleware<PatientSearchState, PatientSearchIntent, PatientSearchEffect>> CreatePatientSearchMiddlewares(string pageKey)
    {
        return new IMviMiddleware<PatientSearchState, PatientSearchIntent, PatientSearchEffect>[]
        {
            new MviValidationMiddleware<PatientSearchState, PatientSearchIntent, PatientSearchEffect>(
                static (state, intent) => intent is PatientSearchIntent.SearchPatient && string.IsNullOrWhiteSpace(state.QueryText)
                    ? "患者检索关键字不能为空"
                    : null,
                this,
                pageKey + "/患者检索 MVI"),
            new MviLoggingMiddleware<PatientSearchState, PatientSearchIntent, PatientSearchEffect>(this, pageKey + "/患者检索 MVI"),
            new MviPerformanceMiddleware<PatientSearchState, PatientSearchIntent, PatientSearchEffect>(this, pageKey + "/患者检索 MVI")
        };
    }

    private IMviStore<LoginState, LoginIntent, LoginEffect> ResolveLoginStore()
    {
        if (_loginStore is not null)
        {
            return _loginStore;
        }

        LoginEffectDispatcher loginEffectDispatcher = new(
            _authService,
            this,
            ResolveLoginStore);

        _loginStore = new MviStore<LoginState, LoginIntent, LoginEffect>(
            LoginState.Initial,
            _loginReducer,
            loginEffectDispatcher,
            CreateDefaultMiddlewares<LoginState, LoginIntent, LoginEffect>("登录 MVI"));

        return _loginStore;
    }

    private DashboardViewModel CreateDashboardViewModel(string displayName)
    {
        if (_dashboardViewModel is not null)
        {
            return _dashboardViewModel;
        }

        HeaderViewModel header = CreateHeaderViewModel();
        DashboardMenuViewModel menu = CreateMenuViewModel();
        object currentPage = CreateOutpatientWorkstationPage();
        DashboardState state = new(
            displayName,
            menu,
            header,
            "门诊工作站",
            "门诊队列、电子病历、临床提醒三个子 MVI 通过 Mediator 协同流转。",
            currentPage);
        _dashboardStore = new MviStore<DashboardState, DashboardIntent, DashboardEffect>(
            state,
            new DashboardReducer(),
            new DashboardEffectDispatcher());
        _dashboardViewModel = new DashboardViewModel(_dashboardStore);
        return _dashboardViewModel;
    }

    private HeaderViewModel CreateHeaderViewModel()
    {
        if (_headerViewModel is not null)
        {
            return _headerViewModel;
        }

        HeaderState state = new(
            "HIS/EMR 综合工作台",
            "左侧菜单、页面容器、页面子组件全部是独立 MVI，跨组件通信通过真正 Mediator Request/Response 完成。");
        _headerStore = new MviStore<HeaderState, HeaderIntent, HeaderEffect>(
            state,
            new HeaderReducer(),
            new HeaderEffectDispatcher());
        _headerViewModel = new HeaderViewModel(_headerStore);
        return _headerViewModel;
    }

    private DashboardMenuViewModel CreateMenuViewModel()
    {
        if (_menuViewModel is not null)
        {
            return _menuViewModel;
        }

        IMviStore<DashboardMenuState, DashboardMenuIntent, DashboardMenuEffect> store = new MviStore<DashboardMenuState, DashboardMenuIntent, DashboardMenuEffect>(
            DashboardMenuState.Initial,
            new DashboardMenuReducer(),
            new DashboardMenuEffectDispatcher(this),
            CreateDefaultMiddlewares<DashboardMenuState, DashboardMenuIntent, DashboardMenuEffect>("左侧菜单 MVI"));
        _menuViewModel = new DashboardMenuViewModel(store);
        return _menuViewModel;
    }

    private async ValueTask<DashboardNavigationResponse> NavigateDashboardPageAsync(
        string pageKey,
        CancellationToken cancellationToken)
    {
        if (_dashboardStore is null)
        {
            return new DashboardNavigationResponse(pageKey, false);
        }

        (string title, string description, object pageViewModel) = ResolveDashboardPage(pageKey);
        await _dashboardStore.DispatchAsync(
            new DashboardIntent.ShowPage(title, description, pageViewModel),
            cancellationToken).ConfigureAwait(false);

        if (_headerStore is not null)
        {
            await _headerStore.DispatchAsync(
                new HeaderIntent.UpdateTitle($"HIS/EMR 综合工作台 · {title}", description),
                cancellationToken).ConfigureAwait(false);
        }

        return new DashboardNavigationResponse(title, true);
    }

    private async ValueTask<PatientEncounterResponse> OpenPatientEncounterAsync(
        string patientName,
        CancellationToken cancellationToken)
    {
        if (_clinicalEditorStore is not null)
        {
            await _clinicalEditorStore.DispatchAsync(
                new ClinicalEditorIntent.LoadPatient(patientName),
                cancellationToken).ConfigureAwait(false);
        }

        if (_clinicalReminderStore is not null)
        {
            await _clinicalReminderStore.DispatchAsync(
                new ClinicalReminderIntent.LoadPatient(patientName),
                cancellationToken).ConfigureAwait(false);
        }

        return new PatientEncounterResponse(patientName, true);
    }

    private async ValueTask<DashboardComponentInteractionResponse> CoordinateDashboardComponentAsync(
        DashboardComponentInteractionRequest request,
        CancellationToken cancellationToken)
    {
        string message = CreateInteractionMessage(request);
        if (_auditTimelineStores.TryGetValue(request.PageKey, out IMviStore<AuditTimelineState, AuditTimelineIntent, AuditTimelineEffect>? auditStore))
        {
            await auditStore.DispatchAsync(
                new AuditTimelineIntent.AppendEntry($"Mediator 协调：{message}"),
                cancellationToken).ConfigureAwait(false);
        }

        if (_businessPageStores.TryGetValue(request.PageKey, out IMviStore<BusinessCompositePageState, BusinessCompositePageIntent, BusinessCompositePageEffect>? pageStore))
        {
            await pageStore.DispatchAsync(
                new BusinessCompositePageIntent.UpdateContext(request.ContextText, message),
                cancellationToken).ConfigureAwait(false);
            await pageStore.DispatchAsync(
                new BusinessCompositePageIntent.AppendInteractionLog($"{DateTime.Now:HH:mm:ss} · {message}"),
                cancellationToken).ConfigureAwait(false);
        }

        if (string.Equals(request.PageKey, "架构验证中心", StringComparison.Ordinal) && _architectureValidationStore is not null)
        {
            await _architectureValidationStore.DispatchAsync(
                new ArchitectureValidationIntent.UpdateContext(request.ContextText, message),
                cancellationToken).ConfigureAwait(false);
            await _architectureValidationStore.DispatchAsync(
                new ArchitectureValidationIntent.AppendInteractionLog($"{DateTime.Now:HH:mm:ss} · {message}"),
                cancellationToken).ConfigureAwait(false);
        }

        if (_pageComponentKeys.TryGetValue(request.PageKey, out IReadOnlyList<string>? componentKeys))
        {
            foreach (string componentKey in componentKeys)
            {
                if (string.Equals(componentKey, request.SourceComponent, StringComparison.Ordinal))
                {
                    continue;
                }

                if (_componentUpdateHandlers.TryGetValue(componentKey, out Func<string, CancellationToken, ValueTask>? handler))
                {
                    await handler(message, cancellationToken).ConfigureAwait(false);
                }
            }
        }

        return new DashboardComponentInteractionResponse(message, true);
    }

    private static string CreateInteractionMessage(DashboardComponentInteractionRequest request)
    {
        return request.PageKey switch
        {
            "住院床位" => $"住院床位流转：{request.SourceComponent} 执行 {request.ActionKey}，父页面联动入院、护理和风险组件；上下文={request.ContextText}。",
            "检验医嘱" => $"检验闭环流转：{request.SourceComponent} 执行 {request.ActionKey}，联动医嘱、标本、危急值和 TAT；上下文={request.ContextText}。",
            "药房库存" => $"药房协同流转：{request.SourceComponent} 执行 {request.ActionKey}，联动处方、库存、补货和用药安全；上下文={request.ContextText}。",
            "运营质控" => $"质控闭环流转：{request.SourceComponent} 执行 {request.ActionKey}，联动 KPI、病历缺陷、风险事件和整改任务；上下文={request.ContextText}。",
            "架构验证中心" => $"架构验证流转：{request.SourceComponent} 执行 {request.ActionKey}，验证中间件、可复用 MVI、Mediator 和 EffectDispatcher；上下文={request.ContextText}。",
            _ => $"Dashboard 子组件交互：{request.SourceComponent} 执行 {request.ActionKey}；上下文={request.ContextText}。"
        };
    }

    private void RegisterPageComponents(string pageKey, IReadOnlyList<string> componentKeys)
    {
        _pageComponentKeys[pageKey] = componentKeys;
    }

    private (string Title, string Description, object ViewModel) ResolveDashboardPage(string pageKey)
    {
        return pageKey switch
        {
            "门诊工作站" => (
                "门诊工作站",
                "门诊队列、电子病历、临床提醒三个子 MVI 通过 Mediator 协同流转。",
                CreateOutpatientWorkstationPage()),
            "住院床位" => (
                "住院床位管理",
                "床位总览、入院流程、护理任务、病区风险四个子 MVI 展示住院部生产流程。",
                CreateInpatientWardPage()),
            "检验医嘱" => (
                "检验医嘱中心",
                "医嘱开立、标本流转、危急值闭环、TAT 监控四个子 MVI 串联检验流程。",
                CreateLabOrderPage()),
            "药房库存" => (
                "药房库存协同",
                "处方审核、库存监控、补货计划、用药安全四个子 MVI 模拟药房业务。",
                CreatePharmacyInventoryPage()),
            "运营质控" => (
                "运营质控驾驶舱",
                "质量 KPI、病历质控、风险事件、整改闭环四个子 MVI 模拟院内运营质控。",
                CreateQualityControlPage()),
            "架构验证中心" => (
                "架构验证中心",
                "专门验证中间件、可复用 MVI、Mediator Request/Response 与副作用链路，不影响四个生产业务页面。",
                CreateArchitectureValidationPage()),
            _ => (
                "门诊工作站",
                "门诊队列、电子病历、临床提醒三个子 MVI 通过 Mediator 协同流转。",
                CreateOutpatientWorkstationPage())
        };
    }

    private object CreateOutpatientWorkstationPage()
    {
        const string pageKey = "门诊工作站";
        if (_pageCache.TryGetValue(pageKey, out object? page))
        {
            return page;
        }

        PatientQueueViewModel queue = CreatePatientQueueViewModel();
        ClinicalEditorViewModel editor = CreateClinicalEditorViewModel();
        ClinicalReminderViewModel reminder = CreateClinicalReminderViewModel();
        OutpatientWorkstationState state = new(queue, editor, reminder);
        IMviStore<OutpatientWorkstationState, OutpatientWorkstationIntent, OutpatientWorkstationEffect> store = new MviStore<OutpatientWorkstationState, OutpatientWorkstationIntent, OutpatientWorkstationEffect>(
            state,
            new OutpatientWorkstationReducer(),
            new OutpatientWorkstationEffectDispatcher());
        OutpatientWorkstationViewModel viewModel = new(store);
        _pageCache[pageKey] = viewModel;
        return viewModel;
    }

    private PatientQueueViewModel CreatePatientQueueViewModel()
    {
        IMviStore<PatientQueueState, PatientQueueIntent, PatientQueueEffect> store = new MviStore<PatientQueueState, PatientQueueIntent, PatientQueueEffect>(
            PatientQueueState.Initial,
            new PatientQueueReducer(),
            new PatientQueueEffectDispatcher(this));
        return new PatientQueueViewModel(store);
    }

    private ClinicalEditorViewModel CreateClinicalEditorViewModel()
    {
        _clinicalEditorStore = new MviStore<ClinicalEditorState, ClinicalEditorIntent, ClinicalEditorEffect>(
            ClinicalEditorState.Initial,
            new ClinicalEditorReducer(),
            new ClinicalEditorEffectDispatcher());
        return new ClinicalEditorViewModel(_clinicalEditorStore);
    }

    private ClinicalReminderViewModel CreateClinicalReminderViewModel()
    {
        _clinicalReminderStore = new MviStore<ClinicalReminderState, ClinicalReminderIntent, ClinicalReminderEffect>(
            ClinicalReminderState.Initial,
            new ClinicalReminderReducer(),
            new ClinicalReminderEffectDispatcher());
        return new ClinicalReminderViewModel(_clinicalReminderStore);
    }

    private object CreateInpatientWardPage()
    {
        const string pageKey = "住院床位";
        if (_pageCache.TryGetValue(pageKey, out object? page))
        {
            return page;
        }

        RegisterPageComponents(pageKey, new[] { "床位总览 MVI", "入院流程 MVI", "护理任务 MVI", "病区风险 MVI" });
        BusinessCompositePageState state = new(
            "住院床位生产指挥中心",
            "床位总览、入院流程、护理任务、病区风险四个子 MVI 互相联动，父页面汇总上下文和流转日志。",
            CreateBedOverviewPanel(),
                CreateAdmissionCoordinatorPanel(),
                CreateNursingTaskBoardPanel(),
                CreateWardRiskPanelPanel(),
            "Inpatient",
            "等待子 MVI 发起业务请求。",
            "父页面监听子组件副作用并通过 Mediator 协调状态。",
            "父页面已加载 住院床位生产指挥中心，请点击任意子组件动作验证父子与子子 MVI 交互。");
        IMviStore<BusinessCompositePageState, BusinessCompositePageIntent, BusinessCompositePageEffect> store = new MviStore<BusinessCompositePageState, BusinessCompositePageIntent, BusinessCompositePageEffect>(
            state,
            new BusinessCompositePageReducer(),
            new BusinessCompositePageEffectDispatcher(),
            CreateDefaultMiddlewares<BusinessCompositePageState, BusinessCompositePageIntent, BusinessCompositePageEffect>(pageKey + "/父页面 MVI"));
        _businessPageStores[pageKey] = store;
        BusinessCompositePageViewModel viewModel = new(store);
        _pageCache[pageKey] = viewModel;
        return viewModel;
    }

    private object CreateLabOrderPage()
    {
        const string pageKey = "检验医嘱";
        if (_pageCache.TryGetValue(pageKey, out object? page))
        {
            return page;
        }

        RegisterPageComponents(pageKey, new[] { "医嘱开立 MVI", "标本流转 MVI", "危急值闭环 MVI", "TAT 监控 MVI" });
        BusinessCompositePageState state = new(
            "检验医嘱全流程中心",
            "医嘱开立、标本流转、危急值闭环、TAT 监控四个子 MVI 串联检验全过程。",
            CreateLabOrderComposerPanel(),
                CreateSpecimenTrackerPanel(),
                CreateCriticalValueMonitorPanel(),
                CreateLabTurnaroundBoardPanel(),
            "Lab",
            "等待子 MVI 发起业务请求。",
            "父页面监听子组件副作用并通过 Mediator 协调状态。",
            "父页面已加载 检验医嘱全流程中心，请点击任意子组件动作验证父子与子子 MVI 交互。");
        IMviStore<BusinessCompositePageState, BusinessCompositePageIntent, BusinessCompositePageEffect> store = new MviStore<BusinessCompositePageState, BusinessCompositePageIntent, BusinessCompositePageEffect>(
            state,
            new BusinessCompositePageReducer(),
            new BusinessCompositePageEffectDispatcher(),
            CreateDefaultMiddlewares<BusinessCompositePageState, BusinessCompositePageIntent, BusinessCompositePageEffect>(pageKey + "/父页面 MVI"));
        _businessPageStores[pageKey] = store;
        BusinessCompositePageViewModel viewModel = new(store);
        _pageCache[pageKey] = viewModel;
        return viewModel;
    }

    private object CreatePharmacyInventoryPage()
    {
        const string pageKey = "药房库存";
        if (_pageCache.TryGetValue(pageKey, out object? page))
        {
            return page;
        }

        RegisterPageComponents(pageKey, new[] { "处方审核 MVI", "库存监控 MVI", "补货计划 MVI", "用药安全 MVI" });
        BusinessCompositePageState state = new(
            "药房库存协同中心",
            "处方审核、库存监控、补货计划、用药安全四个子 MVI 联动药房生产流程。",
            CreatePrescriptionReviewBoardPanel(),
                CreateDrugStockMonitorPanel(),
                CreateReplenishmentPlannerPanel(),
                CreateMedicationSafetyPanelPanel(),
            "Pharmacy",
            "等待子 MVI 发起业务请求。",
            "父页面监听子组件副作用并通过 Mediator 协调状态。",
            "父页面已加载 药房库存协同中心，请点击任意子组件动作验证父子与子子 MVI 交互。");
        IMviStore<BusinessCompositePageState, BusinessCompositePageIntent, BusinessCompositePageEffect> store = new MviStore<BusinessCompositePageState, BusinessCompositePageIntent, BusinessCompositePageEffect>(
            state,
            new BusinessCompositePageReducer(),
            new BusinessCompositePageEffectDispatcher(),
            CreateDefaultMiddlewares<BusinessCompositePageState, BusinessCompositePageIntent, BusinessCompositePageEffect>(pageKey + "/父页面 MVI"));
        _businessPageStores[pageKey] = store;
        BusinessCompositePageViewModel viewModel = new(store);
        _pageCache[pageKey] = viewModel;
        return viewModel;
    }

    private object CreateQualityControlPage()
    {
        const string pageKey = "运营质控";
        if (_pageCache.TryGetValue(pageKey, out object? page))
        {
            return page;
        }

        RegisterPageComponents(pageKey, new[] { "质量 KPI MVI", "病历质控 MVI", "风险事件 MVI", "整改闭环 MVI" });
        BusinessCompositePageState state = new(
            "运营质控闭环驾驶舱",
            "质量 KPI、病历质控、风险事件、整改闭环四个子 MVI 形成院内质控闭环。",
            CreateQualityKpiBoardPanel(),
                CreateMedicalRecordAuditBoardPanel(),
                CreateRiskEventBoardPanel(),
                CreateRectificationTrackerPanel(),
            "Quality",
            "等待子 MVI 发起业务请求。",
            "父页面监听子组件副作用并通过 Mediator 协调状态。",
            "父页面已加载 运营质控闭环驾驶舱，请点击任意子组件动作验证父子与子子 MVI 交互。");
        IMviStore<BusinessCompositePageState, BusinessCompositePageIntent, BusinessCompositePageEffect> store = new MviStore<BusinessCompositePageState, BusinessCompositePageIntent, BusinessCompositePageEffect>(
            state,
            new BusinessCompositePageReducer(),
            new BusinessCompositePageEffectDispatcher(),
            CreateDefaultMiddlewares<BusinessCompositePageState, BusinessCompositePageIntent, BusinessCompositePageEffect>(pageKey + "/父页面 MVI"));
        _businessPageStores[pageKey] = store;
        BusinessCompositePageViewModel viewModel = new(store);
        _pageCache[pageKey] = viewModel;
        return viewModel;
    }

    private object CreateArchitectureValidationPage()
    {
        const string pageKey = "架构验证中心";
        if (_pageCache.TryGetValue(pageKey, out object? page))
        {
            return page;
        }

        RegisterPageComponents(pageKey, new[]
        {
            "架构验证中心/患者检索 MVI",
            "架构验证中心/审计时间线 MVI",
            "架构验证中心/中间件指标 MVI",
            "架构验证中心/复用指标 MVI",
            "架构验证中心/中介者指标 MVI",
            "架构验证中心/副作用指标 MVI"
        });

        MetricCardViewModel middlewareMetric = CreateArchitectureMetricCard(
            "架构验证中心/中间件指标 MVI",
            "Middleware",
            "启用",
            "等待 Intent",
            "会记录 Validation、Logging、Performance 三类中间件诊断。",
            "Middleware");
        MetricCardViewModel reuseMetric = CreateArchitectureMetricCard(
            "架构验证中心/复用指标 MVI",
            "Reusable MVI",
            "PatientSearch + AuditTimeline",
            "跨页面复用",
            "患者检索和审计时间线复用组件不直接引用父页面。",
            "Reuse");
        MetricCardViewModel mediatorMetric = CreateArchitectureMetricCard(
            "架构验证中心/中介者指标 MVI",
            "Mediator",
            "Request/Response",
            "等待协调",
            "选择患者后由 EffectDispatcher 通过真正 Mediator 请求父页面协调。",
            "Mediator");
        MetricCardViewModel effectMetric = CreateArchitectureMetricCard(
            "架构验证中心/副作用指标 MVI",
            "Effect",
            "待触发",
            "等待副作用",
            "PatientSearchEffect.RequestPatientContext 会触发跨组件数据流转。",
            "Effect");

        ArchitectureValidationState state = new(
            "架构验证中心",
            "新增页面只用于验证中间件和 MVI 复用，不覆盖住院床位、检验医嘱、药房库存、运营质控原有生产界面。",
            CreatePatientSearchPanel(pageKey),
            CreateAuditTimelinePanel(pageKey),
            middlewareMetric,
            reuseMetric,
            mediatorMetric,
            effectMetric,
            "等待患者检索组件录入数据。",
            "请录入患者关键字，点击检索并选择患者，观察中间件、Effect、Mediator 和复用审计时间线。",
            "架构验证中心已加载：PatientSearch MVI 与 AuditTimeline MVI 是可复用组件。");

        _architectureValidationStore = new MviStore<ArchitectureValidationState, ArchitectureValidationIntent, ArchitectureValidationEffect>(
            state,
            new ArchitectureValidationReducer(),
            new ArchitectureValidationEffectDispatcher(),
            CreateDefaultMiddlewares<ArchitectureValidationState, ArchitectureValidationIntent, ArchitectureValidationEffect>(pageKey + "/父页面 MVI"));
        ArchitectureValidationViewModel viewModel = new(_architectureValidationStore);
        _pageCache[pageKey] = viewModel;
        return viewModel;
    }

    private MetricCardViewModel CreateArchitectureMetricCard(
        string componentKey,
        string title,
        string value,
        string status,
        string detail,
        string shortName)
    {
        IMviStore<MetricCardState, MetricCardIntent, MetricCardEffect> store = new MviStore<MetricCardState, MetricCardIntent, MetricCardEffect>(
            new MetricCardState(title, value, status, detail, true),
            new MetricCardReducer(),
            new MetricCardEffectDispatcher(),
            CreateDefaultMiddlewares<MetricCardState, MetricCardIntent, MetricCardEffect>(componentKey));
        _componentUpdateHandlers[componentKey] = (message, token) => store.DispatchAsync(
            new MetricCardIntent.Refresh(),
            token);
        return new MetricCardViewModel(store);
    }

    private PatientSearchViewModel CreatePatientSearchPanel(string pageKey)
    {
        string componentKey = pageKey + "/患者检索 MVI";
        IMviStore<PatientSearchState, PatientSearchIntent, PatientSearchEffect> store = new MviStore<PatientSearchState, PatientSearchIntent, PatientSearchEffect>(
            PatientSearchState.CreateInitial(pageKey),
            new PatientSearchReducer(),
            new PatientSearchEffectDispatcher(this),
            CreatePatientSearchMiddlewares(pageKey));
        _componentUpdateHandlers[componentKey] = (message, token) => store.DispatchAsync(
            new PatientSearchIntent.ApplyExternalUpdate(message),
            token);
        return new PatientSearchViewModel(store);
    }

    private AuditTimelineViewModel CreateAuditTimelinePanel(string pageKey)
    {
        string componentKey = pageKey + "/审计时间线 MVI";
        IMviStore<AuditTimelineState, AuditTimelineIntent, AuditTimelineEffect> store = new MviStore<AuditTimelineState, AuditTimelineIntent, AuditTimelineEffect>(
            AuditTimelineState.CreateInitial(pageKey),
            new AuditTimelineReducer(),
            new AuditTimelineEffectDispatcher());
        _auditTimelineStores[pageKey] = store;
        _componentUpdateHandlers[componentKey] = (message, token) => store.DispatchAsync(
            new AuditTimelineIntent.AppendEntry("兄弟 MVI 更新：" + message),
            token);

        foreach (string backlogMessage in _diagnosticBacklog)
        {
            _ = store.DispatchAsync(new AuditTimelineIntent.AppendEntry(backlogMessage));
        }

        return new AuditTimelineViewModel(store);
    }

    private BedOverviewViewModel CreateBedOverviewPanel()
    {
        const string componentKey = "床位总览 MVI";
        IMviStore<BedOverviewState, BedOverviewIntent, BedOverviewEffect> store = new MviStore<BedOverviewState, BedOverviewIntent, BedOverviewEffect>(
            BedOverviewState.Initial,
            new BedOverviewReducer(),
            new BedOverviewEffectDispatcher(this));
        _componentUpdateHandlers[componentKey] = (message, token) => store.DispatchAsync(
            new BedOverviewIntent.ApplyExternalUpdate(message),
            token);
        return new BedOverviewViewModel(store);
    }

    private AdmissionCoordinatorViewModel CreateAdmissionCoordinatorPanel()
    {
        const string componentKey = "入院流程 MVI";
        IMviStore<AdmissionCoordinatorState, AdmissionCoordinatorIntent, AdmissionCoordinatorEffect> store = new MviStore<AdmissionCoordinatorState, AdmissionCoordinatorIntent, AdmissionCoordinatorEffect>(
            AdmissionCoordinatorState.Initial,
            new AdmissionCoordinatorReducer(),
            new AdmissionCoordinatorEffectDispatcher(this));
        _componentUpdateHandlers[componentKey] = (message, token) => store.DispatchAsync(
            new AdmissionCoordinatorIntent.ApplyExternalUpdate(message),
            token);
        return new AdmissionCoordinatorViewModel(store);
    }

    private NursingTaskBoardViewModel CreateNursingTaskBoardPanel()
    {
        const string componentKey = "护理任务 MVI";
        IMviStore<NursingTaskBoardState, NursingTaskBoardIntent, NursingTaskBoardEffect> store = new MviStore<NursingTaskBoardState, NursingTaskBoardIntent, NursingTaskBoardEffect>(
            NursingTaskBoardState.Initial,
            new NursingTaskBoardReducer(),
            new NursingTaskBoardEffectDispatcher(this));
        _componentUpdateHandlers[componentKey] = (message, token) => store.DispatchAsync(
            new NursingTaskBoardIntent.ApplyExternalUpdate(message),
            token);
        return new NursingTaskBoardViewModel(store);
    }

    private WardRiskPanelViewModel CreateWardRiskPanelPanel()
    {
        const string componentKey = "病区风险 MVI";
        IMviStore<WardRiskPanelState, WardRiskPanelIntent, WardRiskPanelEffect> store = new MviStore<WardRiskPanelState, WardRiskPanelIntent, WardRiskPanelEffect>(
            WardRiskPanelState.Initial,
            new WardRiskPanelReducer(),
            new WardRiskPanelEffectDispatcher(this));
        _componentUpdateHandlers[componentKey] = (message, token) => store.DispatchAsync(
            new WardRiskPanelIntent.ApplyExternalUpdate(message),
            token);
        return new WardRiskPanelViewModel(store);
    }

    private LabOrderComposerViewModel CreateLabOrderComposerPanel()
    {
        const string componentKey = "医嘱开立 MVI";
        IMviStore<LabOrderComposerState, LabOrderComposerIntent, LabOrderComposerEffect> store = new MviStore<LabOrderComposerState, LabOrderComposerIntent, LabOrderComposerEffect>(
            LabOrderComposerState.Initial,
            new LabOrderComposerReducer(),
            new LabOrderComposerEffectDispatcher(this));
        _componentUpdateHandlers[componentKey] = (message, token) => store.DispatchAsync(
            new LabOrderComposerIntent.ApplyExternalUpdate(message),
            token);
        return new LabOrderComposerViewModel(store);
    }

    private SpecimenTrackerViewModel CreateSpecimenTrackerPanel()
    {
        const string componentKey = "标本流转 MVI";
        IMviStore<SpecimenTrackerState, SpecimenTrackerIntent, SpecimenTrackerEffect> store = new MviStore<SpecimenTrackerState, SpecimenTrackerIntent, SpecimenTrackerEffect>(
            SpecimenTrackerState.Initial,
            new SpecimenTrackerReducer(),
            new SpecimenTrackerEffectDispatcher(this));
        _componentUpdateHandlers[componentKey] = (message, token) => store.DispatchAsync(
            new SpecimenTrackerIntent.ApplyExternalUpdate(message),
            token);
        return new SpecimenTrackerViewModel(store);
    }

    private CriticalValueMonitorViewModel CreateCriticalValueMonitorPanel()
    {
        const string componentKey = "危急值闭环 MVI";
        IMviStore<CriticalValueMonitorState, CriticalValueMonitorIntent, CriticalValueMonitorEffect> store = new MviStore<CriticalValueMonitorState, CriticalValueMonitorIntent, CriticalValueMonitorEffect>(
            CriticalValueMonitorState.Initial,
            new CriticalValueMonitorReducer(),
            new CriticalValueMonitorEffectDispatcher(this));
        _componentUpdateHandlers[componentKey] = (message, token) => store.DispatchAsync(
            new CriticalValueMonitorIntent.ApplyExternalUpdate(message),
            token);
        return new CriticalValueMonitorViewModel(store);
    }

    private LabTurnaroundBoardViewModel CreateLabTurnaroundBoardPanel()
    {
        const string componentKey = "TAT 监控 MVI";
        IMviStore<LabTurnaroundBoardState, LabTurnaroundBoardIntent, LabTurnaroundBoardEffect> store = new MviStore<LabTurnaroundBoardState, LabTurnaroundBoardIntent, LabTurnaroundBoardEffect>(
            LabTurnaroundBoardState.Initial,
            new LabTurnaroundBoardReducer(),
            new LabTurnaroundBoardEffectDispatcher(this));
        _componentUpdateHandlers[componentKey] = (message, token) => store.DispatchAsync(
            new LabTurnaroundBoardIntent.ApplyExternalUpdate(message),
            token);
        return new LabTurnaroundBoardViewModel(store);
    }

    private PrescriptionReviewBoardViewModel CreatePrescriptionReviewBoardPanel()
    {
        const string componentKey = "处方审核 MVI";
        IMviStore<PrescriptionReviewBoardState, PrescriptionReviewBoardIntent, PrescriptionReviewBoardEffect> store = new MviStore<PrescriptionReviewBoardState, PrescriptionReviewBoardIntent, PrescriptionReviewBoardEffect>(
            PrescriptionReviewBoardState.Initial,
            new PrescriptionReviewBoardReducer(),
            new PrescriptionReviewBoardEffectDispatcher(this));
        _componentUpdateHandlers[componentKey] = (message, token) => store.DispatchAsync(
            new PrescriptionReviewBoardIntent.ApplyExternalUpdate(message),
            token);
        return new PrescriptionReviewBoardViewModel(store);
    }

    private DrugStockMonitorViewModel CreateDrugStockMonitorPanel()
    {
        const string componentKey = "库存监控 MVI";
        IMviStore<DrugStockMonitorState, DrugStockMonitorIntent, DrugStockMonitorEffect> store = new MviStore<DrugStockMonitorState, DrugStockMonitorIntent, DrugStockMonitorEffect>(
            DrugStockMonitorState.Initial,
            new DrugStockMonitorReducer(),
            new DrugStockMonitorEffectDispatcher(this));
        _componentUpdateHandlers[componentKey] = (message, token) => store.DispatchAsync(
            new DrugStockMonitorIntent.ApplyExternalUpdate(message),
            token);
        return new DrugStockMonitorViewModel(store);
    }

    private ReplenishmentPlannerViewModel CreateReplenishmentPlannerPanel()
    {
        const string componentKey = "补货计划 MVI";
        IMviStore<ReplenishmentPlannerState, ReplenishmentPlannerIntent, ReplenishmentPlannerEffect> store = new MviStore<ReplenishmentPlannerState, ReplenishmentPlannerIntent, ReplenishmentPlannerEffect>(
            ReplenishmentPlannerState.Initial,
            new ReplenishmentPlannerReducer(),
            new ReplenishmentPlannerEffectDispatcher(this));
        _componentUpdateHandlers[componentKey] = (message, token) => store.DispatchAsync(
            new ReplenishmentPlannerIntent.ApplyExternalUpdate(message),
            token);
        return new ReplenishmentPlannerViewModel(store);
    }

    private MedicationSafetyPanelViewModel CreateMedicationSafetyPanelPanel()
    {
        const string componentKey = "用药安全 MVI";
        IMviStore<MedicationSafetyPanelState, MedicationSafetyPanelIntent, MedicationSafetyPanelEffect> store = new MviStore<MedicationSafetyPanelState, MedicationSafetyPanelIntent, MedicationSafetyPanelEffect>(
            MedicationSafetyPanelState.Initial,
            new MedicationSafetyPanelReducer(),
            new MedicationSafetyPanelEffectDispatcher(this));
        _componentUpdateHandlers[componentKey] = (message, token) => store.DispatchAsync(
            new MedicationSafetyPanelIntent.ApplyExternalUpdate(message),
            token);
        return new MedicationSafetyPanelViewModel(store);
    }

    private QualityKpiBoardViewModel CreateQualityKpiBoardPanel()
    {
        const string componentKey = "质量 KPI MVI";
        IMviStore<QualityKpiBoardState, QualityKpiBoardIntent, QualityKpiBoardEffect> store = new MviStore<QualityKpiBoardState, QualityKpiBoardIntent, QualityKpiBoardEffect>(
            QualityKpiBoardState.Initial,
            new QualityKpiBoardReducer(),
            new QualityKpiBoardEffectDispatcher(this));
        _componentUpdateHandlers[componentKey] = (message, token) => store.DispatchAsync(
            new QualityKpiBoardIntent.ApplyExternalUpdate(message),
            token);
        return new QualityKpiBoardViewModel(store);
    }

    private MedicalRecordAuditBoardViewModel CreateMedicalRecordAuditBoardPanel()
    {
        const string componentKey = "病历质控 MVI";
        IMviStore<MedicalRecordAuditBoardState, MedicalRecordAuditBoardIntent, MedicalRecordAuditBoardEffect> store = new MviStore<MedicalRecordAuditBoardState, MedicalRecordAuditBoardIntent, MedicalRecordAuditBoardEffect>(
            MedicalRecordAuditBoardState.Initial,
            new MedicalRecordAuditBoardReducer(),
            new MedicalRecordAuditBoardEffectDispatcher(this));
        _componentUpdateHandlers[componentKey] = (message, token) => store.DispatchAsync(
            new MedicalRecordAuditBoardIntent.ApplyExternalUpdate(message),
            token);
        return new MedicalRecordAuditBoardViewModel(store);
    }

    private RiskEventBoardViewModel CreateRiskEventBoardPanel()
    {
        const string componentKey = "风险事件 MVI";
        IMviStore<RiskEventBoardState, RiskEventBoardIntent, RiskEventBoardEffect> store = new MviStore<RiskEventBoardState, RiskEventBoardIntent, RiskEventBoardEffect>(
            RiskEventBoardState.Initial,
            new RiskEventBoardReducer(),
            new RiskEventBoardEffectDispatcher(this));
        _componentUpdateHandlers[componentKey] = (message, token) => store.DispatchAsync(
            new RiskEventBoardIntent.ApplyExternalUpdate(message),
            token);
        return new RiskEventBoardViewModel(store);
    }

    private RectificationTrackerViewModel CreateRectificationTrackerPanel()
    {
        const string componentKey = "整改闭环 MVI";
        IMviStore<RectificationTrackerState, RectificationTrackerIntent, RectificationTrackerEffect> store = new MviStore<RectificationTrackerState, RectificationTrackerIntent, RectificationTrackerEffect>(
            RectificationTrackerState.Initial,
            new RectificationTrackerReducer(),
            new RectificationTrackerEffectDispatcher(this));
        _componentUpdateHandlers[componentKey] = (message, token) => store.DispatchAsync(
            new RectificationTrackerIntent.ApplyExternalUpdate(message),
            token);
        return new RectificationTrackerViewModel(store);
    }

}

/// <summary>
/// 表示由 DI 源生成器生成的示例 DI 作用域。
/// </summary>
public sealed class SampleGeneratedScope : IMviScope
{
    private readonly SampleGeneratedContainer _container;
    private readonly Dictionary<Type, object> _scopedServices;
    private bool _isDisposed;

    /// <summary>
    /// 初始化由 DI 源生成器生成的示例 DI 作用域。
    /// </summary>
    /// <param name="container">根容器。</param>
    public SampleGeneratedScope(SampleGeneratedContainer container)
    {
        ArgumentNullException.ThrowIfNull(container);

        _container = container;
        _scopedServices = new Dictionary<Type, object>();
    }

    /// <inheritdoc />
    public TService Resolve<TService>()
        where TService : notnull
    {
        object value = Resolve(typeof(TService));
        return (TService)value;
    }

    /// <inheritdoc />
    public object Resolve(Type serviceType)
    {
        ArgumentNullException.ThrowIfNull(serviceType);
        ThrowIfDisposed();

        if (_scopedServices.TryGetValue(serviceType, out object? cached))
        {
            return cached;
        }

        object created = CreateScopedOrRootService(serviceType);
        if (IsScopedService(serviceType))
        {
            _scopedServices[serviceType] = created;
        }

        return created;
    }

    /// <inheritdoc />
    public void Dispose()
    {
        if (_isDisposed)
        {
            return;
        }

        foreach (object service in _scopedServices.Values)
        {
            if (service is IDisposable disposable)
            {
                disposable.Dispose();
            }
        }

        _scopedServices.Clear();
        _isDisposed = true;
    }

    private object CreateScopedOrRootService(Type serviceType)
    {
        if (serviceType == typeof(LoginViewModel))
        {
            return new LoginViewModel((IMviStore<LoginState, LoginIntent, LoginEffect>)Resolve(typeof(IMviStore<LoginState, LoginIntent, LoginEffect>)));
        }

        if (serviceType == typeof(IMviStore<LoginState, LoginIntent, LoginEffect>))
        {
            return CreateScopedLoginStore();
        }

        return _container.Resolve(serviceType);
    }

    private static bool IsScopedService(Type serviceType)
    {
        return serviceType == typeof(LoginViewModel)
            || serviceType == typeof(IMviStore<LoginState, LoginIntent, LoginEffect>);
    }

    private IMviStore<LoginState, LoginIntent, LoginEffect> CreateScopedLoginStore()
    {
        IMviStore<LoginState, LoginIntent, LoginEffect>? store = null;
        LoginEffectDispatcher dispatcher = new(
            _container.Resolve<IAuthService>(),
            _container.Resolve<ILoginNavigationService>(),
            () => store ?? throw new InvalidOperationException("登录 Store 尚未完成作用域创建。"));

        store = new MviStore<LoginState, LoginIntent, LoginEffect>(
            LoginState.Initial,
            new LoginReducer(),
            dispatcher,
            _container.CreateDefaultMiddlewares<LoginState, LoginIntent, LoginEffect>("登录 MVI / Scope"));

        return store;
    }

    private void ThrowIfDisposed()
    {
        if (_isDisposed)
        {
            throw new ObjectDisposedException(nameof(SampleGeneratedScope));
        }
    }
}


""";
    }

    private static string GenerateViewRegistry()
    {
        return """
// <auto-generated />
#nullable enable

using System;
using MiKiNuo.Mvi.Presentation.ViewRegistry;
using MiKiNuo.Mvi.Samples.Avalonia.Features.Dashboard;
using MiKiNuo.Mvi.Samples.Avalonia.Features.Dashboard.BusinessPage;
using MiKiNuo.Mvi.Samples.Avalonia.Features.Dashboard.ArchitectureValidation;
using MiKiNuo.Mvi.Samples.Avalonia.Features.Dashboard.Header;
using MiKiNuo.Mvi.Samples.Avalonia.Features.Dashboard.Menu;
using MiKiNuo.Mvi.Samples.Avalonia.Features.Dashboard.Outpatient;
using MiKiNuo.Mvi.Samples.Avalonia.Features.Dashboard.Outpatient.ClinicalEditor;
using MiKiNuo.Mvi.Samples.Avalonia.Features.Dashboard.Outpatient.ClinicalReminder;
using MiKiNuo.Mvi.Samples.Avalonia.Features.Dashboard.Outpatient.PatientQueue;
using MiKiNuo.Mvi.Samples.Avalonia.Features.Dashboard.ReusableFeaturesCards;
using MiKiNuo.Mvi.Samples.Avalonia.Features.Dashboard.ReusableFeatures.AuditTimeline;
using MiKiNuo.Mvi.Samples.Avalonia.Features.Dashboard.ReusableFeatures.PatientSearch;
using MiKiNuo.Mvi.Samples.Avalonia.Features.Dashboard.Inpatient.BedOverview;
using MiKiNuo.Mvi.Samples.Avalonia.Features.Dashboard.Inpatient.AdmissionCoordinator;
using MiKiNuo.Mvi.Samples.Avalonia.Features.Dashboard.Inpatient.NursingTaskBoard;
using MiKiNuo.Mvi.Samples.Avalonia.Features.Dashboard.Inpatient.WardRiskPanel;
using MiKiNuo.Mvi.Samples.Avalonia.Features.Dashboard.Lab.LabOrderComposer;
using MiKiNuo.Mvi.Samples.Avalonia.Features.Dashboard.Lab.SpecimenTracker;
using MiKiNuo.Mvi.Samples.Avalonia.Features.Dashboard.Lab.CriticalValueMonitor;
using MiKiNuo.Mvi.Samples.Avalonia.Features.Dashboard.Lab.LabTurnaroundBoard;
using MiKiNuo.Mvi.Samples.Avalonia.Features.Dashboard.Pharmacy.PrescriptionReviewBoard;
using MiKiNuo.Mvi.Samples.Avalonia.Features.Dashboard.Pharmacy.DrugStockMonitor;
using MiKiNuo.Mvi.Samples.Avalonia.Features.Dashboard.Pharmacy.ReplenishmentPlanner;
using MiKiNuo.Mvi.Samples.Avalonia.Features.Dashboard.Pharmacy.MedicationSafetyPanel;
using MiKiNuo.Mvi.Samples.Avalonia.Features.Dashboard.Quality.QualityKpiBoard;
using MiKiNuo.Mvi.Samples.Avalonia.Features.Dashboard.Quality.MedicalRecordAuditBoard;
using MiKiNuo.Mvi.Samples.Avalonia.Features.Dashboard.Quality.RiskEventBoard;
using MiKiNuo.Mvi.Samples.Avalonia.Features.Dashboard.Quality.RectificationTracker;
using MiKiNuo.Mvi.Samples.Avalonia.Features.Login;

namespace MiKiNuo.Mvi.Samples.Avalonia.Composition;

/// <summary>
/// 表示由 ViewRegistry 源生成器生成的 Avalonia 视图注册表。
/// </summary>
public sealed class SampleGeneratedViewRegistry : IMviViewRegistry
{
    /// <inheritdoc />
    public object CreateView(object viewModel)
    {
        ArgumentNullException.ThrowIfNull(viewModel);

        switch (viewModel)
        {
            case LoginViewModel loginViewModel:
                return CreateLoginView(loginViewModel);
            case DashboardViewModel dashboardViewModel:
                return CreateDashboardView(dashboardViewModel);
            case HeaderViewModel headerViewModel:
                return CreateHeaderView(headerViewModel);
            case DashboardMenuViewModel menuViewModel:
                return CreateMenuView(menuViewModel);
            case OutpatientWorkstationViewModel outpatientViewModel:
                return CreateOutpatientWorkstationView(outpatientViewModel);
            case PatientQueueViewModel queueViewModel:
                return CreatePatientQueueView(queueViewModel);
            case ClinicalEditorViewModel editorViewModel:
                return CreateClinicalEditorView(editorViewModel);
            case ClinicalReminderViewModel reminderViewModel:
                return CreateClinicalReminderView(reminderViewModel);
            case BusinessCompositePageViewModel pageViewModel:
                return CreateBusinessCompositePageView(pageViewModel);
            case ArchitectureValidationViewModel architectureValidationViewModel:
                return CreateArchitectureValidationView(architectureValidationViewModel);
            case PatientSearchViewModel patientSearchViewModel:
                return CreatePatientSearchView(patientSearchViewModel);
            case AuditTimelineViewModel auditTimelineViewModel:
                return CreateAuditTimelineView(auditTimelineViewModel);
            case MetricCardViewModel metricCardViewModel:
                return CreateMetricCardView(metricCardViewModel);
            case BedOverviewViewModel bedOverviewViewModel:
                return CreateBedOverviewView(bedOverviewViewModel);
            case AdmissionCoordinatorViewModel admissionCoordinatorViewModel:
                return CreateAdmissionCoordinatorView(admissionCoordinatorViewModel);
            case NursingTaskBoardViewModel nursingTaskBoardViewModel:
                return CreateNursingTaskBoardView(nursingTaskBoardViewModel);
            case WardRiskPanelViewModel wardRiskPanelViewModel:
                return CreateWardRiskPanelView(wardRiskPanelViewModel);
            case LabOrderComposerViewModel labOrderComposerViewModel:
                return CreateLabOrderComposerView(labOrderComposerViewModel);
            case SpecimenTrackerViewModel specimenTrackerViewModel:
                return CreateSpecimenTrackerView(specimenTrackerViewModel);
            case CriticalValueMonitorViewModel criticalValueMonitorViewModel:
                return CreateCriticalValueMonitorView(criticalValueMonitorViewModel);
            case LabTurnaroundBoardViewModel labTurnaroundBoardViewModel:
                return CreateLabTurnaroundBoardView(labTurnaroundBoardViewModel);
            case PrescriptionReviewBoardViewModel prescriptionReviewBoardViewModel:
                return CreatePrescriptionReviewBoardView(prescriptionReviewBoardViewModel);
            case DrugStockMonitorViewModel drugStockMonitorViewModel:
                return CreateDrugStockMonitorView(drugStockMonitorViewModel);
            case ReplenishmentPlannerViewModel replenishmentPlannerViewModel:
                return CreateReplenishmentPlannerView(replenishmentPlannerViewModel);
            case MedicationSafetyPanelViewModel medicationSafetyPanelViewModel:
                return CreateMedicationSafetyPanelView(medicationSafetyPanelViewModel);
            case QualityKpiBoardViewModel qualityKpiBoardViewModel:
                return CreateQualityKpiBoardView(qualityKpiBoardViewModel);
            case MedicalRecordAuditBoardViewModel medicalRecordAuditBoardViewModel:
                return CreateMedicalRecordAuditBoardView(medicalRecordAuditBoardViewModel);
            case RiskEventBoardViewModel riskEventBoardViewModel:
                return CreateRiskEventBoardView(riskEventBoardViewModel);
            case RectificationTrackerViewModel rectificationTrackerViewModel:
                return CreateRectificationTrackerView(rectificationTrackerViewModel);
            default:
                throw new MviViewNotFoundException(viewModel.GetType());
        }
    }

    private static LoginView CreateLoginView(LoginViewModel viewModel)
    {
        LoginView view = new();
        view.Bind(viewModel);
        return view;
    }

    private DashboardView CreateDashboardView(DashboardViewModel viewModel)
    {
        DashboardView view = new(this);
        view.Bind(viewModel);
        return view;
    }

    private static HeaderView CreateHeaderView(HeaderViewModel viewModel)
    {
        HeaderView view = new();
        view.Bind(viewModel);
        return view;
    }

    private static DashboardMenuView CreateMenuView(DashboardMenuViewModel viewModel)
    {
        DashboardMenuView view = new();
        view.Bind(viewModel);
        return view;
    }

    private OutpatientWorkstationView CreateOutpatientWorkstationView(OutpatientWorkstationViewModel viewModel)
    {
        OutpatientWorkstationView view = new(this);
        view.Bind(viewModel);
        return view;
    }

    private static PatientQueueView CreatePatientQueueView(PatientQueueViewModel viewModel)
    {
        PatientQueueView view = new();
        view.Bind(viewModel);
        return view;
    }

    private static ClinicalEditorView CreateClinicalEditorView(ClinicalEditorViewModel viewModel)
    {
        ClinicalEditorView view = new();
        view.Bind(viewModel);
        return view;
    }

    private static ClinicalReminderView CreateClinicalReminderView(ClinicalReminderViewModel viewModel)
    {
        ClinicalReminderView view = new();
        view.Bind(viewModel);
        return view;
    }

    private BusinessCompositePageView CreateBusinessCompositePageView(BusinessCompositePageViewModel viewModel)
    {
        BusinessCompositePageView view = new(this);
        view.Bind(viewModel);
        return view;
    }

    private ArchitectureValidationView CreateArchitectureValidationView(ArchitectureValidationViewModel viewModel)
    {
        ArchitectureValidationView view = new(this);
        view.Bind(viewModel);
        return view;
    }

    private static PatientSearchView CreatePatientSearchView(PatientSearchViewModel viewModel)
    {
        PatientSearchView view = new();
        view.Bind(viewModel);
        return view;
    }

    private static AuditTimelineView CreateAuditTimelineView(AuditTimelineViewModel viewModel)
    {
        AuditTimelineView view = new();
        view.Bind(viewModel);
        return view;
    }

    private static MetricCardView CreateMetricCardView(MetricCardViewModel viewModel)
    {
        MetricCardView view = new();
        view.Bind(viewModel);
        return view;
    }

    private static BedOverviewView CreateBedOverviewView(BedOverviewViewModel viewModel)
    {
        BedOverviewView view = new();
        view.Bind(viewModel);
        return view;
    }

    private static AdmissionCoordinatorView CreateAdmissionCoordinatorView(AdmissionCoordinatorViewModel viewModel)
    {
        AdmissionCoordinatorView view = new();
        view.Bind(viewModel);
        return view;
    }

    private static NursingTaskBoardView CreateNursingTaskBoardView(NursingTaskBoardViewModel viewModel)
    {
        NursingTaskBoardView view = new();
        view.Bind(viewModel);
        return view;
    }

    private static WardRiskPanelView CreateWardRiskPanelView(WardRiskPanelViewModel viewModel)
    {
        WardRiskPanelView view = new();
        view.Bind(viewModel);
        return view;
    }

    private static LabOrderComposerView CreateLabOrderComposerView(LabOrderComposerViewModel viewModel)
    {
        LabOrderComposerView view = new();
        view.Bind(viewModel);
        return view;
    }

    private static SpecimenTrackerView CreateSpecimenTrackerView(SpecimenTrackerViewModel viewModel)
    {
        SpecimenTrackerView view = new();
        view.Bind(viewModel);
        return view;
    }

    private static CriticalValueMonitorView CreateCriticalValueMonitorView(CriticalValueMonitorViewModel viewModel)
    {
        CriticalValueMonitorView view = new();
        view.Bind(viewModel);
        return view;
    }

    private static LabTurnaroundBoardView CreateLabTurnaroundBoardView(LabTurnaroundBoardViewModel viewModel)
    {
        LabTurnaroundBoardView view = new();
        view.Bind(viewModel);
        return view;
    }

    private static PrescriptionReviewBoardView CreatePrescriptionReviewBoardView(PrescriptionReviewBoardViewModel viewModel)
    {
        PrescriptionReviewBoardView view = new();
        view.Bind(viewModel);
        return view;
    }

    private static DrugStockMonitorView CreateDrugStockMonitorView(DrugStockMonitorViewModel viewModel)
    {
        DrugStockMonitorView view = new();
        view.Bind(viewModel);
        return view;
    }

    private static ReplenishmentPlannerView CreateReplenishmentPlannerView(ReplenishmentPlannerViewModel viewModel)
    {
        ReplenishmentPlannerView view = new();
        view.Bind(viewModel);
        return view;
    }

    private static MedicationSafetyPanelView CreateMedicationSafetyPanelView(MedicationSafetyPanelViewModel viewModel)
    {
        MedicationSafetyPanelView view = new();
        view.Bind(viewModel);
        return view;
    }

    private static QualityKpiBoardView CreateQualityKpiBoardView(QualityKpiBoardViewModel viewModel)
    {
        QualityKpiBoardView view = new();
        view.Bind(viewModel);
        return view;
    }

    private static MedicalRecordAuditBoardView CreateMedicalRecordAuditBoardView(MedicalRecordAuditBoardViewModel viewModel)
    {
        MedicalRecordAuditBoardView view = new();
        view.Bind(viewModel);
        return view;
    }

    private static RiskEventBoardView CreateRiskEventBoardView(RiskEventBoardViewModel viewModel)
    {
        RiskEventBoardView view = new();
        view.Bind(viewModel);
        return view;
    }

    private static RectificationTrackerView CreateRectificationTrackerView(RectificationTrackerViewModel viewModel)
    {
        RectificationTrackerView view = new();
        view.Bind(viewModel);
        return view;
    }
}

""";
    }
}
