using System.Collections.Generic;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace MiKiNuo.Mvi.Infrastructure.BuildTime.SourceGeneration;

/// <summary>
/// 表示泛型编译期 DI 容器源生成器。
/// 通过扫描 [DiService] 特性和 MviReducerBase 子类，
/// 为任意项目生成 DI 容器注册代码，不再硬编码特定程序集。
/// </summary>
[Generator]
public sealed class MviDiContainerGenerator : IIncrementalGenerator
{
    private static readonly SymbolDisplayFormat TypeFormat = SymbolDisplayFormat.FullyQualifiedFormat
        .WithMiscellaneousOptions(
            SymbolDisplayMiscellaneousOptions.IncludeNullableReferenceTypeModifier
            | SymbolDisplayMiscellaneousOptions.UseSpecialTypes);

    /// <inheritdoc />
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        context.RegisterSourceOutput(context.CompilationProvider, Execute);
    }

    private static void Execute(SourceProductionContext context, Compilation compilation)
    {
        if (!HasDiServices(compilation, context.CancellationToken))
        {
            return;
        }

        string source = GenerateContainerSource(compilation, context.CancellationToken);
        context.AddSource("GeneratedMviContainer.g.cs", SourceText.From(source, Encoding.UTF8));
    }

    /// <summary>
    /// 检查编译中是否包含 [DiService] 标记的类。
    /// </summary>
    private static bool HasDiServices(Compilation compilation, System.Threading.CancellationToken ct)
    {
        foreach (SyntaxTree tree in compilation.SyntaxTrees)
        {
            SyntaxNode root = tree.GetRoot(ct);
            foreach (ClassDeclarationSyntax classDecl in root.DescendantNodes().OfType<ClassDeclarationSyntax>())
            {
                foreach (AttributeListSyntax attributeList in classDecl.AttributeLists)
                {
                    foreach (AttributeSyntax attribute in attributeList.Attributes)
                    {
                        string? attrName = attribute.Name.ToString();
                        if (attrName is "DiService" or "DiServiceAttribute"
                            or "MviFeatureModule" or "MviFeatureModuleAttribute")
                        {
                            return true;
                        }
                    }
                }
            }
        }

        return false;
    }

    /// <summary>
    /// 生成泛型 DI 容器源码。
    /// </summary>
    private static string GenerateContainerSource(Compilation compilation, System.Threading.CancellationToken ct)
    {
        List<DiServiceInfo> services = DiscoverDiServices(compilation, ct);

        StringBuilder builder = new();
        string containerNamespace = compilation.AssemblyName ?? "GeneratedContainer";

        builder.AppendLine("// <auto-generated />");
        builder.AppendLine("#nullable enable");
        builder.AppendLine();
        builder.AppendLine("using System;");
        builder.AppendLine("using System.Collections.Generic;");
        builder.AppendLine("using MiKiNuo.Mvi.Application.DI;");
        builder.AppendLine("using MiKiNuo.Mvi.Domain.DI;");
        builder.AppendLine();

        HashSet<string> addedNamespaces = new HashSet<string>();

        foreach (DiServiceInfo service in services)
        {
            if (service.Namespace is { Length: > 0 } ns && addedNamespaces.Add(ns))
            {
                builder.Append("using ").Append(ns).AppendLine(";");
            }
        }

        builder.AppendLine();
        builder.Append("namespace ").Append(containerNamespace).AppendLine(".Composition;");
        builder.AppendLine();
        builder.AppendLine("/// <summary>");
        builder.AppendLine("/// 表示由 MVI 源生成器自动生成的泛型 DI 容器。");
        builder.AppendLine("/// 所有服务通过 [DiService] 特性自动注册。");
        builder.AppendLine("/// </summary>");
        builder.Append("public sealed class GeneratedMviContainer : IMviResolver, IMviServiceGraph");
        builder.AppendLine();
        builder.AppendLine("{");
        builder.AppendLine("    private readonly Dictionary<Type, object> _singletons = new();");

        foreach (DiServiceInfo service in services)
        {
            if (service.IsSingleton && service.ImplementationTypeName is { Length: > 0 })
            {
                builder.Append("    private readonly ").Append(service.ImplementationTypeName)
                    .Append(' ').Append(service.GetFieldName()).AppendLine(";");
            }
        }

        builder.AppendLine();
        builder.AppendLine("    /// <summary>");
        builder.AppendLine("    /// 初始化由源生成器生成的泛型 DI 容器。");
        builder.AppendLine("    /// </summary>");
        builder.AppendLine("    public GeneratedMviContainer()");
        builder.AppendLine("    {");

        foreach (DiServiceInfo service in services)
        {
            if (service.IsSingleton && service.ImplementationTypeName is { Length: > 0 })
            {
                builder.Append("        ").Append(service.GetFieldName())
                    .Append(" = new ").Append(service.ImplementationTypeName).AppendLine("();");
            }
        }

        builder.AppendLine("    }");
        builder.AppendLine();
        builder.AppendLine("    /// <inheritdoc />");
        builder.AppendLine("    public IReadOnlyList<MviServiceDescriptor> ServiceDescriptors => _descriptors;");
        builder.AppendLine();
        builder.AppendLine("    private static readonly IReadOnlyList<MviServiceDescriptor> _descriptors = new MviServiceDescriptor[]");
        builder.AppendLine("    {");

        foreach (DiServiceInfo service in services)
        {
            builder.Append("        new(typeof(").Append(service.ServiceTypeName).Append("), typeof(")
                .Append(service.ImplementationTypeName).Append("), ServiceLifetime.")
                .Append(service.Lifetime.ToPascalCase()).AppendLine("),");
        }

        builder.AppendLine("    };");
        builder.AppendLine();
        builder.AppendLine("    /// <inheritdoc />");
        builder.AppendLine("    public TService Resolve<TService>()");
        builder.AppendLine("        where TService : notnull");
        builder.AppendLine("    {");
        builder.AppendLine("        return (TService)Resolve(typeof(TService));");
        builder.AppendLine("    }");
        builder.AppendLine();
        builder.AppendLine("    /// <inheritdoc />");
        builder.AppendLine("    public object Resolve(Type serviceType)");
        builder.AppendLine("    {");
        builder.AppendLine("        if (serviceType is null)");
        builder.AppendLine("        {");
        builder.AppendLine("            throw new ArgumentNullException(nameof(serviceType));");
        builder.AppendLine("        }");
        builder.AppendLine();

        foreach (DiServiceInfo service in services)
        {
            if (service.IsSingleton)
            {
                builder.Append("        if (serviceType == typeof(").Append(service.ServiceTypeName)
                    .AppendLine("))");
                builder.Append("            return ").Append(service.GetFieldName()).AppendLine(";");
            }
            else
            {
                builder.Append("        if (serviceType == typeof(").Append(service.ServiceTypeName)
                    .AppendLine("))");
                builder.Append("            return new ").Append(service.ImplementationTypeName).AppendLine("();");
            }
        }

        builder.AppendLine();
        builder.AppendLine("        throw new InvalidOperationException($\"未注册服务：{serviceType.FullName}\");");
        builder.AppendLine("    }");
        builder.AppendLine();
        builder.AppendLine("    /// <inheritdoc />");
        builder.AppendLine("    public IMviScope CreateScope()");
        builder.AppendLine("    {");
        builder.AppendLine("        return new GeneratedMviScope(this);");
        builder.AppendLine("    }");
        builder.AppendLine("}");
        builder.AppendLine();
        builder.AppendLine("/// <summary>");
        builder.AppendLine("/// 表示由源生成器生成的作用域实现。");
        builder.AppendLine("/// </summary>");
        builder.AppendLine("internal sealed class GeneratedMviScope : IMviScope");
        builder.AppendLine("{");
        builder.AppendLine("    private readonly GeneratedMviContainer _container;");
        builder.AppendLine();
        builder.AppendLine("    public GeneratedMviScope(GeneratedMviContainer container)");
        builder.AppendLine("    {");
        builder.AppendLine("        _container = container;");
        builder.AppendLine("    }");
        builder.AppendLine();
        builder.AppendLine("    public TService Resolve<TService>() where TService : notnull => _container.Resolve<TService>();");
        builder.AppendLine("    public object Resolve(Type serviceType) => _container.Resolve(serviceType);");
        builder.AppendLine("    public void Dispose() { }");
        builder.AppendLine("}");

        return builder.ToString();
    }

    /// <summary>
    /// 发现所有 [DiService] 标记的服务。
    /// </summary>
    private static List<DiServiceInfo> DiscoverDiServices(
        Compilation compilation,
        System.Threading.CancellationToken ct)
    {
        List<DiServiceInfo> result = new List<DiServiceInfo>();

        foreach (SyntaxTree tree in compilation.SyntaxTrees)
        {
            SyntaxNode root = tree.GetRoot(ct);
            SemanticModel semanticModel = compilation.GetSemanticModel(tree);

            foreach (ClassDeclarationSyntax classDecl in root.DescendantNodes().OfType<ClassDeclarationSyntax>())
            {
                ct.ThrowIfCancellationRequested();

                if (semanticModel.GetDeclaredSymbol(classDecl, ct) is not INamedTypeSymbol classSymbol)
                {
                    continue;
                }

                DiServiceInfo? info = ParseDiService(classSymbol);
                if (info is not null)
                {
                    result.Add(info);
                }
            }
        }

        return result;
    }

    /// <summary>
    /// 从类符号中解析 [DiService] 配置。
    /// </summary>
    private static DiServiceInfo? ParseDiService(INamedTypeSymbol classSymbol)
    {
        foreach (AttributeData attr in classSymbol.GetAttributes())
        {
            string? attrName = attr.AttributeClass?.Name;
            if (attrName is not ("DiService" or "DiServiceAttribute"))
            {
                continue;
            }

            string serviceTypeName = classSymbol.ToDisplayString(TypeFormat);
            string implementationTypeName = classSymbol.ToDisplayString(TypeFormat);
            string lifetime = "Singleton";
            string? @namespace = classSymbol.ContainingNamespace?.ToDisplayString();

            if (attr.ConstructorArguments.Length > 0
                && attr.ConstructorArguments[0].Value is int lifetimeValue)
            {
                lifetime = lifetimeValue switch
                {
                    0 => "Singleton",
                    1 => "Scoped",
                    2 => "Transient",
                    _ => "Singleton"
                };
            }

            foreach (KeyValuePair<string, TypedConstant> namedArgument in attr.NamedArguments)
            {
                if (namedArgument.Key == "ServiceType"
                    && namedArgument.Value.Value is INamedTypeSymbol serviceType)
                {
                    serviceTypeName = serviceType.ToDisplayString(TypeFormat);
                }
            }

            return new DiServiceInfo(serviceTypeName, implementationTypeName, lifetime, @namespace);
        }

        return null;
    }

    /// <summary>
    /// 表示发现的 DI 服务信息。
    /// </summary>
    private sealed record DiServiceInfo
    {
        public DiServiceInfo(
            string serviceTypeName,
            string implementationTypeName,
            string lifetime,
            string? @namespace)
        {
            ServiceTypeName = serviceTypeName;
            ImplementationTypeName = implementationTypeName;
            Lifetime = lifetime;
            Namespace = @namespace;
        }

        public string ServiceTypeName { get; }
        public string ImplementationTypeName { get; }
        public string Lifetime { get; }
        public string? Namespace { get; }
        public bool IsSingleton => Lifetime is "Singleton";

        public string GetFieldName()
        {
            string name = ServiceTypeName.Split('.').Last();
            return "_" + char.ToLowerInvariant(name[0]) + name.Substring(1);
        }
    }
}

/// <summary>
/// 字符串扩展方法。
/// </summary>
file static class StringExtensions
{
    public static string ToPascalCase(this string value)
    {
        if (value.Length == 0)
        {
            return value;
        }

        return char.ToUpperInvariant(value[0]) + value.Substring(1);
    }
}
