using System.Collections.Generic;
using System.Text;
using Microsoft.CodeAnalysis;

namespace MiKiNuo.Mvi.Infrastructure.BuildTime.SourceGeneration;

/// <summary>
/// 表示 <see cref="MviDiContainerGenerator"/> 的容器主体发射部分。
/// </summary>
public sealed partial class MviDiContainerGenerator
{
    /// <summary>
    /// 表示 <see cref="MviDiContainerGenerator"/> 的代码发射阶段：
    /// 根据 <see cref="Models.DiServiceInfo"/> 列表生成 DI 容器源码字符串。
    /// </summary>
    internal static partial class Emission
    {
        /// <summary>
        /// 生成 DI 容器源码。
        /// </summary>
        /// <param name="assemblyName">目标程序集名称（用作容器命名空间）。</param>
        /// <param name="services">分析得到的 DI 服务信息。</param>
        /// <param name="features">分析得到的 Feature Store 装配信息。</param>
        /// <returns>生成的 C# 源码。</returns>
        public static string GenerateContainerSource(
            string assemblyName,
            IReadOnlyList<Models.DiServiceInfo> services,
            IReadOnlyList<Models.FeatureStoreInfo> features)
        {
            StringBuilder builder = new();
            string containerNamespace = string.IsNullOrEmpty(assemblyName) ? "GeneratedContainer" : assemblyName;

            EmitFileHeader(builder, containerNamespace, services);
            EmitConstructor(builder, services);
            EmitResolveMethods(builder, services, features);
            EmitFeatureStoreFactories(builder, features);
            EmitCreateScope(builder);
            EmitCreateWith(builder, services);
            EmitScopeClass(builder, services);

            return builder.ToString();
        }

        /// <summary>
        /// 生成文件头：using、namespace、类声明与字段。
        /// </summary>
        private static void EmitFileHeader(
            StringBuilder builder,
            string containerNamespace,
            IReadOnlyList<Models.DiServiceInfo> services)
        {
            builder.AppendLine("// <auto-generated />");
            builder.AppendLine("#nullable enable");
            builder.AppendLine();
            builder.AppendLine("using System;");
            builder.AppendLine("using System.Collections.Generic;");
            builder.AppendLine("using MiKiNuo.Mvi.Application.DI;");
            builder.AppendLine("using MiKiNuo.Mvi.Domain.DI;");
            builder.AppendLine();

            HashSet<string> addedNamespaces = new HashSet<string>();
            foreach (Models.DiServiceInfo service in services)
            {
                if (service.Namespace is { Length: > 0 } ns && addedNamespaces.Add(ns))
                {
                    builder.Append("using ").Append(ns).AppendLine(";");
                }
            }

            builder.AppendLine();
            builder.Append("namespace ").Append(containerNamespace).AppendLine(".Composition;");
            builder.AppendLine();
            builder.AppendLine("/// <summary>");
            builder.AppendLine("/// 表示由 MVI 源生成器自动生成的泛型 DI 容器。");
            builder.AppendLine("/// 所有服务通过 [DiService] 特性自动注册。");
            builder.AppendLine("/// 单例使用按需懒加载，避免构造期因未注册依赖而失败。");
            builder.AppendLine("/// </summary>");
            builder.Append("public sealed class GeneratedMviContainer : IMviResolver, IMviServiceGraph");
            builder.AppendLine();
            builder.AppendLine("{");
            builder.AppendLine("    private readonly Dictionary<Type, object> _singletons = new();");
            builder.AppendLine();
        }

        /// <summary>
        /// 生成构造函数与服务描述符字段。
        /// </summary>
        private static void EmitConstructor(StringBuilder builder, IReadOnlyList<Models.DiServiceInfo> services)
        {
            builder.AppendLine("    /// <summary>");
            builder.AppendLine("    /// 初始化由源生成器生成的泛型 DI 容器。");
            builder.AppendLine("    /// 仅注册服务描述符，不做服务实例化，避免构造期出现未注册依赖的级联失败。");
            builder.AppendLine("    /// </summary>");
            builder.AppendLine("    public GeneratedMviContainer()");
            builder.AppendLine("    {");
            builder.AppendLine("    }");
            builder.AppendLine();
            builder.AppendLine("    /// <summary>");
            builder.AppendLine("    /// 获取服务描述集合。");
            builder.AppendLine("    /// </summary>");
            builder.AppendLine("    public IReadOnlyList<MviServiceDescriptor> ServiceDescriptors => _descriptors;");
            builder.AppendLine();
            builder.AppendLine("    private static readonly IReadOnlyList<MviServiceDescriptor> _descriptors = new MviServiceDescriptor[]");
            builder.AppendLine("    {");

            foreach (Models.DiServiceInfo service in services)
            {
                builder.Append("        new(typeof(").Append(service.ServiceTypeName).Append("), typeof(")
                    .Append(service.ImplementationTypeName).Append("), ServiceLifetime.")
                    .Append(service.Lifetime.ToServiceLifetimeName()).AppendLine("),");
            }

            builder.AppendLine("    };");
            builder.AppendLine();
        }

        /// <summary>
        /// 生成 Resolve&lt;T&gt; 与 Resolve(Type) 方法。
        /// </summary>
        private static void EmitResolveMethods(
            StringBuilder builder,
            IReadOnlyList<Models.DiServiceInfo> services,
            IReadOnlyList<Models.FeatureStoreInfo> features)
        {
            EmitResolveGeneric(builder);
            EmitResolveByType(builder, services, features);
        }

        /// <summary>
        /// 生成 Resolve&lt;T&gt; 泛型方法。
        /// </summary>
        private static void EmitResolveGeneric(StringBuilder builder)
        {
            builder.AppendLine("    /// <summary>");
            builder.AppendLine("    /// 解析服务。");
            builder.AppendLine("    /// </summary>");
            builder.AppendLine("    /// <typeparam name=\"TService\">服务类型。</typeparam>");
            builder.AppendLine("    /// <returns>服务实例。</returns>");
            builder.AppendLine("    public TService Resolve<TService>()");
            builder.AppendLine("        where TService : notnull");
            builder.AppendLine("    {");
            builder.AppendLine("        return (TService)Resolve(typeof(TService));");
            builder.AppendLine("    }");
            builder.AppendLine();
        }

        /// <summary>
        /// 生成 Resolve(Type) 非泛型方法。
        /// </summary>
        private static void EmitResolveByType(
            StringBuilder builder,
            IReadOnlyList<Models.DiServiceInfo> services,
            IReadOnlyList<Models.FeatureStoreInfo> features)
        {
            builder.AppendLine("    /// <summary>");
            builder.AppendLine("    /// 解析指定类型的服务。");
            builder.AppendLine("    /// </summary>");
            builder.AppendLine("    /// <param name=\"serviceType\">服务类型。</param>");
            builder.AppendLine("    /// <returns>服务实例。</returns>");
            builder.AppendLine("    public object Resolve(Type serviceType)");
            builder.AppendLine("    {");
            builder.AppendLine("        if (serviceType is null)");
            builder.AppendLine("        {");
            builder.AppendLine("            throw new ArgumentNullException(nameof(serviceType));");
            builder.AppendLine("        }");
            builder.AppendLine();
            builder.AppendLine("        if (_singletons.TryGetValue(serviceType, out object? existing))");
            builder.AppendLine("        {");
            builder.AppendLine("            return existing;");
            builder.AppendLine("        }");
            builder.AppendLine();
            foreach (Models.DiServiceInfo service in services)
            {
                builder.Append("        if (serviceType == typeof(").Append(service.ServiceTypeName)
                    .AppendLine("))");
                if (service.Lifetime == Models.GeneratedLifetime.Singleton)
                {
                    builder.Append("        {").AppendLine();
                    builder.Append("            object created = new ").Append(service.ImplementationTypeName).Append('(');
                    builder.Append(string.Join(", ", service.ConstructorArgumentExpressions));
                    builder.AppendLine(");");
                    builder.Append("            _singletons[serviceType] = created;").AppendLine();
                    builder.Append("            return created;").AppendLine();
                    builder.Append("        }").AppendLine();
                }
                else
                {
                    builder.Append("            return new ").Append(service.ImplementationTypeName).Append('(');
                    builder.Append(string.Join(", ", service.ConstructorArgumentExpressions));
                    builder.AppendLine(");");
                }
            }

            foreach (Models.FeatureStoreInfo feature in features)
            {
                builder.Append("        if (serviceType == typeof(global::MiKiNuo.Mvi.Application.MVI.Store.IMviStore<")
                    .Append(feature.StateTypeName).Append(", ")
                    .Append(feature.IntentTypeName).Append(", ")
                    .Append(feature.EffectTypeName).AppendLine(">))");
                builder.AppendLine("        {");
                builder.Append("            object created = Create").Append(feature.GetSafeMethodKey()).AppendLine("FeatureStore();");
                builder.AppendLine("            _singletons[serviceType] = created;");
                builder.AppendLine("            return created;");
                builder.AppendLine("        }");
                builder.AppendLine();
            }

            builder.AppendLine();
            builder.AppendLine("        throw new InvalidOperationException($\"未注册服务：{serviceType.FullName}\");");
            builder.AppendLine("    }");
            builder.AppendLine();
        }

        /// <summary>
        /// 生成 CreateScope 方法。
        /// </summary>
        private static void EmitCreateScope(StringBuilder builder)
        {
            builder.AppendLine("    /// <summary>");
            builder.AppendLine("    /// 创建作用域。");
            builder.AppendLine("    /// </summary>");
            builder.AppendLine("    /// <returns>服务作用域。</returns>");
            builder.AppendLine("    public IMviScope CreateScope()");
            builder.AppendLine("    {");
            builder.AppendLine("        return new GeneratedMviScope(this);");
            builder.AppendLine("    }");
            builder.AppendLine();
        }

        /// <summary>
        /// 生成 CreateWith&lt;T&gt; 与 CreateWithCore 方法。
        /// </summary>
        private static void EmitCreateWith(StringBuilder builder, IReadOnlyList<Models.DiServiceInfo> services)
        {
            EmitCreateWithGeneric(builder);
            EmitCreateWithCore(builder, services);
        }

        /// <summary>
        /// 生成 CreateWith&lt;T&gt; 泛型方法。
        /// </summary>
        private static void EmitCreateWithGeneric(StringBuilder builder)
        {
            builder.AppendLine("    /// <summary>");
            builder.AppendLine("    /// 按构造参数即时构造服务实例。");
            builder.AppendLine("    /// </summary>");
            builder.AppendLine("    /// <typeparam name=\"TService\">要实例化的服务类型。</typeparam>");
            builder.AppendLine("    /// <param name=\"args\">构造函数实参。</param>");
            builder.AppendLine("    /// <returns>新构造的实例。</returns>");
            builder.AppendLine("    public TService CreateWith<TService>(params object[] args)");
            builder.AppendLine("        where TService : notnull");
            builder.AppendLine("    {");
            builder.AppendLine("        if (args is null)");
            builder.AppendLine("        {");
            builder.AppendLine("            throw new ArgumentNullException(nameof(args));");
            builder.AppendLine("        }");
            builder.AppendLine();
            builder.AppendLine("        return (TService)CreateWithCore(typeof(TService), args);");
            builder.AppendLine("    }");
            builder.AppendLine();
        }

        /// <summary>
        /// 生成 CreateWithCore 核心方法。
        /// </summary>
        private static void EmitCreateWithCore(StringBuilder builder, IReadOnlyList<Models.DiServiceInfo> services)
        {
            builder.AppendLine("    /// <summary>");
            builder.AppendLine("    /// 按构造参数即时构造并返回服务实例的核心实现。");
            builder.AppendLine("    /// 不走单例缓存，按运行时参数匹配公共构造函数。");
            builder.AppendLine("    /// </summary>");
            builder.AppendLine("    private object CreateWithCore(Type serviceType, object[] args)");
            builder.AppendLine("    {");
            builder.AppendLine("        if (serviceType is null)");
            builder.AppendLine("        {");
            builder.AppendLine("            throw new ArgumentNullException(nameof(serviceType));");
            builder.AppendLine("        }");
            builder.AppendLine();
            EmitCreateWithZeroArgs(builder, services);
            EmitCreateWithOneArg(builder, services);
            builder.AppendLine("        throw new InvalidOperationException($\"CreateWith 暂不支持 {args.Length} 个参数的构造：{serviceType.FullName}\");");
            builder.AppendLine("    }");
        }

        /// <summary>
        /// 生成 CreateWithCore 零参分支。
        /// </summary>
        private static void EmitCreateWithZeroArgs(StringBuilder builder, IReadOnlyList<Models.DiServiceInfo> services)
        {
            builder.AppendLine("        if (args.Length == 0)");
            builder.AppendLine("        {");
            foreach (Models.DiServiceInfo service in services)
            {
                builder.Append("            if (serviceType == typeof(").Append(service.ImplementationTypeName)
                    .AppendLine("))");
                builder.Append("            {").AppendLine();
                builder.Append("                return new ").Append(service.ImplementationTypeName).Append('(');
                builder.Append(string.Join(", ", service.ConstructorArgumentExpressions));
                builder.AppendLine(");");
                builder.Append("            }").AppendLine();
            }
            builder.AppendLine("            throw new InvalidOperationException($\"CreateWith 未注册实现类型：{serviceType.FullName}\");");
            builder.AppendLine("        }");
            builder.AppendLine();
        }

        /// <summary>
        /// 生成 CreateWithCore 单参分支。
        /// </summary>
        private static void EmitCreateWithOneArg(StringBuilder builder, IReadOnlyList<Models.DiServiceInfo> services)
        {
            builder.AppendLine("        if (args.Length == 1)");
            builder.AppendLine("        {");
            foreach (Models.DiServiceInfo service in services)
            {
                if (service.ConstructorParameterTypeNames.Count != 1)
                {
                    continue;
                }

                builder.Append("            if (serviceType == typeof(").Append(service.ImplementationTypeName)
                    .Append(") && args[0] is ").Append(service.ConstructorParameterTypeNames[0])
                    .AppendLine(" a0)");
                builder.Append("            {").AppendLine();
                builder.Append("                return new ").Append(service.ImplementationTypeName).Append("(a0")
                    .AppendLine(");");
                builder.Append("            }").AppendLine();
            }
            builder.AppendLine("            throw new InvalidOperationException($\"CreateWith 未找到匹配 1 个参数的构造函数：{serviceType.FullName}\");");
            builder.AppendLine("        }");
            builder.AppendLine();
        }

        /// <summary>
        /// 生成作用域嵌套类。
        /// </summary>
        private static void EmitScopeClass(
            StringBuilder builder,
            IReadOnlyList<Models.DiServiceInfo> services)
        {
            builder.AppendLine("}");
            builder.AppendLine();
            builder.AppendLine("/// <summary>");
            builder.AppendLine("/// 表示由源生成器生成的作用域实现。");
            builder.AppendLine("/// </summary>");
            builder.AppendLine("internal sealed class GeneratedMviScope : IMviScope");
            builder.AppendLine();
            builder.AppendLine("{");
            builder.AppendLine("    private readonly GeneratedMviContainer _container;");
            builder.AppendLine("    private readonly Dictionary<Type, object> _scoped = new();");
            builder.AppendLine("    private bool _isDisposed;");
            builder.AppendLine();
            builder.AppendLine("    public GeneratedMviScope(GeneratedMviContainer container)");
            builder.AppendLine("    {");
            builder.AppendLine("        _container = container;");
            builder.AppendLine("    }");
            builder.AppendLine();
            builder.AppendLine("    public TService Resolve<TService>() where TService : notnull => (TService)Resolve(typeof(TService));");
            builder.AppendLine();
            builder.AppendLine("    public object Resolve(Type serviceType)");
            builder.AppendLine("    {");
            builder.AppendLine("        ObjectDisposedException.ThrowIf(_isDisposed, this);");
            builder.AppendLine("        ArgumentNullException.ThrowIfNull(serviceType);");
            builder.AppendLine();
            builder.AppendLine("        if (_scoped.TryGetValue(serviceType, out object? existing))");
            builder.AppendLine("        {");
            builder.AppendLine("            return existing;");
            builder.AppendLine("        }");
            builder.AppendLine();

            foreach (Models.DiServiceInfo service in services)
            {
                builder.Append("        if (serviceType == typeof(").Append(service.ServiceTypeName)
                    .AppendLine("))");
                builder.AppendLine("        {");

                if (service.Lifetime == Models.GeneratedLifetime.Singleton)
                {
                    builder.AppendLine("            return _container.Resolve(serviceType);");
                }
                else
                {
                    builder.Append("            object created = new ").Append(service.ImplementationTypeName).Append('(');
                    builder.Append(string.Join(", ", service.ConstructorArgumentExpressions));
                    builder.AppendLine(");");
                    if (service.Lifetime == Models.GeneratedLifetime.Scoped)
                    {
                        builder.AppendLine("            _scoped[serviceType] = created;");
                    }

                    builder.AppendLine("            return created;");
                }

                builder.AppendLine("        }");
            }

            builder.AppendLine();
            builder.AppendLine("        throw new InvalidOperationException($\"未注册服务：{serviceType.FullName}\");");
            builder.AppendLine("    }");
            builder.AppendLine();
            builder.AppendLine("    public TService CreateWith<TService>(params object[] args) where TService : notnull => _container.CreateWith<TService>(args);");
            builder.AppendLine();
            builder.AppendLine("    public void Dispose()");
            builder.AppendLine("    {");
            builder.AppendLine("        if (_isDisposed)");
            builder.AppendLine("        {");
            builder.AppendLine("            return;");
            builder.AppendLine("        }");
            builder.AppendLine();
            builder.AppendLine("        foreach (object instance in _scoped.Values)");
            builder.AppendLine("        {");
            builder.AppendLine("            if (instance is IDisposable disposable)");
            builder.AppendLine("            {");
            builder.AppendLine("                disposable.Dispose();");
            builder.AppendLine("            }");
            builder.AppendLine("        }");
            builder.AppendLine();
            builder.AppendLine("        _scoped.Clear();");
            builder.AppendLine("        _isDisposed = true;");
            builder.AppendLine("    }");
            builder.AppendLine("}");
        }
    }
}
