using System.Collections.Generic;
using System.Text;

namespace MiKiNuo.Mvi.Infrastructure.BuildTime.SourceGeneration;

/// <summary>
/// 表示 <see cref="MviDiContainerGenerator"/> 的代码发射阶段：
/// 根据 <see cref="MviDiContainerModels.DiServiceInfo"/> 列表生成 DI 容器源码字符串。
/// </summary>
internal static class MviDiContainerEmission
{
    /// <summary>
    /// 生成 DI 容器源码。
    /// </summary>
    /// <param name="assemblyName">目标程序集名称（用作容器命名空间）。</param>
    /// <param name="services">分析得到的 DI 服务信息。</param>
    /// <returns>生成的 C# 源码。</returns>
    public static string GenerateContainerSource(
        string assemblyName,
        IReadOnlyList<MviDiContainerModels.DiServiceInfo> services)
    {
        StringBuilder builder = new();
        string containerNamespace = string.IsNullOrEmpty(assemblyName) ? "GeneratedContainer" : assemblyName;

        builder.AppendLine("// <auto-generated />");
        builder.AppendLine("#nullable enable");
        builder.AppendLine();
        builder.AppendLine("using System;");
        builder.AppendLine("using System.Collections.Generic;");
        builder.AppendLine("using MiKiNuo.Mvi.Application.DI;");
        builder.AppendLine("using MiKiNuo.Mvi.Domain.DI;");
        builder.AppendLine();

        HashSet<string> addedNamespaces = new HashSet<string>();

        foreach (MviDiContainerModels.DiServiceInfo service in services)
        {
            if (service.Namespace is { Length: > 0 } ns && addedNamespaces.Add(ns))
            {
                builder.Append("using ").Append(ns).AppendLine(";");
            }
        }

        builder.AppendLine();
        builder.Append("namespace ").Append(containerNamespace).AppendLine(".Composition;");
        builder.AppendLine();
        builder.AppendLine("/// <summary>");
        builder.AppendLine("/// 表示由 MVI 源生成器自动生成的泛型 DI 容器。");
        builder.AppendLine("/// 所有服务通过 [DiService] 特性自动注册。");
        builder.AppendLine("/// </summary>");
        builder.Append("public sealed class GeneratedMviContainer : IMviResolver, IMviServiceGraph");
        builder.AppendLine();
        builder.AppendLine("{");
        builder.AppendLine("    private readonly Dictionary<Type, object> _singletons = new();");

        foreach (MviDiContainerModels.DiServiceInfo service in services)
        {
            if (service.Lifetime == MviDiContainerModels.GeneratedLifetime.Singleton && service.ImplementationTypeName is { Length: > 0 })
            {
                builder.Append("    private readonly ").Append(service.ImplementationTypeName)
                    .Append(' ').Append(service.GetFieldName()).AppendLine(";");
            }
        }

        builder.AppendLine();
        builder.AppendLine("    /// <summary>");
        builder.AppendLine("    /// 初始化由源生成器生成的泛型 DI 容器。");
        builder.AppendLine("    /// </summary>");
        builder.AppendLine("    public GeneratedMviContainer()");
        builder.AppendLine("    {");

        foreach (MviDiContainerModels.DiServiceInfo service in services)
        {
            if (service.Lifetime == MviDiContainerModels.GeneratedLifetime.Singleton && service.ImplementationTypeName is { Length: > 0 })
            {
                builder.Append("        ").Append(service.GetFieldName())
                    .Append(" = new ").Append(service.ImplementationTypeName).AppendLine("();");
            }
        }

        builder.AppendLine("    }");
        builder.AppendLine();
        builder.AppendLine("    /// <inheritdoc />");
        builder.AppendLine("    public IReadOnlyList<MviServiceDescriptor> ServiceDescriptors => _descriptors;");
        builder.AppendLine();
        builder.AppendLine("    private static readonly IReadOnlyList<MviServiceDescriptor> _descriptors = new MviServiceDescriptor[]");
        builder.AppendLine("    {");

        foreach (MviDiContainerModels.DiServiceInfo service in services)
        {
            builder.Append("        new(typeof(").Append(service.ServiceTypeName).Append("), typeof(")
                .Append(service.ImplementationTypeName).Append("), ServiceLifetime.")
                .Append(service.Lifetime.ToServiceLifetimeName()).AppendLine("),");
        }

        builder.AppendLine("    };");
        builder.AppendLine();
        builder.AppendLine("    /// <inheritdoc />");
        builder.AppendLine("    public TService Resolve<TService>()");
        builder.AppendLine("        where TService : notnull");
        builder.AppendLine("    {");
        builder.AppendLine("        return (TService)Resolve(typeof(TService));");
        builder.AppendLine("    }");
        builder.AppendLine();
        builder.AppendLine("    /// <inheritdoc />");
        builder.AppendLine("    public object Resolve(Type serviceType)");
        builder.AppendLine("    {");
        builder.AppendLine("        if (serviceType is null)");
        builder.AppendLine("        {");
        builder.AppendLine("            throw new ArgumentNullException(nameof(serviceType));");
        builder.AppendLine("        }");
        builder.AppendLine();

        foreach (MviDiContainerModels.DiServiceInfo service in services)
        {
            if (service.Lifetime == MviDiContainerModels.GeneratedLifetime.Singleton)
            {
                builder.Append("        if (serviceType == typeof(").Append(service.ServiceTypeName)
                    .AppendLine("))");
                builder.Append("            return ").Append(service.GetFieldName()).AppendLine(";");
            }
            else
            {
                builder.Append("        if (serviceType == typeof(").Append(service.ServiceTypeName)
                    .AppendLine("))");
                builder.Append("            return new ").Append(service.ImplementationTypeName).AppendLine("();");
            }
        }

        builder.AppendLine();
        builder.AppendLine("        throw new InvalidOperationException($\"未注册服务：{serviceType.FullName}\");");
        builder.AppendLine("    }");
        builder.AppendLine();
        builder.AppendLine("    /// <inheritdoc />");
        builder.AppendLine("    public IMviScope CreateScope()");
        builder.AppendLine("    {");
        builder.AppendLine("        return new GeneratedMviScope(this);");
        builder.AppendLine("    }");
        builder.AppendLine("}");
        builder.AppendLine();
        builder.AppendLine("/// <summary>");
        builder.AppendLine("/// 表示由源生成器生成的作用域实现。");
        builder.AppendLine("/// </summary>");
        builder.AppendLine("internal sealed class GeneratedMviScope : IMviScope");
        builder.AppendLine("{");
        builder.AppendLine("    private readonly GeneratedMviContainer _container;");
        builder.AppendLine();
        builder.AppendLine("    public GeneratedMviScope(GeneratedMviContainer container)");
        builder.AppendLine("    {");
        builder.AppendLine("        _container = container;");
        builder.AppendLine("    }");
        builder.AppendLine();
        builder.AppendLine("    public TService Resolve<TService>() where TService : notnull => _container.Resolve<TService>();");
        builder.AppendLine("    public object Resolve(Type serviceType) => _container.Resolve(serviceType);");
        builder.AppendLine("    public void Dispose() { }");
        builder.AppendLine("}");

        return builder.ToString();
    }
}
