using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace MiKiNuo.Mvi.Infrastructure.BuildTime.SourceGeneration;

/// <summary>
/// 表示根据实例规约器方法生成 Reduce 分发逻辑的源生成器。
/// </summary>
[Generator]
public sealed class MviReducerGenerator : IIncrementalGenerator
{
    private static readonly SymbolDisplayFormat TypeFormat = SymbolDisplayFormat.FullyQualifiedFormat
        .WithMiscellaneousOptions(
            SymbolDisplayMiscellaneousOptions.IncludeNullableReferenceTypeModifier
            | SymbolDisplayMiscellaneousOptions.UseSpecialTypes);

    /// <inheritdoc />
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        context.RegisterSourceOutput(context.CompilationProvider, Execute);
    }

    private static void Execute(SourceProductionContext context, Compilation compilation)
    {
        foreach (INamedTypeSymbol reducerType in FindAllClasses(compilation, context.CancellationToken))
        {
            if (!reducerType.Name.EndsWith("Reducer", StringComparison.Ordinal))
            {
                continue;
            }

            List<ReducerMethodModel> methods = GetReducerMethods(reducerType);
            if (methods.Count == 0)
            {
                continue;
            }

            string source = GenerateReducerPartial(reducerType, methods);
            context.AddSource($"{reducerType.Name}.g.cs", SourceText.From(source, Encoding.UTF8));
        }
    }

    private static string GenerateReducerPartial(INamedTypeSymbol reducerType, IReadOnlyList<ReducerMethodModel> methods)
    {
        ReducerMethodModel first = methods[0];
        string namespaceName = reducerType.ContainingNamespace.ToDisplayString();
        StringBuilder builder = new StringBuilder();

        builder.AppendLine("// <auto-generated />");
        builder.AppendLine("#nullable enable");
        builder.AppendLine();
        builder.Append("namespace ").Append(namespaceName).AppendLine(";");
        builder.AppendLine();
        builder.AppendLine("/// <summary>");
        builder.AppendLine("/// 表示由 MVI 源生成器生成的实例规约分发逻辑。");
        builder.AppendLine("/// </summary>");
        builder.Append("public sealed partial class ").Append(reducerType.Name).AppendLine();
        builder.AppendLine("{");
        builder.AppendLine("    /// <inheritdoc />");
        builder.Append("    public override global::MiKiNuo.Mvi.Domain.MVI.Reducer.MviReduceResult<")
            .Append(first.StateTypeName).Append(", ").Append(first.EffectTypeName).Append("> Reduce(")
            .Append(first.StateTypeName).Append(" state, ").Append(first.RootIntentTypeName).AppendLine(" intent)");
        builder.AppendLine("    {");
        builder.AppendLine("        global::System.ArgumentNullException.ThrowIfNull(state);");
        builder.AppendLine("        global::System.ArgumentNullException.ThrowIfNull(intent);");
        builder.AppendLine();
        builder.AppendLine("        return intent switch");
        builder.AppendLine("        {");
        foreach (ReducerMethodModel method in methods)
        {
            builder.Append("            ").Append(method.IntentTypeName).Append(" typedIntent => ")
                .Append(method.MethodName).AppendLine("(state, typedIntent),");
        }
        builder.Append("            _ => global::MiKiNuo.Mvi.Domain.MVI.Reducer.MviReduceResult.State<")
            .Append(first.StateTypeName).Append(", ").Append(first.EffectTypeName).AppendLine(">(state)");
        builder.AppendLine("        };");
        builder.AppendLine("    }");
        builder.AppendLine("}");
        return builder.ToString();
    }

    private static List<ReducerMethodModel> GetReducerMethods(INamedTypeSymbol reducerType)
    {
        List<ReducerMethodModel> result = new List<ReducerMethodModel>();

        foreach (IMethodSymbol method in reducerType.GetMembers().OfType<IMethodSymbol>())
        {
            if (method.IsStatic || method.Parameters.Length != 2)
            {
                continue;
            }

            if (!HasReduceAttribute(method))
            {
                continue;
            }

            if (method.ReturnType is not INamedTypeSymbol returnType || returnType.TypeArguments.Length != 2)
            {
                continue;
            }

            ITypeSymbol stateType = method.Parameters[0].Type;
            ITypeSymbol intentType = method.Parameters[1].Type;
            ITypeSymbol effectType = returnType.TypeArguments[1];
            ITypeSymbol rootIntentType = GetRootIntentType(intentType);

            result.Add(new ReducerMethodModel(
                method.Name,
                stateType.ToDisplayString(TypeFormat),
                intentType.ToDisplayString(TypeFormat),
                rootIntentType.ToDisplayString(TypeFormat),
                effectType.ToDisplayString(TypeFormat)));
        }

        return result;
    }

    private static bool HasReduceAttribute(IMethodSymbol method)
    {
        foreach (AttributeData attribute in method.GetAttributes())
        {
            string? attributeName = attribute.AttributeClass?.Name;
            if (attributeName == "MviReduceAttribute" || attributeName == "MviReducerAttribute")
            {
                return true;
            }
        }

        return false;
    }

    private static ITypeSymbol GetRootIntentType(ITypeSymbol intentType)
    {
        ITypeSymbol current = intentType;
        while (current.BaseType is not null && current.BaseType.SpecialType != SpecialType.System_Object)
        {
            current = current.BaseType;
        }

        return current;
    }

    private static IEnumerable<INamedTypeSymbol> FindAllClasses(Compilation compilation, System.Threading.CancellationToken cancellationToken)
    {
        foreach (SyntaxTree tree in compilation.SyntaxTrees)
        {
            SyntaxNode root = tree.GetRoot(cancellationToken);
            SemanticModel semanticModel = compilation.GetSemanticModel(tree);
            foreach (ClassDeclarationSyntax declaration in root.DescendantNodes().OfType<ClassDeclarationSyntax>())
            {
                cancellationToken.ThrowIfCancellationRequested();
                if (semanticModel.GetDeclaredSymbol(declaration, cancellationToken) is INamedTypeSymbol symbol)
                {
                    yield return symbol;
                }
            }
        }
    }

    private sealed class ReducerMethodModel
    {
        public ReducerMethodModel(
            string methodName,
            string stateTypeName,
            string intentTypeName,
            string rootIntentTypeName,
            string effectTypeName)
        {
            MethodName = methodName;
            StateTypeName = stateTypeName;
            IntentTypeName = intentTypeName;
            RootIntentTypeName = rootIntentTypeName;
            EffectTypeName = effectTypeName;
        }

        public string MethodName { get; }

        public string StateTypeName { get; }

        public string IntentTypeName { get; }

        public string RootIntentTypeName { get; }

        public string EffectTypeName { get; }
    }
}
