using System.Collections.Generic;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;

namespace MiKiNuo.Mvi.Infrastructure.BuildTime.SourceGeneration;

/// <summary>
/// 表示根据静态 Reducer 类中的 Reduce 方法生成规约分发器的源生成器。
/// 扫描名称以 "Reducers" 结尾的类，为其中的静态 Reduce 方法生成分发调度代码。
/// </summary>
[Generator]
public sealed class MviReducerDispatcherGenerator : MviReducerGeneratorBase
{
    /// <inheritdoc />
    protected override bool IsTargetClass(INamedTypeSymbol symbol)
    {
        return symbol.Name.EndsWith("Reducers", System.StringComparison.Ordinal);
    }

    /// <inheritdoc />
    protected override List<ReducerMethodModel> GetReducerMethods(INamedTypeSymbol reducersType)
    {
        List<ReducerMethodModel> result = [];

        foreach (IMethodSymbol method in reducersType.GetMembers().OfType<IMethodSymbol>())
        {
            if (!method.IsStatic || method.Name != "Reduce" || method.Parameters.Length != 2)
            {
                continue;
            }

            if (method.ReturnType is not INamedTypeSymbol returnType || returnType.TypeArguments.Length != 2)
            {
                continue;
            }

            ITypeSymbol stateType = method.Parameters[0].Type;
            ITypeSymbol intentType = method.Parameters[1].Type;
            ITypeSymbol effectType = returnType.TypeArguments[1];
            ITypeSymbol rootIntentType = GetRootIntentType(intentType);

            result.Add(new ReducerMethodModel(
                method.Name,
                stateType.ToDisplayString(TypeFormat),
                intentType.ToDisplayString(TypeFormat),
                rootIntentType.ToDisplayString(TypeFormat),
                effectType.ToDisplayString(TypeFormat)));
        }

        return result;
    }

    /// <inheritdoc />
    protected override string GenerateSource(INamedTypeSymbol reducersType, IReadOnlyList<ReducerMethodModel> methods)
    {
        ReducerMethodModel first = methods[0];
        string namespaceName = reducersType.ContainingNamespace.ToDisplayString();
        string dispatcherName = reducersType.Name.Substring(0, reducersType.Name.Length - "Reducers".Length) + "ReducerDispatcher";
        StringBuilder builder = new();

        builder.AppendLine("// <auto-generated />");
        builder.AppendLine("#nullable enable");
        builder.AppendLine();
        builder.Append("namespace ").Append(namespaceName).AppendLine(";");
        builder.AppendLine();
        builder.AppendLine("/// <summary>");
        builder.AppendLine("/// 表示由 MVI 源生成器生成的规约分发器。");
        builder.AppendLine("/// </summary>");
        builder.Append("public sealed class ").Append(dispatcherName).AppendLine();
        builder.Append("    : global::MiKiNuo.Mvi.Application.MVI.Reducer.IMviReducerDispatcher<")
            .Append(first.StateTypeName).Append(", ").Append(first.RootIntentTypeName).Append(", ").Append(first.EffectTypeName).AppendLine(">");
        builder.AppendLine("{");
        builder.AppendLine("    /// <inheritdoc />");
        builder.Append("    public global::MiKiNuo.Mvi.Domain.MVI.Reducer.MviReduceResult<")
            .Append(first.StateTypeName).Append(", ").Append(first.EffectTypeName).Append("> Reduce(")
            .Append(first.StateTypeName).Append(" state, ").Append(first.RootIntentTypeName).AppendLine(" intent)");
        builder.AppendLine("    {");
        builder.AppendLine("        return intent switch");
        builder.AppendLine("        {");
        foreach (ReducerMethodModel method in methods)
        {
            builder.Append("            ").Append(method.IntentTypeName).Append(" typedIntent => ")
                .Append(reducersType.ToDisplayString(TypeFormat)).Append('.').Append(method.MethodName)
                .AppendLine("(state, typedIntent),");
        }
        builder.Append("            _ => global::MiKiNuo.Mvi.Domain.MVI.Reducer.MviReduceResult.State<")
            .Append(first.StateTypeName).Append(", ").Append(first.EffectTypeName).AppendLine(">(state)");
        builder.AppendLine("        };");
        builder.AppendLine("    }");
        builder.AppendLine("}");
        return builder.ToString();
    }

    /// <inheritdoc />
    protected override string GetOutputFileName(INamedTypeSymbol symbol)
    {
        string dispatcherName = symbol.Name.Substring(0, symbol.Name.Length - "Reducers".Length) + "ReducerDispatcher";
        return $"{dispatcherName}.g.cs";
    }
}