using System.Collections.Generic;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;

namespace MiKiNuo.Mvi.Infrastructure.BuildTime.SourceGeneration;

/// <summary>
/// 表示根据实例规约器中带 [MviReduceAttribute] 的方法生成 Reduce 分发逻辑的源生成器。
/// 扫描名称以 "Reducer" 结尾的类，为带特性的实例方法生成分发代码。
/// </summary>
[Generator]
public sealed class MviReducerGenerator : MviReducerGeneratorBase
{
    /// <summary>
    /// 判断指定类是否为生成目标。
    /// </summary>
    /// <param name="symbol">类型符号。</param>
    /// <returns>如果是目标类则返回 true。</returns>
    protected override bool IsTargetClass(INamedTypeSymbol symbol)
    {
        return symbol.Name.EndsWith("Reducer", System.StringComparison.Ordinal);
    }

    /// <summary>
    /// 收集类型中的规约方法信息。
    /// </summary>
    /// <param name="reducerType">类型符号。</param>
    /// <returns>规约方法信息列表。</returns>
    protected override List<ReducerMethodModel> GetReducerMethods(INamedTypeSymbol reducerType)
    {
        List<ReducerMethodModel> result = [];

        foreach (IMethodSymbol method in reducerType.GetMembers().OfType<IMethodSymbol>())
        {
            if (method.IsStatic || method.Parameters.Length != 2)
            {
                continue;
            }

            if (!HasReduceAttribute(method))
            {
                continue;
            }

            if (method.ReturnType is not INamedTypeSymbol returnType || returnType.TypeArguments.Length != 2)
            {
                continue;
            }

            ITypeSymbol stateType = method.Parameters[0].Type;
            ITypeSymbol intentType = method.Parameters[1].Type;
            ITypeSymbol effectType = returnType.TypeArguments[1];
            ITypeSymbol rootIntentType = GetRootIntentType(intentType);

            result.Add(new ReducerMethodModel(
                method.Name,
                stateType.ToDisplayString(GeneratorSyntaxHelpers.FullyQualifiedNullableFormat),
                intentType.ToDisplayString(GeneratorSyntaxHelpers.FullyQualifiedNullableFormat),
                rootIntentType.ToDisplayString(GeneratorSyntaxHelpers.FullyQualifiedNullableFormat),
                effectType.ToDisplayString(GeneratorSyntaxHelpers.FullyQualifiedNullableFormat)));
        }

        return result;
    }

    /// <summary>
    /// 生成目标源码。
    /// </summary>
    /// <param name="reducerType">类型符号。</param>
    /// <param name="methods">规约方法信息列表。</param>
    /// <returns>生成的源码字符串。</returns>
    protected override string GenerateSource(INamedTypeSymbol reducerType, IReadOnlyList<ReducerMethodModel> methods)
    {
        ReducerMethodModel first = methods[0];
        string namespaceName = reducerType.ContainingNamespace.ToDisplayString();
        StringBuilder builder = new();

        builder.AppendLine("// <auto-generated />");
        builder.AppendLine("#nullable enable");
        builder.AppendLine();
        builder.Append("namespace ").Append(namespaceName).AppendLine(";");
        builder.AppendLine();
        builder.AppendLine("/// <summary>");
        builder.AppendLine("/// 表示由 MVI 源生成器生成的实例规约分发逻辑。");
        builder.AppendLine("/// </summary>");
        builder.Append("public sealed partial class ").Append(reducerType.Name).AppendLine();
        builder.AppendLine("{");
        builder.AppendLine("    /// <summary>");
        builder.AppendLine("    /// 执行意图到状态的规约分发。");
        builder.AppendLine("    /// </summary>");
        builder.Append("    public override global::MiKiNuo.Mvi.Domain.MVI.Reducer.MviReduceResult<")
            .Append(first.StateTypeName).Append(", ").Append(first.EffectTypeName).Append("> Reduce(")
            .Append(first.StateTypeName).Append(" state, ").Append(first.RootIntentTypeName).AppendLine(" intent)");
        builder.AppendLine("    {");
        builder.AppendLine("        global::System.ArgumentNullException.ThrowIfNull(state);");
        builder.AppendLine("        global::System.ArgumentNullException.ThrowIfNull(intent);");
        builder.AppendLine();
        builder.AppendLine("        return intent switch");
        builder.AppendLine("        {");
        foreach (ReducerMethodModel method in methods)
        {
            builder.Append("            ").Append(method.IntentTypeName).Append(" typedIntent => ")
                .Append(method.MethodName).AppendLine("(state, typedIntent),");
        }
        builder.Append("            _ => global::MiKiNuo.Mvi.Domain.MVI.Reducer.MviReduceResult.State<")
            .Append(first.StateTypeName).Append(", ").Append(first.EffectTypeName).AppendLine(">(state)");
        builder.AppendLine("        };");
        builder.AppendLine("    }");
        builder.AppendLine("}");
        return builder.ToString();
    }

    /// <summary>
    /// 获取输出文件名。
    /// </summary>
    /// <param name="symbol">类型符号。</param>
    /// <returns>输出文件名。</returns>
    protected override string GetOutputFileName(INamedTypeSymbol symbol)
    {
        return $"{symbol.Name}.g.cs";
    }

    /// <summary>
    /// 判断方法是否标记了规约特性。
    /// </summary>
    private static bool HasReduceAttribute(IMethodSymbol method)
    {
        return GeneratorSyntaxHelpers.HasAttribute(method, "MviReduce", "MviReducer");
    }
}