
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace MiKiNuo.Mvi.Infrastructure.BuildTime.SourceGeneration;

/// <summary>
/// 表示根据 Reducer 方法生成规约分发器的源生成器。
/// </summary>
[Generator]
public sealed class MviReducerDispatcherGenerator : IIncrementalGenerator
{
    private static readonly SymbolDisplayFormat TypeFormat = SymbolDisplayFormat.FullyQualifiedFormat
        .WithMiscellaneousOptions(
            SymbolDisplayMiscellaneousOptions.IncludeNullableReferenceTypeModifier
            | SymbolDisplayMiscellaneousOptions.UseSpecialTypes);

    /// <inheritdoc />
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        context.RegisterSourceOutput(context.CompilationProvider, Execute);
    }

    private static void Execute(SourceProductionContext context, Compilation compilation)
    {
        foreach (INamedTypeSymbol reducersType in FindAllClasses(compilation, context.CancellationToken))
        {
            if (!reducersType.Name.EndsWith("Reducers", StringComparison.Ordinal))
            {
                continue;
            }

            List<ReducerMethodModel> methods = GetReducerMethods(reducersType);
            if (methods.Count == 0)
            {
                continue;
            }

            string source = GenerateDispatcher(reducersType, methods);
            string dispatcherName = reducersType.Name.Substring(0, reducersType.Name.Length - "Reducers".Length) + "ReducerDispatcher";
            context.AddSource($"{dispatcherName}.g.cs", SourceText.From(source, Encoding.UTF8));
        }
    }

    private static string GenerateDispatcher(INamedTypeSymbol reducersType, IReadOnlyList<ReducerMethodModel> methods)
    {
        ReducerMethodModel first = methods[0];
        string namespaceName = reducersType.ContainingNamespace.ToDisplayString();
        string dispatcherName = reducersType.Name.Substring(0, reducersType.Name.Length - "Reducers".Length) + "ReducerDispatcher";
        StringBuilder builder = new();

        builder.AppendLine("// <auto-generated />");
        builder.AppendLine("#nullable enable");
        builder.AppendLine();
        builder.Append("namespace ").Append(namespaceName).AppendLine(";");
        builder.AppendLine();
        builder.AppendLine("/// <summary>");
        builder.AppendLine("/// 表示由 MVI 源生成器生成的规约分发器。");
        builder.AppendLine("/// </summary>");
        builder.Append("public sealed class ").Append(dispatcherName).AppendLine();
        builder.Append("    : global::MiKiNuo.Mvi.Application.MVI.Reducer.IMviReducerDispatcher<")
            .Append(first.StateTypeName).Append(", ").Append(first.RootIntentTypeName).Append(", ").Append(first.EffectTypeName).AppendLine(">");
        builder.AppendLine("{");
        builder.AppendLine("    /// <inheritdoc />");
        builder.Append("    public global::MiKiNuo.Mvi.Domain.MVI.Reducer.MviReduceResult<")
            .Append(first.StateTypeName).Append(", ").Append(first.EffectTypeName).Append("> Reduce(")
            .Append(first.StateTypeName).Append(" state, ").Append(first.RootIntentTypeName).AppendLine(" intent)");
        builder.AppendLine("    {");
        builder.AppendLine("        return intent switch");
        builder.AppendLine("        {");
        foreach (ReducerMethodModel method in methods)
        {
            builder.Append("            ").Append(method.IntentTypeName).Append(" typedIntent => ")
                .Append(reducersType.ToDisplayString(TypeFormat)).Append('.').Append(method.MethodName)
                .AppendLine("(state, typedIntent),");
        }
        builder.Append("            _ => global::MiKiNuo.Mvi.Domain.MVI.Reducer.MviReduceResult.State<")
            .Append(first.StateTypeName).Append(", ").Append(first.EffectTypeName).AppendLine(">(state)");
        builder.AppendLine("        };");
        builder.AppendLine("    }");
        builder.AppendLine("}");
        return builder.ToString();
    }

    private static List<ReducerMethodModel> GetReducerMethods(INamedTypeSymbol reducersType)
    {
        List<ReducerMethodModel> result = new();

        foreach (IMethodSymbol method in reducersType.GetMembers().OfType<IMethodSymbol>())
        {
            if (!method.IsStatic || method.Name != "Reduce" || method.Parameters.Length != 2)
            {
                continue;
            }

            if (method.ReturnType is not INamedTypeSymbol returnType || returnType.TypeArguments.Length != 2)
            {
                continue;
            }

            ITypeSymbol stateType = method.Parameters[0].Type;
            ITypeSymbol intentType = method.Parameters[1].Type;
            ITypeSymbol effectType = returnType.TypeArguments[1];
            ITypeSymbol rootIntentType = GetRootIntentType(intentType);

            result.Add(new ReducerMethodModel(
                method.Name,
                stateType.ToDisplayString(TypeFormat),
                intentType.ToDisplayString(TypeFormat),
                rootIntentType.ToDisplayString(TypeFormat),
                effectType.ToDisplayString(TypeFormat)));
        }

        return result;
    }

    private static ITypeSymbol GetRootIntentType(ITypeSymbol intentType)
    {
        ITypeSymbol current = intentType;
        while (current.BaseType is not null && current.BaseType.SpecialType != SpecialType.System_Object)
        {
            current = current.BaseType;
        }

        return current;
    }

    private static IEnumerable<INamedTypeSymbol> FindAllClasses(Compilation compilation, System.Threading.CancellationToken cancellationToken)
    {
        foreach (SyntaxTree tree in compilation.SyntaxTrees)
        {
            SyntaxNode root = tree.GetRoot(cancellationToken);
            SemanticModel semanticModel = compilation.GetSemanticModel(tree);
            foreach (ClassDeclarationSyntax declaration in root.DescendantNodes().OfType<ClassDeclarationSyntax>())
            {
                cancellationToken.ThrowIfCancellationRequested();
                if (semanticModel.GetDeclaredSymbol(declaration, cancellationToken) is INamedTypeSymbol symbol)
                {
                    yield return symbol;
                }
            }
        }
    }

    private sealed class ReducerMethodModel
    {
        public ReducerMethodModel(
            string methodName,
            string stateTypeName,
            string intentTypeName,
            string rootIntentTypeName,
            string effectTypeName)
        {
            MethodName = methodName;
            StateTypeName = stateTypeName;
            IntentTypeName = intentTypeName;
            RootIntentTypeName = rootIntentTypeName;
            EffectTypeName = effectTypeName;
        }

        public string MethodName { get; }

        public string StateTypeName { get; }

        public string IntentTypeName { get; }

        public string RootIntentTypeName { get; }

        public string EffectTypeName { get; }
    }
}
