
using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace MiKiNuo.Mvi.Infrastructure.BuildTime.SourceGeneration;

/// <summary>
/// 表示根据 MVI 绑定特性生成 ViewModel 重复代码的源生成器。
/// </summary>
[Generator]
public sealed class MviViewModelGenerator : IIncrementalGenerator
{
    private static readonly SymbolDisplayFormat TypeFormat = SymbolDisplayFormat.FullyQualifiedFormat
        .WithMiscellaneousOptions(
            SymbolDisplayMiscellaneousOptions.IncludeNullableReferenceTypeModifier
            | SymbolDisplayMiscellaneousOptions.UseSpecialTypes);

    /// <inheritdoc />
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        context.RegisterSourceOutput(context.CompilationProvider, Execute);
    }

    private static void Execute(SourceProductionContext context, Compilation compilation)
    {
        INamedTypeSymbol? viewModelBaseSymbol = compilation.GetTypeByMetadataName(
            "MiKiNuo.Mvi.Application.MVI.ViewModel.MviViewModelBase`3");

        if (viewModelBaseSymbol is null)
        {
            return;
        }

        foreach (INamedTypeSymbol viewModelSymbol in FindAllClasses(compilation, context.CancellationToken))
        {
            if (!TryGetMviBase(viewModelSymbol, viewModelBaseSymbol, out INamedTypeSymbol? mviBase))
            {
                continue;
            }

            List<BindPropertyModel> bindProperties = GetBindProperties(viewModelSymbol);
            List<CommandPropertyModel> commandProperties = GetCommandProperties(viewModelSymbol);

            if (bindProperties.Count == 0 && commandProperties.Count == 0)
            {
                continue;
            }

            string source = GenerateViewModel(viewModelSymbol, mviBase!, bindProperties, commandProperties);
            context.AddSource($"{viewModelSymbol.Name}.g.cs", SourceText.From(source, Encoding.UTF8));
        }
    }

    private static string GenerateViewModel(
        INamedTypeSymbol viewModelSymbol,
        INamedTypeSymbol mviBase,
        IReadOnlyList<BindPropertyModel> bindProperties,
        IReadOnlyList<CommandPropertyModel> commandProperties)
    {
        string namespaceName = viewModelSymbol.ContainingNamespace.ToDisplayString();
        string className = viewModelSymbol.Name;
        string stateTypeName = mviBase.TypeArguments[0].ToDisplayString(TypeFormat);
        bool hasTwoWay = bindProperties.Any(static property => property.IsTwoWay);
        StringBuilder builder = new();

        builder.AppendLine("// <auto-generated />");
        builder.AppendLine("#nullable enable");
        builder.AppendLine();
        builder.AppendLine("using R3;");
        builder.AppendLine();
        builder.Append("namespace ").Append(namespaceName).AppendLine(";");
        builder.AppendLine();
        builder.AppendLine("/// <summary>");
        builder.AppendLine("/// 表示由 MVI 源生成器生成的 ViewModel 部分。");
        builder.AppendLine("/// </summary>");
        builder.Append("public sealed partial class ").Append(className).AppendLine();
        builder.AppendLine("{");

        foreach (BindPropertyModel property in bindProperties)
        {
            builder.Append("    private ").Append(property.TypeName).Append(' ').Append(property.FieldName).AppendLine(" = default!;");
        }

        foreach (CommandPropertyModel property in commandProperties)
        {
            builder.Append("    private ").Append(property.TypeName).Append(' ').Append(property.FieldName).AppendLine(" = default!;");
        }

        if (hasTwoWay)
        {
            builder.AppendLine("    private bool _isApplyingState;");
        }

        builder.AppendLine();

        foreach (BindPropertyModel property in bindProperties)
        {
            builder.AppendLine("    /// <inheritdoc />");
            builder.Append("    public partial ").Append(property.TypeName).Append(' ').Append(property.Name).AppendLine();
            builder.AppendLine("    {");
            builder.Append("        get => ").Append(property.FieldName).AppendLine(";");
            builder.Append("        ").Append(property.SetterAccessibility).AppendLine();
            builder.AppendLine("        {");
            builder.Append("            if (SetProperty(ref ").Append(property.FieldName).AppendLine(", value)");
            if (property.IsTwoWay)
            {
                builder.AppendLine(" && !_isApplyingState)");
            }
            else
            {
                builder.AppendLine(")");
            }
            builder.AppendLine("            {");
            if (property.IsTwoWay && !string.IsNullOrWhiteSpace(property.IntentTypeName))
            {
                builder.Append("                _ = DispatchAsync(new ").Append(property.IntentTypeName).AppendLine("(value));");
            }
            builder.AppendLine("            }");
            builder.AppendLine("        }");
            builder.AppendLine("    }");
            builder.AppendLine();
        }

        foreach (CommandPropertyModel property in commandProperties)
        {
            builder.AppendLine("    /// <inheritdoc />");
            builder.Append("    public partial ").Append(property.TypeName).Append(' ').Append(property.Name).AppendLine();
            builder.AppendLine("    {");
            builder.Append("        get => ").Append(property.FieldName).AppendLine(";");
            builder.Append("        ").Append(property.SetterAccessibility).AppendLine(" => SetProperty(ref ").Append(property.FieldName).AppendLine(", value);");
            builder.AppendLine("    }");
            builder.AppendLine();
        }

        if (commandProperties.Count > 0)
        {
            builder.AppendLine("    /// <summary>");
            builder.AppendLine("    /// 初始化由源生成器创建的命令。");
            builder.AppendLine("    /// </summary>");
            builder.AppendLine("    private void InitializeGeneratedCommands()");
            builder.AppendLine("    {");
            foreach (CommandPropertyModel command in commandProperties)
            {
                string streamName = ToCamelCase(command.Name) + "CanExecuteStream";
                builder.Append("        Observable<bool> ").Append(streamName).AppendLine(" = Store.States");
                if (string.IsNullOrWhiteSpace(command.CanExecuteProperty))
                {
                    builder.AppendLine("            .Select(static _ => true)");
                }
                else
                {
                    builder.Append("            .Select(static state => state.").Append(command.CanExecuteProperty).AppendLine(")");
                }
                builder.AppendLine("            .DistinctUntilChanged();");
                builder.AppendLine();

                if (command.IsAsync)
                {
                    builder.Append("        ").Append(command.Name).Append(" = new global::MiKiNuo.Mvi.Application.MVI.Command.MviAsyncCommand(").AppendLine();
                    builder.Append("            ").Append(streamName).AppendLine(",");
                    builder.Append("            (_, cancellationToken) => DispatchAsync(new ").Append(command.IntentTypeName).AppendLine("(), cancellationToken));");
                }
                else
                {
                    builder.Append("        ").Append(command.Name).Append(" = new global::MiKiNuo.Mvi.Application.MVI.Command.MviCommand(").AppendLine();
                    builder.Append("            ").Append(streamName).AppendLine(",");
                    builder.Append("            _ => _ = DispatchAsync(new ").Append(command.IntentTypeName).AppendLine("()));");
                }
                builder.AppendLine();
            }
            builder.AppendLine("    }");
            builder.AppendLine();
        }

        builder.AppendLine("    /// <inheritdoc />");
        builder.Append("    protected override void ApplyStateCore(").Append(stateTypeName).AppendLine(" state)");
        builder.AppendLine("    {");
        if (hasTwoWay)
        {
            builder.AppendLine("        _isApplyingState = true;");
            builder.AppendLine();
            builder.AppendLine("        try");
            builder.AppendLine("        {");
        }

        string indent = hasTwoWay ? "            " : "        ";
        foreach (BindPropertyModel property in bindProperties)
        {
            builder.Append(indent).Append(property.Name).Append(" = state.").Append(property.StatePropertyName).AppendLine(";");
        }

        if (hasTwoWay)
        {
            builder.AppendLine("        }");
            builder.AppendLine("        finally");
            builder.AppendLine("        {");
            builder.AppendLine("            _isApplyingState = false;");
            builder.AppendLine("        }");
        }
        builder.AppendLine("    }");

        if (commandProperties.Count > 0)
        {
            builder.AppendLine();
            builder.AppendLine("    /// <inheritdoc />");
            builder.AppendLine("    protected override void DisposeManagedResources()");
            builder.AppendLine("    {");
            for (int commandIndex = 0; commandIndex < commandProperties.Count; commandIndex++)
            {
                CommandPropertyModel command = commandProperties[commandIndex];
                string disposableVariableName = "disposable" + commandIndex.ToString(System.Globalization.CultureInfo.InvariantCulture);

                builder.Append("        if (").Append(command.Name).Append(" is global::System.IDisposable ").Append(disposableVariableName).AppendLine(")");
                builder.AppendLine("        {");
                builder.Append("            ").Append(disposableVariableName).AppendLine(".Dispose();");
                builder.AppendLine("        }");
            }
            builder.AppendLine("    }");
        }

        builder.AppendLine("}");
        return builder.ToString();
    }

    private static List<BindPropertyModel> GetBindProperties(INamedTypeSymbol viewModelSymbol)
    {
        List<BindPropertyModel> result = new();

        foreach (IPropertySymbol property in viewModelSymbol.GetMembers().OfType<IPropertySymbol>())
        {
            AttributeData? attribute = property.GetAttributes().FirstOrDefault(static item => item.AttributeClass?.Name == "MviBindAttribute");
            if (attribute is null)
            {
                continue;
            }

            string stateProperty = attribute.ConstructorArguments.Length > 0
                ? attribute.ConstructorArguments[0].Value?.ToString() ?? property.Name
                : property.Name;
            bool isTwoWay = false;
            string? intentTypeName = null;

            foreach (KeyValuePair<string, TypedConstant> namedArgument in attribute.NamedArguments)
            {
                if (namedArgument.Key == "BindingMode")
                {
                    isTwoWay = namedArgument.Value.Value?.ToString() == "1";
                }
                else if (namedArgument.Key == "IntentType" && namedArgument.Value.Value is INamedTypeSymbol intentType)
                {
                    intentTypeName = intentType.ToDisplayString(TypeFormat);
                }
            }

            result.Add(new BindPropertyModel(
                property.Name,
                property.Type.ToDisplayString(TypeFormat),
                stateProperty,
                intentTypeName,
                isTwoWay,
                GetSetterAccessibility(property),
                "_" + ToCamelCase(property.Name)));
        }

        return result;
    }

    private static List<CommandPropertyModel> GetCommandProperties(INamedTypeSymbol viewModelSymbol)
    {
        List<CommandPropertyModel> result = new();

        foreach (IPropertySymbol property in viewModelSymbol.GetMembers().OfType<IPropertySymbol>())
        {
            AttributeData? attribute = property.GetAttributes().FirstOrDefault(static item => item.AttributeClass?.Name == "MviCommandAttribute");
            if (attribute is null || attribute.ConstructorArguments.Length == 0 || attribute.ConstructorArguments[0].Value is not INamedTypeSymbol intentType)
            {
                continue;
            }

            string? canExecuteProperty = null;
            bool isAsync = false;
            foreach (KeyValuePair<string, TypedConstant> namedArgument in attribute.NamedArguments)
            {
                if (namedArgument.Key == "CanExecuteProperty")
                {
                    canExecuteProperty = namedArgument.Value.Value?.ToString();
                }
                else if (namedArgument.Key == "IsAsync")
                {
                    isAsync = namedArgument.Value.Value is true;
                }
            }

            result.Add(new CommandPropertyModel(
                property.Name,
                property.Type.ToDisplayString(TypeFormat),
                intentType.ToDisplayString(TypeFormat),
                canExecuteProperty,
                isAsync,
                GetSetterAccessibility(property),
                "_" + ToCamelCase(property.Name)));
        }

        return result;
    }

    private static string GetSetterAccessibility(IPropertySymbol property)
    {
        Accessibility accessibility = property.SetMethod?.DeclaredAccessibility ?? Accessibility.Private;
        return accessibility == Accessibility.Private ? "private set" : "set";
    }

    private static bool TryGetMviBase(
        INamedTypeSymbol typeSymbol,
        INamedTypeSymbol viewModelBaseSymbol,
        out INamedTypeSymbol? mviBase)
    {
        INamedTypeSymbol? current = typeSymbol.BaseType;
        while (current is not null)
        {
            if (SymbolEqualityComparer.Default.Equals(current.OriginalDefinition, viewModelBaseSymbol))
            {
                mviBase = current;
                return true;
            }

            current = current.BaseType;
        }

        mviBase = null;
        return false;
    }

    private static IEnumerable<INamedTypeSymbol> FindAllClasses(Compilation compilation, System.Threading.CancellationToken cancellationToken)
    {
        foreach (SyntaxTree tree in compilation.SyntaxTrees)
        {
            SyntaxNode root = tree.GetRoot(cancellationToken);
            SemanticModel semanticModel = compilation.GetSemanticModel(tree);
            foreach (ClassDeclarationSyntax declaration in root.DescendantNodes().OfType<ClassDeclarationSyntax>())
            {
                cancellationToken.ThrowIfCancellationRequested();
                if (semanticModel.GetDeclaredSymbol(declaration, cancellationToken) is INamedTypeSymbol symbol)
                {
                    yield return symbol;
                }
            }
        }
    }

    private static string ToCamelCase(string value)
    {
        if (string.IsNullOrEmpty(value))
        {
            return value;
        }

        return value.Length == 1
            ? value.ToLowerInvariant()
            : char.ToLowerInvariant(value[0]) + value.Substring(1);
    }

    private sealed class BindPropertyModel
    {
        public BindPropertyModel(
            string name,
            string typeName,
            string statePropertyName,
            string? intentTypeName,
            bool isTwoWay,
            string setterAccessibility,
            string fieldName)
        {
            Name = name;
            TypeName = typeName;
            StatePropertyName = statePropertyName;
            IntentTypeName = intentTypeName;
            IsTwoWay = isTwoWay;
            SetterAccessibility = setterAccessibility;
            FieldName = fieldName;
        }

        public string Name { get; }

        public string TypeName { get; }

        public string StatePropertyName { get; }

        public string? IntentTypeName { get; }

        public bool IsTwoWay { get; }

        public string SetterAccessibility { get; }

        public string FieldName { get; }
    }

    private sealed class CommandPropertyModel
    {
        public CommandPropertyModel(
            string name,
            string typeName,
            string intentTypeName,
            string? canExecuteProperty,
            bool isAsync,
            string setterAccessibility,
            string fieldName)
        {
            Name = name;
            TypeName = typeName;
            IntentTypeName = intentTypeName;
            CanExecuteProperty = canExecuteProperty;
            IsAsync = isAsync;
            SetterAccessibility = setterAccessibility;
            FieldName = fieldName;
        }

        public string Name { get; }

        public string TypeName { get; }

        public string IntentTypeName { get; }

        public string? CanExecuteProperty { get; }

        public bool IsAsync { get; }

        public string SetterAccessibility { get; }

        public string FieldName { get; }
    }
}
