using System.Collections.Generic;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;

namespace MiKiNuo.Mvi.Infrastructure.BuildTime.SourceGeneration;

/// <summary>
/// 表示 <see cref="MviViewModelGenerator"/> 的代码发射阶段：
/// 接收 <see cref="MviViewModelModels.ViewModelDescriptor"/>，生成 ViewModel partial 类源码字符串。
/// </summary>
internal static class MviViewModelEmission
{
    /// <summary>
    /// 为单个 ViewModel 描述生成 partial 类源码。
    /// </summary>
    /// <param name="descriptor">ViewModel 描述。</param>
    /// <returns>生成的 C# 源码。</returns>
    public static string Emit(MviViewModelModels.ViewModelDescriptor descriptor)
    {
        INamedTypeSymbol viewModelSymbol = descriptor.ViewModelSymbol;
        INamedTypeSymbol mviBase = descriptor.MviBase;
        IReadOnlyList<MviViewModelModels.BindPropertyModel> bindProperties = descriptor.BindProperties;
        IReadOnlyList<MviViewModelModels.CommandPropertyModel> commandProperties = descriptor.CommandProperties;

        string namespaceName = viewModelSymbol.ContainingNamespace.ToDisplayString();
        string className = viewModelSymbol.Name;
        string stateTypeName = mviBase.TypeArguments[0].ToDisplayString(GeneratorSyntaxHelpers.FullyQualifiedNullableFormat);
        string intentBaseTypeName = mviBase.TypeArguments[1].ToDisplayString(GeneratorSyntaxHelpers.FullyQualifiedNullableFormat);
        bool hasTwoWay = bindProperties.Any(static property => property.IsTwoWay);
        StringBuilder builder = new();

        EmitClassDeclaration(builder, namespaceName, className, bindProperties, commandProperties, hasTwoWay);
        EmitBindProperties(builder, bindProperties);
        EmitCommandProperties(builder, commandProperties);

        if (commandProperties.Count > 0)
        {
            EmitInitializeCommands(builder, commandProperties);
            EmitIntentFactory(builder, intentBaseTypeName, commandProperties);
        }

        EmitStateMapping(builder, stateTypeName, bindProperties, hasTwoWay);

        if (commandProperties.Count > 0)
        {
            EmitDispose(builder, commandProperties);
        }

        builder.AppendLine("}");
        return builder.ToString();
    }

    /// <summary>
    /// 发射文件头、命名空间、类声明与字段。
    /// </summary>
    private static void EmitClassDeclaration(
        StringBuilder builder,
        string namespaceName,
        string className,
        IReadOnlyList<MviViewModelModels.BindPropertyModel> bindProperties,
        IReadOnlyList<MviViewModelModels.CommandPropertyModel> commandProperties,
        bool hasTwoWay)
    {
        builder.AppendLine("// <auto-generated />");
        builder.AppendLine("#nullable enable");
        builder.AppendLine();
        builder.AppendLine("using R3;");
        builder.AppendLine();
        builder.Append("namespace ").Append(namespaceName).AppendLine(";");
        builder.AppendLine();
        builder.AppendLine("/// <summary>");
        builder.AppendLine("/// 表示由 MVI 源生成器生成的 ViewModel 部分。");
        builder.AppendLine("/// </summary>");
        builder.Append("public sealed partial class ").Append(className).AppendLine();
        builder.AppendLine("{");

        foreach (MviViewModelModels.BindPropertyModel property in bindProperties)
        {
            builder.Append("    private ").Append(property.TypeName).Append(' ').Append(property.FieldName).AppendLine(" = default!;");
        }

        foreach (MviViewModelModels.CommandPropertyModel property in commandProperties)
        {
            builder.Append("    private ").Append(property.TypeName).Append(' ').Append(property.FieldName).AppendLine(" = default!;");
        }

        if (hasTwoWay)
        {
            builder.AppendLine("    private bool _isApplyingState;");
        }

        builder.AppendLine();
    }

    /// <summary>
    /// 发射所有绑定属性。
    /// </summary>
    private static void EmitBindProperties(
        StringBuilder builder,
        IReadOnlyList<MviViewModelModels.BindPropertyModel> bindProperties)
    {
        foreach (MviViewModelModels.BindPropertyModel property in bindProperties)
        {
            AppendBindProperty(builder, property);
        }
    }

    /// <summary>
    /// 发射所有命令属性。
    /// </summary>
    private static void EmitCommandProperties(
        StringBuilder builder,
        IReadOnlyList<MviViewModelModels.CommandPropertyModel> commandProperties)
    {
        foreach (MviViewModelModels.CommandPropertyModel property in commandProperties)
        {
            AppendCommandProperty(builder, property);
        }
    }

    /// <summary>
    /// 发射命令初始化方法。
    /// </summary>
    private static void EmitInitializeCommands(
        StringBuilder builder,
        IReadOnlyList<MviViewModelModels.CommandPropertyModel> commandProperties)
    {
        builder.AppendLine("    /// <summary>");
        builder.AppendLine("    /// 初始化由源生成器创建的命令。");
        builder.AppendLine("    /// </summary>");
        builder.AppendLine("    private void InitializeGeneratedCommands()");
        builder.AppendLine("    {");
        foreach (MviViewModelModels.CommandPropertyModel command in commandProperties)
        {
            string streamName = GeneratorSyntaxHelpers.ToCamelCase(command.Name) + "CanExecuteStream";
            builder.Append("        Observable<bool> ").Append(streamName).AppendLine(" = Store.States");
            if (string.IsNullOrWhiteSpace(command.CanExecuteProperty))
            {
                builder.AppendLine("            .Select(static _ => true)");
            }
            else
            {
                builder.Append("            .Select(static state => state.").Append(command.CanExecuteProperty).AppendLine(")");
            }

            builder.AppendLine("            .DistinctUntilChanged();");
            builder.AppendLine();

            if (command.IsAsync)
            {
                builder.Append("        ").Append(command.Name).Append(" = new global::MiKiNuo.Mvi.Application.MVI.Command.MviAsyncCommand(").AppendLine();
                builder.Append("            ").Append(streamName).AppendLine(",");
                builder.Append("            (payload, cancellationToken) => DispatchAsync(Create").Append(command.Name).AppendLine("Intent(payload), cancellationToken),");
                builder.Append("            UiDispatcher);").AppendLine();
            }
            else
            {
                builder.Append("        ").Append(command.Name).Append(" = new global::MiKiNuo.Mvi.Application.MVI.Command.MviCommand(").AppendLine();
                builder.Append("            ").Append(streamName).AppendLine(",");
                builder.Append("            payload => _ = DispatchAsync(Create").Append(command.Name).AppendLine("Intent(payload)),");
                builder.Append("            UiDispatcher);").AppendLine();
            }

            builder.AppendLine();
        }

        builder.AppendLine("    }");
        builder.AppendLine();
    }

    /// <summary>
    /// 发射所有 Intent 工厂方法。
    /// </summary>
    private static void EmitIntentFactory(
        StringBuilder builder,
        string intentBaseTypeName,
        IReadOnlyList<MviViewModelModels.CommandPropertyModel> commandProperties)
    {
        foreach (MviViewModelModels.CommandPropertyModel command in commandProperties)
        {
            AppendCreateIntentMethod(builder, intentBaseTypeName, command);
        }
    }

    private static void AppendBindProperty(StringBuilder builder, MviViewModelModels.BindPropertyModel property)
    {
        builder.AppendLine("    /// <summary>");
        builder.AppendLine("    /// 获取或设置属性值并通知变更。");
        builder.AppendLine("    /// </summary>");
        builder.Append("    public partial ").Append(property.TypeName).Append(' ').Append(property.Name).AppendLine();
        builder.AppendLine("    {");
        builder.Append("        get => ").Append(property.FieldName).AppendLine(";");
        builder.Append("        ").Append(property.SetterAccessibility).AppendLine();
        builder.AppendLine("        {");
        builder.Append("            if (SetProperty(ref ").Append(property.FieldName).AppendLine(", value)");
        if (property.IsTwoWay)
        {
            builder.AppendLine(" && !_isApplyingState)");
        }
        else
        {
            builder.AppendLine(")");
        }

        builder.AppendLine("            {");
        if (property.IsTwoWay && !string.IsNullOrWhiteSpace(property.IntentTypeName))
        {
            builder.Append("                _ = DispatchAsync(new ").Append(property.IntentTypeName).AppendLine("(value));");
        }

        builder.AppendLine("            }");
        builder.AppendLine("        }");
        builder.AppendLine("    }");
        builder.AppendLine();
    }

    private static void AppendCommandProperty(StringBuilder builder, MviViewModelModels.CommandPropertyModel property)
    {
        builder.AppendLine("    /// <summary>");
        builder.AppendLine("    /// 获取命令实例。");
        builder.AppendLine("    /// </summary>");
        builder.Append("    public partial ").Append(property.TypeName).Append(' ').Append(property.Name).AppendLine();
        builder.AppendLine("    {");
        builder.Append("        get => ").Append(property.FieldName).AppendLine(";");
        builder.Append("        ").Append(property.SetterAccessibility).AppendLine(" => SetProperty(ref ").Append(property.FieldName).AppendLine(", value);");
        builder.AppendLine("    }");
        builder.AppendLine();
    }

    private static void AppendCreateIntentMethod(
        StringBuilder builder,
        string intentBaseTypeName,
        MviViewModelModels.CommandPropertyModel command)
    {
        builder.AppendLine("    /// <summary>");
        builder.Append("    /// 创建 ").Append(command.Name).AppendLine(" 对应的 Intent。");
        builder.AppendLine("    /// </summary>");
        builder.AppendLine("    /// <param name=\"payload\">命令载荷。</param>");
        builder.AppendLine("    /// <returns>创建的 Intent。</returns>");
        builder.Append("    private ").Append(intentBaseTypeName).Append(" Create").Append(command.Name).AppendLine("Intent(object? payload)");
        builder.AppendLine("    {");

        if (command.HasParameterlessConstructor)
        {
            builder.AppendLine("        if (payload is null)");
            builder.AppendLine("        {");
            builder.Append("            return new ").Append(command.IntentTypeName).AppendLine("();");
            builder.AppendLine("        }");
            builder.AppendLine();
        }

        if (!string.IsNullOrWhiteSpace(command.PayloadTypeName))
        {
            builder.Append("        if (payload is ").Append(command.PayloadTypeName).AppendLine(" payloadValue)");
            builder.AppendLine("        {");
            builder.Append("            return new ").Append(command.IntentTypeName).AppendLine("(payloadValue);");
            builder.AppendLine("        }");
            builder.AppendLine();
        }

        builder.Append("        throw new global::System.InvalidOperationException(\"命令 ")
            .Append(command.Name)
            .Append(" 无法用当前 payload 创建 Intent ")
            .Append(command.IntentTypeName.Replace("\"", "\\\""))
            .AppendLine("。\");");
        builder.AppendLine("    }");
        builder.AppendLine();
    }

    /// <summary>
    /// 发射状态映射方法。
    /// </summary>
    private static void EmitStateMapping(
        StringBuilder builder,
        string stateTypeName,
        IReadOnlyList<MviViewModelModels.BindPropertyModel> bindProperties,
        bool hasTwoWay)
    {
        builder.AppendLine("    /// <summary>");
        builder.AppendLine("    /// 映射状态到 ViewModel 属性。");
        builder.AppendLine("    /// </summary>");
        builder.Append("    protected override void ApplyStateCore(").Append(stateTypeName).AppendLine(" state)");
        builder.AppendLine("    {");
        if (hasTwoWay)
        {
            builder.AppendLine("        _isApplyingState = true;");
            builder.AppendLine();
            builder.AppendLine("        try");
            builder.AppendLine("        {");
        }

        string indent = hasTwoWay ? "            " : "        ";
        foreach (MviViewModelModels.BindPropertyModel property in bindProperties)
        {
            builder.Append(indent).Append(property.Name).Append(" = state.").Append(property.StatePropertyName).AppendLine(";");
        }

        if (hasTwoWay)
        {
            builder.AppendLine("        }");
            builder.AppendLine("        finally");
            builder.AppendLine("        {");
            builder.AppendLine("            _isApplyingState = false;");
            builder.AppendLine("        }");
        }

        builder.AppendLine("    }");
    }

    /// <summary>
    /// 发射资源释放方法。
    /// </summary>
    private static void EmitDispose(
        StringBuilder builder,
        IReadOnlyList<MviViewModelModels.CommandPropertyModel> commandProperties)
    {
        builder.AppendLine();
        builder.AppendLine("    /// <summary>");
        builder.AppendLine("    /// 释放命令资源。");
        builder.AppendLine("    /// </summary>");
        builder.AppendLine("    protected override void DisposeManagedResources()");
        builder.AppendLine("    {");
        for (int commandIndex = 0; commandIndex < commandProperties.Count; commandIndex++)
        {
            MviViewModelModels.CommandPropertyModel command = commandProperties[commandIndex];
            string disposableVariableName = "disposable" + commandIndex.ToString(System.Globalization.CultureInfo.InvariantCulture);

            builder.Append("        if (").Append(command.Name).Append(" is global::System.IDisposable ").Append(disposableVariableName).AppendLine(")");
            builder.AppendLine("        {");
            builder.Append("            ").Append(disposableVariableName).AppendLine(".Dispose();");
            builder.AppendLine("        }");
        }

        builder.AppendLine("    }");
    }
}
