<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <PackageId>MiKiNuo.Mvi.Avalonia</PackageId>
    <Description>Avalonia views and input adapters for MiKiNuo MVI.</Description>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../MiKiNuo.Mvi/MiKiNuo.Mvi.csproj" />
    <PackageReference Include="Avalonia" />
  </ItemGroup>
</Project>
